In [1]:
#Import libraries
#LOAD MODULES
import tensorflow as tf

assert tf.__version__.startswith('2')
from os import listdir
import numpy as np
#import segmentation_models as sm
import cv2

#sm.set_framework('tf.keras')
#sm.framework()
from PIL import Image
import tensorflow as tf
from scipy import ndimage
import pandas as pd

import copy
import tensorflow_addons as tfa
import matplotlib.pyplot as plt
from keras import backend as K
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
import random
import copy

import openpyxl
import sys
import os

import traceback

import seaborn as sns

resize_coeff=1
patch_size = (256, 256)
const_outside = 0.626
clip_val = -0.1


model_path = "model_further_21.keras"
overall_path = '/Volumes/Expansion/AI2 results 20240119/'

/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning:

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP).

For more information see: https://github.com/tensorflow/addons/issues/2807

  warnings.warn(

In [2]:
#Load the annotation
c1_temp = {'/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-1/1.png': (965,
  950),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-1/2.png': (990,
  925),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-1/3.png': (955,
  960),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-1/4.png': (1045,
  930),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-2/1.png': (935,
  750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-2/2.png': (965,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-2/3.png': (1010,
  825),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-2/4.png': (980,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-3/1.png': (892,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-3/2.png': (952,
  777),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-3/3.png': (990,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-3/4.png': (937,
  812),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-4/1.png': (1002,
  884),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-4/2.png': (910,
  837),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-4/3.png': (967,
  815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-4/4.png': (920,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-5/1.png': (975,
  715),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-5/2.png': (915,
  757),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-5/3.png': (990,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-5/4.png': (896,
  817),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-6/1.png': (1035,
  927),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-6/2.png': (940,
  895),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-6/3.png': (1020,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-6/4.png': (893,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-1/1.png': (980,
  876),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-1/2.png': (1105,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-1/3.png': (1143,
  970),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-1/4.png': (1065,
  973),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-2/1.png': (850,
  862),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-2/2.png': (915,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-2/3.png': (995,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-2/4.png': (910,
  917),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-3/1.png': (735,
  760),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-3/2.png': (785,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-3/3.png': (960,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-3/4.png': (965,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-4/1.png': (930,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-4/2.png': (970,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-4/3.png': (1060,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-4/4.png': (980,
  890),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-5/1.png': (840,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-5/2.png': (890,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-5/3.png': (1055,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-5/4.png': (1180,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-6/1.png': (910,
  750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-6/2.png': (950,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-6/3.png': (1100,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-6/4.png': (1140,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-7/1.png': (975,
  895),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-7/2.png': (1055,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-7/3.png': (1225,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-7/4.png': (1225,
  835),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-8/1.png': (970,
  1000),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-8/2.png': (1050,
  965),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-8/3.png': (1080,
  920),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-8/4.png': (970,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-9/1.png': (1045,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-9/2.png': (1140,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-9/3.png': (1165,
  815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-9/4.png': (1110,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-10/1.png': (925,
  995),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-10/2.png': (1140,
  940),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-10/3.png': (1120,
  875),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-10/4.png': (930,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-1/1.png': (975,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-1/2.png': (975,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-1/3.png': (947,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-1/4.png': (1117,
  797),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-2/1.png': (987,
  865),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-2/2.png': (982,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-2/3.png': (1022,
  825),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-2/4.png': (1105,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-3/1.png': (990,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-3/2.png': (1015,
  815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-3/3.png': (1010,
  817),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-3/4.png': (1112,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-4/1.png': (875,
  827),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-4/2.png': (892,
  835),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-4/3.png': (930,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-4/4.png': (980,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-5/1.png': (1030,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-5/2.png': (985,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-5/3.png': (915,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-5/4.png': (977,
  875),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-6/1.png': (895,
  905),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-6/2.png': (970,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-6/3.png': (995,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-6/4.png': (1027,
  807),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-7/1.png': (900,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-7/2.png': (810,
  815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-7/3.png': (955,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-7/4.png': (920,
  890),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-8/1.png': (990,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-8/2.png': (885,
  885),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-8/3.png': (1025,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-8/4.png': (975,
  895),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-9/1.png': (875,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-9/2.png': (780,
  740),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-9/3.png': (910,
  735),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-9/4.png': (852,
  747),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-10/1.png': (865,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-10/2.png': (790,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-10/3.png': (902,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-10/4.png': (900,
  760),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-11/1.png': (940,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-11/2.png': (910,
  865),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-11/3.png': (940,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-11/4.png': (975,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-1/1.png': (1070,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-1/2.png': (1075,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-1/3.png': (1045,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-1/4.png': (1040,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-2/1.png': (1032,
  725),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-2/2.png': (1052,
  717),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-2/3.png': (1025,
  725),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-2/4.png': (1035,
  705),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-3/1.png': (1010,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-3/2.png': (1040,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-3/3.png': (987,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-3/4.png': (1005,
  720),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-4/1.png': (985,
  895),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-4/2.png': (1017,
  912),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-4/3.png': (970,
  902),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-4/4.png': (980,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-5/1.png': (980,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-5/2.png': (1010,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-5/3.png': (965,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-5/4.png': (970,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-6/1.png': (1060,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-6/2.png': (995,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-6/3.png': (970,
  835),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-6/4.png': (960,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-7/1.png': (1005,
  740),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-7/2.png': (1015,
  760),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-7/3.png': (1060,
  785),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-7/4.png': (1040,
  785),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-8/1.png': (1005,
  700),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-8/2.png': (980,
  710),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-8/3.png': (1005,
  690),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-8/4.png': (980,
  720),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-9/1.png': (1000,
  742),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-9/2.png': (1000,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-9/3.png': (1000,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-9/4.png': (910,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-10/1.png': (990,
  725),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-10/2.png': (1000,
  705),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-10/3.png': (980,
  670),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-10/4.png': (900,
  685),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-11/1.png': (975,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-11/2.png': (980,
  875),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-11/3.png': (965,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-11/4.png': (780,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-12/1.png': (950,
  925),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-12/2.png': (955,
  900),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-12/3.png': (975,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-12/4.png': (735,
  795),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-1/1.png': (890,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-1/2.png': (942,
  920),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-1/3.png': (965,
  835),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-1/4.png': (930,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-2/1.png': (882,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-2/2.png': (925,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-2/3.png': (930,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-2/4.png': (1040,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-3/1.png': (1010,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-3/2.png': (860,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-3/3.png': (950,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-3/4.png': (870,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-4/1.png': (955,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-4/2.png': (900,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-4/3.png': (900,
  750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-4/4.png': (920,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-5/1.png': (1035,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-5/2.png': (1010,
  920),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-5/3.png': (910,
  865),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-5/4.png': (1000,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-6/1.png': (970,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-6/2.png': (1020,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-6/3.png': (910,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-6/4.png': (960,
  825),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-7/1.png': (840,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-7/2.png': (890,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-7/3.png': (770,
  847),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-7/4.png': (840,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-8/1.png': (835,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-8/2.png': (920,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-8/3.png': (840,
  795),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-8/4.png': (840,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-9/1.png': (840,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-9/2.png': (890,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-9/3.png': (890,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-9/4.png': (930,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-10/1.png': (800,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-10/2.png': (790,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-10/3.png': (860,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-10/4.png': (910,
  740),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-11/1.png': (830,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-11/2.png': (910,
  940),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-11/3.png': (880,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-11/4.png': (940,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-12/1.png': (840,
  900),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-12/2.png': (830,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-12/3.png': (830,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-12/4.png': (870,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-1/1.png': (1015,
  895),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-1/2.png': (920,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-1/3.png': (940,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-1/4.png': (1050,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-2/1.png': (970,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-2/2.png': (890,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-2/3.png': (900,
  890),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-2/4.png': (1040,
  890),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-3/1.png': (880,
  930),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-3/2.png': (840,
  940),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-3/3.png': (850,
  940),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-3/4.png': (1000,
  905),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-4/1.png': (830,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-4/2.png': (800,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-4/3.png': (815,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-4/4.png': (1050,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-5/1.png': (750,
  920),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-5/2.png': (705,
  885),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-5/3.png': (770,
  885),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-5/4.png': (1000,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-6/1.png': (940,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-6/2.png': (890,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-6/3.png': (730,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-6/4.png': (1000,
  705),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-7/1.png': (950,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-7/2.png': (950,
  865),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-7/3.png': (950,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-7/4.png': (1090,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-8/1.png': (925,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-8/2.png': (875,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-8/3.png': (930,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-8/4.png': (1145,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-9/1.png': (975,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-9/2.png': (905,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-9/3.png': (1040,
  940),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-9/4.png': (1140,
  930),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-10/1.png': (1040,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-10/2.png': (960,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-10/3.png': (1000,
  760),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-10/4.png': (1160,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-11/1.png': (1080,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-11/2.png': (950,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-11/3.png': (960,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-11/4.png': (1120,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-12/1.png': (1110,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-12/2.png': (1100,
  890),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-12/3.png': (1030,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-12/4.png': (1060,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-1/1.png': (980,
  740),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-1/2.png': (1020,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-1/3.png': (1010,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-1/4.png': (1000,
  815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-2/1.png': (950,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-2/2.png': (990,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-2/3.png': (1010,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-2/4.png': (1070,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-3/1.png': (985,
  750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-3/2.png': (965,
  750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-3/3.png': (1070,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-3/4.png': (1055,
  815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-4/1.png': (1090,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-4/2.png': (1090,
  785),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-4/3.png': (1060,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-4/4.png': (1100,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-5/1.png': (1010,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-5/2.png': (1070,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-5/3.png': (950,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-5/4.png': (1060,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-6/1.png': (1030,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-6/2.png': (1010,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-6/3.png': (1040,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-6/4.png': (1035,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-7/1.png': (920,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-7/2.png': (940,
  795),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-7/3.png': (1080,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-7/4.png': (1020,
  720),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-8/1.png': (850,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-8/2.png': (940,
  765),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-8/3.png': (830,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-8/4.png': (980,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-9/1.png': (830,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-9/2.png': (905,
  745),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-9/3.png': (800,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-9/4.png': (905,
  740),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-10/1.png': (880,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-10/2.png': (980,
  765),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-10/3.png': (915,
  715),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-10/4.png': (870,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-11/1.png': (705,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-11/2.png': (835,
  745),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-11/3.png': (910,
  700),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-11/4.png': (805,
  750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-12/1.png': (690,
  847),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-12/2.png': (860,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-12/3.png': (840,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-12/4.png': (805,
  710),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-1/1.png': (1070,
  865),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-1/2.png': (1155,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-1/3.png': (1223,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-1/4.png': (875,
  815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-2/1.png': (1080,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-2/2.png': (0,
  0),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-2/3.png': (1210,
  750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-2/4.png': (915,
  715),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-3/1.png': (935,
  720),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-3/2.png': (1060,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-3/3.png': (1190,
  785),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-3/4.png': (1170,
  750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-5/1.png': (900,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-5/2.png': (770,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-5/3.png': (915,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-5/4.png': (945,
  750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-6/1.png': (985,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-6/2.png': (910,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-6/3.png': (1045,
  795),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-6/4.png': (1060,
  720),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-7/1.png': (1075,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-7/2.png': (1065,
  965),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-7/3.png': (1155,
  950),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-7/4.png': (1185,
  925),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-8/1.png': (1125,
  995),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-8/2.png': (1090,
  1000),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-8/3.png': (1210,
  985),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-8/4.png': (960,
  925),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-9/1.png': (1080,
  990),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-9/2.png': (1165,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-9/3.png': (1170,
  960),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-9/4.png': (1115,
  905),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-10/1.png': (1075,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-10/2.png': (0,
  0),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-10/3.png': (1150,
  960),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-10/4.png': (1185,
  922),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-11/1.png': (1085,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-11/2.png': (1010,
  760),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-11/3.png': (1110,
  995),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-11/4.png': (1145,
  965),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-12/1.png': (1085,
  940),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-12/2.png': (0,
  0),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-12/3.png': (1075,
  905),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-12/4.png': (1135,
  870), 
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-1/1.png':(820, 805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-1/2.png':(760, 800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-1/3.png':(860, 800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-1/4.png':(860, 850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-2/1.png':(750, 750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-2/2.png':(770, 770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-2/3.png':(930, 750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-2/4.png':(840, 820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-3/1.png':(720, 710),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-3/2.png':(800, 840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-3/3.png':(1000, 830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-3/4.png':(940, 850),             
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-4/1.png':(860, 820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-4/2.png':(780, 820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-4/3.png':(1150, 1000),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-4/4.png':(1030, 960),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-5/1.png':(765, 750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-5/2.png':(870, 900),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-5/3.png':(1020, 860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-5/4.png':(1065, 860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-6/1.png':(825, 835),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-6/2.png':(820, 855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-6/3.png':(1005, 780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-6/4.png':(980, 865),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-7/1.png':(925, 875),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-7/2.png':(955, 810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-7/3.png':(1045, 750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-7/4.png':(1030, 900),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-8/1.png':(1075, 870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-8/2.png':(1085, 820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-8/3.png':(1200, 970),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-8/4.png':(1135, 930),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-9/1.png':(985, 1000),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-9/2.png':(925, 950),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-9/3.png':(1000, 940),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-9/4.png':(1015, 910),             
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-10/1.png':(810, 975),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-10/2.png':(955, 875),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-10/3.png':(1015, 890),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-10/4.png':(1060, 825),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-11/1.png':(780, 990),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-11/2.png':(890, 940),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-11/3.png':(1005, 900),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-11/4.png':(990, 810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-12/1.png':(820, 910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-12/2.png':(820, 830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-12/3.png':(900, 770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-12/4.png':(870, 690)}

c2_temp = {'/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-1/1.png': (977,
  978),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-1/2.png': (975,
  930),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-1/3.png': (945,
  965),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-1/4.png': (1040,
  930),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-2/1.png': (937,
  748),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-2/2.png': (955,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-2/3.png': (1000,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-2/4.png': (985,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-3/1.png': (888,
  798),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-3/2.png': (942,
  795),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-3/3.png': (998,
  785),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-3/4.png': (953,
  838),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-4/1.png': (1015,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-4/2.png': (947,
  832),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-4/3.png': (970,
  795),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-4/4.png': (945,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-5/1.png': (985,
  720),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-5/2.png': (904,
  753),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-5/3.png': (985,
  785),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-5/4.png': (890,
  813),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-6/1.png': (1022,
  930),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-6/2.png': (945,
  890),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-6/3.png': (1035,
  872),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220617/profilometer/before/4-1-6/4.png': (930,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-1/1.png': (970,
  884),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-1/2.png': (1115,
  920),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-1/3.png': (1142,
  972),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-1/4.png': (1073,
  965),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-2/1.png': (835,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-2/2.png': (915,
  895),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-2/3.png': (985,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-2/4.png': (905,
  917),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-3/1.png': (730,
  760),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-3/2.png': (790,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-3/3.png': (950,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-3/4.png': (967,
  912),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-4/1.png': (920,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-4/2.png': (975,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-4/3.png': (1070,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-4/4.png': (980,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-5/1.png': (830,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-5/2.png': (890,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-5/3.png': (1055,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-5/4.png': (1170,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-6/1.png': (910,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-6/2.png': (950,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-6/3.png': (1100,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-6/4.png': (1130,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-7/1.png': (980,
  895),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-7/2.png': (1065,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-7/3.png': (1200,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-7/4.png': (1225,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-8/1.png': (950,
  990),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-8/2.png': (1060,
  950),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-8/3.png': (1095,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-8/4.png': (960,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-9/1.png': (1040,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-9/2.png': (1140,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-9/3.png': (1165,
  815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-9/4.png': (1100,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-10/1.png': (910,
  1000),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-10/2.png': (1145,
  935),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-10/3.png': (1115,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-3-10/4.png': (920,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-1/1.png': (975,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-1/2.png': (975,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-1/3.png': (942,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-1/4.png': (1115,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-2/1.png': (985,
  865),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-2/2.png': (967,
  837),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-2/3.png': (1030,
  825),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-2/4.png': (1120,
  835),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-3/1.png': (990,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-3/2.png': (1015,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-3/3.png': (1010,
  817),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-3/4.png': (1110,
  802),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-4/1.png': (875,
  827),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-4/2.png': (892,
  835),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-4/3.png': (945,
  817),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-4/4.png': (987,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-5/1.png': (1032,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-5/2.png': (985,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-5/3.png': (920,
  847),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-5/4.png': (985,
  872),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-6/1.png': (905,
  905),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-6/2.png': (968,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-6/3.png': (1000,
  835),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-6/4.png': (1020,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-7/1.png': (890,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-7/2.png': (805,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-7/3.png': (955,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-7/4.png': (915,
  885),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-8/1.png': (995,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-8/2.png': (885,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-8/3.png': (1025,
  875),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-8/4.png': (980,
  890),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-9/1.png': (865,
  795),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-9/2.png': (780,
  745),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-9/3.png': (910,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-9/4.png': (850,
  740),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-10/1.png': (870,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-10/2.png': (790,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-10/3.png': (890,
  797),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-10/4.png': (900,
  760),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-11/1.png': (945,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-11/2.png': (907,
  872),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-11/3.png': (935,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220823/profilometer/before/2-2-11/4.png': (975,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-1/1.png': (1060,
  857),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-1/2.png': (1070,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-1/3.png': (1030,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-1/4.png': (1025,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-2/1.png': (1022,
  725),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-2/2.png': (1045,
  727),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-2/3.png': (1015,
  735),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-2/4.png': (1025,
  710),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-3/1.png': (1000,
  817),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-3/2.png': (1017,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-3/3.png': (980,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-3/4.png': (995,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-4/1.png': (987,
  915),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-4/2.png': (1012,
  925),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-4/3.png': (965,
  907),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-4/4.png': (960,
  905),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-5/1.png': (980,
  895),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-5/2.png': (995,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-5/3.png': (955,
  865),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-5/4.png': (970,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-6/1.png': (1035,
  915),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-6/2.png': (990,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-6/3.png': (960,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-6/4.png': (955,
  785),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-7/1.png': (1005,
  745),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-7/2.png': (1025,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-7/3.png': (1065,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-7/4.png': (1050,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-8/1.png': (1000,
  690),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-8/2.png': (1030,
  695),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-8/3.png': (1005,
  690),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-8/4.png': (1030,
  695),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-9/1.png': (1015,
  722),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-9/2.png': (1010,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-9/3.png': (1010,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-9/4.png': (915,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-10/1.png': (1005,
  725),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-10/2.png': (990,
  685),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-10/3.png': (980,
  670),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-10/4.png': (900,
  690),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-11/1.png': (965,
  885),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-11/2.png': (980,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-11/3.png': (965,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-11/4.png': (780,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-12/1.png': (950,
  920),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-12/2.png': (965,
  900),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-12/3.png': (975,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-3-12/4.png': (735,
  795),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-1/1.png': (890,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-1/2.png': (942,
  915),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-1/3.png': (950,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-1/4.png': (930,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-2/1.png': (882,
  905),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-2/2.png': (917,
  872),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-2/3.png': (930,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-2/4.png': (1040,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-3/1.png': (1000,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-3/2.png': (860,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-3/3.png': (950,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-3/4.png': (870,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-4/1.png': (955,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-4/2.png': (900,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-4/3.png': (900,
  750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-4/4.png': (920,
  835),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-5/1.png': (1035,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-5/2.png': (1010,
  920),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-5/3.png': (910,
  865),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-5/4.png': (980,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-6/1.png': (970,
  905),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-6/2.png': (1020,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-6/3.png': (910,
  875),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-6/4.png': (960,
  825),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-7/1.png': (840,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-7/2.png': (900,
  815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-7/3.png': (770,
  847),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-7/4.png': (840,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-8/1.png': (835,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-8/2.png': (920,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-8/3.png': (840,
  795),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-8/4.png': (840,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-9/1.png': (840,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-9/2.png': (890,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-9/3.png': (890,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-9/4.png': (930,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-10/1.png': (800,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-10/2.png': (790,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-10/3.png': (860,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-10/4.png': (900,
  740),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-11/1.png': (830,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-11/2.png': (920,
  950),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-11/3.png': (880,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-11/4.png': (950,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-12/1.png': (840,
  900),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-12/2.png': (830,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-12/3.png': (830,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-4-12/4.png': (870,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-1/1.png': (1015,
  895),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-1/2.png': (920,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-1/3.png': (940,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-1/4.png': (1050,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-2/1.png': (970,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-2/2.png': (870,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-2/3.png': (890,
  890),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-2/4.png': (1040,
  890),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-3/1.png': (880,
  930),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-3/2.png': (840,
  940),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-3/3.png': (850,
  940),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-3/4.png': (1000,
  905),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-4/1.png': (830,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-4/2.png': (800,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-4/3.png': (815,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-4/4.png': (1050,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-5/1.png': (750,
  920),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-5/2.png': (705,
  885),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-5/3.png': (770,
  885),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-5/4.png': (980,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-6/1.png': (930,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-6/2.png': (880,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-6/3.png': (730,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-6/4.png': (990,
  715),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-7/1.png': (950,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-7/2.png': (950,
  865),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-7/3.png': (940,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-7/4.png': (1090,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-8/1.png': (925,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-8/2.png': (875,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-8/3.png': (930,
  760),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-8/4.png': (1145,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-9/1.png': (975,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-9/2.png': (905,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-9/3.png': (1040,
  940),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-9/4.png': (1140,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-10/1.png': (1040,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-10/2.png': (970,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-10/3.png': (1000,
  760),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-10/4.png': (1160,
  880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-11/1.png': (1080,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-11/2.png': (950,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-11/3.png': (960,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-11/4.png': (1120,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-12/1.png': (1110,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-12/2.png': (1100,
  890),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-12/3.png': (1030,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-5-12/4.png': (1060,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-1/1.png': (980,
  740),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-1/2.png': (1020,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-1/3.png': (1010,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-1/4.png': (1000,
  815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-2/1.png': (950,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-2/2.png': (1000,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-2/3.png': (1010,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-2/4.png': (1070,
  845),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-3/1.png': (985,
  750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-3/2.png': (965,
  760),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-3/3.png': (1080,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-3/4.png': (1055,
  815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-4/1.png': (1090,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-4/2.png': (1090,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-4/3.png': (1060,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-4/4.png': (1100,
  870),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-5/1.png': (1010,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-5/2.png': (1070,
  835),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-5/3.png': (950,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-5/4.png': (1060,
  860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-6/1.png': (1030,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-6/2.png': (1010,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-6/3.png': (1040,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-6/4.png': (1030,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-7/1.png': (920,
  820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-7/2.png': (950,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-7/3.png': (1080,
  780),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-7/4.png': (1020,
  720),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-8/1.png': (850,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-8/2.png': (950,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-8/3.png': (830,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-8/4.png': (980,
  710),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-9/1.png': (830,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-9/2.png': (920,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-9/3.png': (815,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-9/4.png': (915,
  760),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-10/1.png': (880,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-10/2.png': (980,
  765),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-10/3.png': (915,
  715),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-10/4.png': (840,
  800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-11/1.png': (705,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-11/2.png': (855,
  750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-11/3.png': (850,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-11/4.png': (805,
  775),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-12/1.png': (700,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-12/2.png': (860,
  810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-12/3.png': (840,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220719/profilometer/before/4-6-12/4.png': (815,
  720),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-1/1.png': (1070,
  865),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-1/2.png': (1140,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-1/3.png': (1223,
  815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-1/4.png': (875,
  835),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-2/1.png': (1075,
  865),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-2/2.png': (0,
  0),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-2/3.png': (1215,
  755),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-2/4.png': (940,
  715),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-3/1.png': (935,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-3/2.png': (1060,
  850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-3/3.png': (1190,
  785),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-3/4.png': (1180,
  730),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-5/1.png': (890,
  900),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-5/2.png': (770,
  855),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-5/3.png': (915,
  805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-5/4.png': (930,
  740),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-6/1.png': (990,
  830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-6/2.png': (915,
  840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-6/3.png': (1050,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-6/4.png': (1060,
  710),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-7/1.png': (1080,
  930),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-7/2.png': (1065,
  965),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-7/3.png': (1155,
  950),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-7/4.png': (1190,
  920),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-8/1.png': (1120,
  1000),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-8/2.png': (1090,
  1000),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-8/3.png': (1210,
  985),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-8/4.png': (0,
  0),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-9/1.png': (1080,
  990),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-9/2.png': (1160,
  750),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-9/3.png': (1175,
  950),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-9/4.png': (1140,
  905),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-10/1.png': (1075,
  790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-10/2.png': (0,
  0),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-10/3.png': (1100,
  990),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-10/4.png': (1132,
  967),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-11/1.png': (1082,
  785),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-11/2.png': (1005,
  770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-11/3.png': (1140,
  965),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-11/4.png': (1180,
  920),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-12/1.png': (1085,
  940),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-12/2.png': (0,
  0),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-12/3.png': (1075,
  910),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220906/profilometer/before/2-5-12/4.png': (1120,
  880), 
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-1/1.png':(845, 825),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-1/2.png':(750, 805),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-1/3.png':(865, 825),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-1/4.png':(845, 825),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-2/1.png':(785, 815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-2/2.png':(775, 815),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-2/3.png':(910, 745),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-2/4.png':(830, 820),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-3/1.png':(705, 710),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-3/2.png':(825, 710),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-3/3.png':(980, 810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-3/4.png':(980, 850),             
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-4/1.png':(900, 830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-4/2.png':(790, 770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-4/3.png':(1130, 990),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-4/4.png':(1070, 930),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-5/1.png':(830, 810),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-5/2.png':(870, 850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-5/3.png':(1025, 860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-5/4.png':(1025, 860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-6/1.png':(820, 830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-6/2.png':(810, 840),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-6/3.png':(1000, 770),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-6/4.png':(1020, 850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-7/1.png':(960, 860),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-7/2.png':(960, 800),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-7/3.png':(1050, 900),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-7/4.png':(1050, 900),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-8/1.png':(1080, 880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-8/2.png':(1080, 990),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-8/3.png':(1200, 990),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-8/4.png':(1180, 990),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-9/1.png':(1020, 990),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-9/2.png':(910, 960),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-9/3.png':(980, 950),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-9/4.png':(1000, 930),             
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-10/1.png':(830, 960),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-10/2.png':(930, 900),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-10/3.png':(1020, 890),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-10/4.png':(1020, 880),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-11/1.png':(840, 970),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-11/2.png':(870, 950),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-11/3.png':(970, 920),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-11/4.png':(950, 830),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-12/1.png':(840, 900),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-12/2.png':(700, 850),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-12/3.png':(850, 790),
 '/Users/anna.lisitsyna/Documents/Corrosion estimation/Pics//20220919/profilometer/before/2-4-12/4.png':(870, 690)}

In [3]:
c1_add = {'/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-1/1.png': (809, 773), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-1/2.png': (814, 813), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-1/3.png': (800, 831), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-1/4.png': (782, 840), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-10/1.png': (845, 858), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-10/2.png': (836, 840), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-10/3.png': (805, 813), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-10/4.png': (832, 831), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-11/1.png': (791, 836), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-11/2.png': (827, 863), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-11/3.png': (809, 903), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-11/4.png': (818, 832), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-12/1.png': (809, 872), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-12/2.png': (701, 885), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-12/3.png': (800, 854), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-12/4.png': (800, 836), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-2/1.png': (800, 764), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-2/2.png': (791, 782), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-2/3.png': (791, 814), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-2/4.png': (823, 832), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-3/1.png': (800, 777), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-3/2.png': (814, 813), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-3/3.png': (814, 800), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-3/4.png': (805, 840), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-4/1.png': (809, 818), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-4/2.png': (818, 786), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-4/3.png': (786, 818), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-4/4.png': (800, 831), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-5/1.png': (805, 822), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-5/2.png': (800, 845), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-5/3.png': (800, 840), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-5/4.png': (818, 849), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-6/1.png': (809, 831), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-6/2.png': (809, 840), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-6/3.png': (823, 827), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-6/4.png': (818, 894), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-7/1.png': (823, 876), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-7/2.png': (755, 845), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-7/3.png': (832, 872), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-7/4.png': (737, 894), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-8/1.png': (818, 836), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-8/2.png': (814, 818), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-8/3.png': (823, 845), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-8/4.png': (850, 836), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-9/1.png': (814, 854), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-9/2.png': (814, 858), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-9/3.png': (818, 849), '/Volumes/Expansion/AI2 results/AI2 results/1-1/before/profilometer/1-1-9/4.png': (827, 831), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-1/1.png': (946, 809), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-1/2.png': (946, 791), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-1/3.png': (865, 791), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-1/4.png': (1027, 759), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-10/1.png': (860, 845), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-10/2.png': (964, 881), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-10/3.png': (937, 823), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-10/4.png': (860, 899), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-11/1.png': (951, 755), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-11/2.png': (928, 795), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-11/3.png': (951, 871), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-11/4.png': (874, 885), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-12/1.png': (1005, 845), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-12/2.png': (1010, 854), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-12/3.png': (1027, 885), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-12/4.png': (1090, 849), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-2/1.png': (919, 804), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-2/2.png': (928, 759), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-2/3.png': (865, 773), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-2/4.png': (946, 736), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-3/1.png': (946, 827), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-3/2.png': (960, 755), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-3/3.png': (865, 750), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-3/4.png': (946, 773), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-4/1.png': (910, 732), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-4/2.png': (941, 732), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-4/3.png': (937, 746), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-4/4.png': (964, 813), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-5/1.png': (860, 733), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-5/2.png': (883, 734), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-5/3.png': (928, 783), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-5/4.png': (973, 828), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-6/1.png': (896, 759), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-6/2.png': (901, 727), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-6/3.png': (964, 700), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-6/4.png': (969, 687), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-7/1.png': (974, 831), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-7/2.png': (1041, 845), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-7/3.png': (1018, 899), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-7/4.png': (905, 957), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-8/1.png': (969, 823), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-8/2.png': (1023, 787), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-8/3.png': (1018, 814), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-8/4.png': (914, 891), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-9/1.png': (923, 827), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-9/2.png': (1006, 800), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-9/3.png': (991, 899), '/Volumes/Expansion/AI2 results/AI2 results/2-1/before/profilometer/2-1-9/4.png': (919, 939), '/Volumes/Expansion/AI2 results/AI2 results/2-3/before/profilometer/2-3-11/1.png': (856, 862), '/Volumes/Expansion/AI2 results/AI2 results/2-3/before/profilometer/2-3-11/2.png': (1108, 967), '/Volumes/Expansion/AI2 results/AI2 results/2-3/before/profilometer/2-3-11/3.png': (1023, 985), '/Volumes/Expansion/AI2 results/AI2 results/2-3/before/profilometer/2-3-11/4.png': (815, 912), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-1/1.png': (841, 849), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-1/2.png': (836, 881), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-1/3.png': (832, 831), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-1/4.png': (810, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-2/1.png': (841, 827), 
          '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-2/2.png': (859, 849), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-2/3.png': (827, 831), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-2/4.png': (832, 849), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-3/1.png': (805, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-3/2.png': (832, 800), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-3/3.png': (827, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-3/4.png': (814, 845), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-4/1.png': (809, 845), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-4/2.png': (795, 786), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-4/3.png': (800, 822), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-4/4.png': (805, 827), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-5/1.png': (809, 867), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-5/2.png': (818, 840), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-5/3.png': (800, 849), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-5/4.png': (823, 822), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-6/1.png': (791, 822), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-6/2.png': (805, 800), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-6/3.png': (805, 800), '/Volumes/Expansion/AI2 results/AI2 results/3-1 with results/before/profilometer/3-1-6/4.png': (809, 809), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-1/1.png': (836, 831), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-1/2.png': (796, 827), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-1/3.png': (809, 872), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-1/4.png': (800, 831), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-10/1.png': (786, 769), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-10/2.png': (814, 737), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-10/3.png': (796, 845), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-10/4.png': (832, 854), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-11/1.png': (822, 754), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-11/2.png': (755, 872), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-11/3.png': (809, 835), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-11/4.png': (814, 862), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-12/1.png': (800, 764), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-12/2.png': (787, 791), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-12/3.png': (805, 732), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-12/4.png': (814, 827), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-2/1.png': (809, 845), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-2/2.png': (805, 854), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-2/3.png': (800, 831), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-2/4.png': (814, 795), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-3/1.png': (818, 831), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-3/2.png': (823, 840), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-3/3.png': (795, 800), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-3/4.png': (827, 876), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-4/1.png': (809, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-4/2.png': (809, 840), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-4/3.png': (832, 885), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-4/4.png': (795, 840), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-5/1.png': (805, 840), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-5/2.png': (750, 813), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-5/3.png': (805, 854), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-5/4.png': (836, 831), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-6/1.png': (800, 872), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-6/2.png': (795, 872), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-6/3.png': (786, 827), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-6/4.png': (814, 796), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-7/1.png': (809, 822), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-7/2.png': (787, 818), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-7/3.png': (810, 813), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-7/4.png': (819, 813), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-8/1.png': (791, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-8/2.png': (815, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-8/3.png': (791, 791), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-8/4.png': (819, 818), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-9/1.png': (809, 718), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-9/2.png': (837, 854), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-9/3.png': (836, 840), '/Volumes/Expansion/AI2 results/AI2 results/3-5/before/profilometer/3-5-9/4.png': (796, 804), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-1/1.png': (841, 827), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-1/2.png': (836, 840), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-1/3.png': (800, 840), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-1/4.png': (845, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-10/1.png': (782, 804), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-10/2.png': (768, 800), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-10/3.png': (841, 863), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-10/4.png': (777, 845), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-11/1.png': (795, 844), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-11/2.png': (791, 840), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-11/3.png': (809, 840), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-11/4.png': (805, 831), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-12/1.png': (828, 854), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-12/2.png': (818, 818), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-12/3.png': (791, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-12/4.png': (827, 818), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-2/1.png': (795, 872), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-2/2.png': (823, 827), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-2/3.png': (805, 840), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-2/4.png': (795, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-3/1.png': (786, 810), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-3/2.png': (795, 855), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-3/3.png': (786, 850), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-3/4.png': (818, 859), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-4/1.png': (818, 858), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-4/2.png': (823, 827), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-4/3.png': (823, 858), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-4/4.png': (795, 867), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-5/1.png': (786, 813), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-5/2.png': (827, 809), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-5/3.png': (786, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-5/4.png': (805, 845), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-6/1.png': (823, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-6/2.png': (818, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-6/3.png': (800, 822), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-6/4.png': (791, 849), 
          '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-7/1.png': (832, 777), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-7/2.png': (805, 818), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-7/3.png': (791, 822), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-7/4.png': (818, 804), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-8/1.png': (809, 827), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-8/2.png': (800, 804), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-8/3.png': (800, 827), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-8/4.png': (768, 827), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-9/1.png': (823, 773), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-9/2.png': (823, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-9/3.png': (868, 759), '/Volumes/Expansion/AI2 results/AI2 results/3-7/before/profilometer/3-7-9/4.png': (850, 764), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-1/1.png': (800, 796), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-1/2.png': (828, 814), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-1/3.png': (796, 859), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-1/4.png': (810, 824), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-2/1.png': (809, 764), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-2/2.png': (818, 822), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-2/3.png': (805, 854), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-2/4.png': (791, 867), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-3/1.png': (795, 769), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-3/2.png': (782, 805), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-3/3.png': (828, 802), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-3/4.png': (809, 841), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-4/1.png': (782, 805), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-4/2.png': (819, 846), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-4/3.png': (787, 833), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-4/4.png': (810, 833), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-5/1.png': (768, 822), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-5/2.png': (805, 831), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-5/3.png': (791, 867), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-5/4.png': (809, 840), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-6/1.png': (809, 831), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-6/2.png': (805, 809), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-6/3.png': (795, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-8/before/profilometer/3-8-6/4.png': (795, 800), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-1/1.png': (818, 818), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-1/2.png': (791, 854), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-1/3.png': (786, 813), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-1/4.png': (814, 867), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-2/1.png': (777, 818), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-2/2.png': (782, 836), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-2/3.png': (786, 854), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-2/4.png': (773, 858), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-3/1.png': (768, 831), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-3/2.png': (809, 800), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-3/3.png': (786, 822), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-3/4.png': (782, 858), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-4/1.png': (768, 841), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-4/2.png': (791, 872), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-4/3.png': (827, 800), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-4/4.png': (786, 818), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-5/1.png': (818, 845), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-5/2.png': (773, 831), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-5/3.png': (814, 831), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-5/4.png': (786, 840), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-6/1.png': (777, 809), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-6/2.png': (777, 863), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-6/3.png': (805, 822), '/Volumes/Expansion/AI2 results/AI2 results/3-9/before/profilometer/3-9-6/4.png': (782, 863), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-1/1.png': (1018, 854), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-1/2.png': (951, 944), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-1/3.png': (941, 881), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-1/4.png': (946, 881), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-10/1.png': (982, 815), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-10/2.png': (969, 847), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-10/3.png': (1001, 902), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-10/4.png': (1001, 911), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-11/1.png': (1041, 854), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-11/2.png': (941, 804), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-11/3.png': (937, 876), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-11/4.png': (973, 881), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-12/1.png': (1027, 804), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-12/2.png': (973, 791), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-12/3.png': (1000, 845), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-12/4.png': (1068, 814), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-2/1.png': (1045, 800), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-2/2.png': (960, 814), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-2/3.png': (969, 755), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-2/4.png': (1045, 873), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-3/1.png': (982, 807), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-3/2.png': (928, 784), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-3/3.png': (932, 838), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-3/4.png': (824, 879), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-4/1.png': (970, 839), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-4/2.png': (924, 875), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-4/3.png': (965, 885), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-4/4.png': (942, 890), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-5/1.png': (1032, 723), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-5/2.png': (951, 777), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-5/3.png': (1009, 808), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-5/4.png': (923, 854), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-6/1.png': (969, 768), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-6/2.png': (987, 885), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-6/3.png': (1005, 863), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-6/4.png': (829, 885), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-7/1.png': (1009, 814), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-7/2.png': (974, 800), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-7/3.png': (1077, 818), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-7/4.png': (1086, 769), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-8/1.png': (1041, 800), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-8/2.png': (1032, 795), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-8/3.png': (996, 759), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-8/4.png': (1054, 795), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-9/1.png': (960, 900), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-9/2.png': (883, 855), 
          '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-9/3.png': (1028, 855), '/Volumes/Expansion/AI2 results/AI2 results/4-7/before/profilometer/4-7-9/4.png': (992, 887), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/1.png': (786, 845), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/2.png': (800, 863), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/3.png': (827, 863), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/4.png': (818, 809), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/1.png': (818, 872), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/2.png': (800, 822), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/3.png': (823, 813), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/4.png': (814, 855), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/1.png': (809, 840), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/2.png': (810, 786), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/3.png': (823, 791), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/4.png': (818, 840), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/1.png': (809, 844), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/2.png': (777, 845), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/3.png': (800, 818), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/4.png': (796, 840), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/1.png': (800, 827), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/2.png': (837, 849), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/3.png': (814, 876), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/4.png': (814, 912), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/1.png': (809, 849), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/2.png': (795, 836), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/3.png': (800, 854), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/4.png': (777, 831), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-7/1.png': (818, 800), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-7/2.png': (809, 858), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-7/3.png': (845, 845), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-7/4.png': (823, 823), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-8/1.png': (800, 885), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-8/2.png': (827, 840), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-8/3.png': (782, 822), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-8/4.png': (805, 813), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/1.png': (800, 849), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/2.png': (791, 831), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/3.png': (810, 831), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/4.png': (823, 831), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/1.png': (827, 786), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/2.png': (832, 804), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/3.png': (805, 818), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/4.png': (795, 858), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-11/1.png': (841, 804), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-11/2.png': (805, 809), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-11/3.png': (809, 840), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/1.png': (805, 800), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/2.png': (800, 813), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/3.png': (800, 822), '/Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/4.png': (832, 782), 
         '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-1/1.png': (814, 837), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-1/2.png': (805, 860), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-1/3.png': (823, 833), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-1/4.png': (800, 851), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-2/1.png': (795, 800), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-2/2.png': (800, 818), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-2/3.png': (814, 818), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-2/4.png': (818, 854), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-3/1.png': (800, 863), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-3/2.png': (818, 854), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-3/3.png': (814, 872), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-3/4.png': (809, 827), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-4/1.png': (823, 858), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-4/2.png': (809, 840), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-4/3.png': (809, 827), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-4/4.png': (818, 822), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-5/1.png': (791, 831), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-5/2.png': (777, 831), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-5/3.png': (827, 822), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-5/4.png': (814, 845), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-6/1.png': (814, 872), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-6/2.png': (827, 863), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-6/3.png': (800, 836), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-6/4.png': (805, 841), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-7/1.png': (836, 858), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-7/2.png': (818, 809), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-7/3.png': (791, 804), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-7/4.png': (805, 831), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-8/1.png': (814, 836), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-8/2.png': (818, 840), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-8/3.png': (818, 854), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-8/4.png': (841, 858), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-9/1.png': (805, 804), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-9/2.png': (805, 867), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-9/3.png': (800, 858), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-9/4.png': (800, 827), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-10/1.png': (814, 849), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-10/2.png': (813, 831), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-10/3.png': (768, 867), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-10/4.png': (818, 881), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-11/1.png': (800, 835), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-11/2.png': (860, 836), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-11/3.png': (823, 818), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-11/4.png': (818, 845), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-12/1.png': (814, 899), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-12/2.png': (792, 868), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-12/3.png': (805, 845), '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-12/4.png': (800, 836), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-1/1.png': (850, 930), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-1/2.png': (850, 822), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-1/3.png': (823, 876), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-1/4.png': (809, 840), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-2/1.png': (800, 872), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-2/2.png': (832, 899), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-2/3.png': (791, 854), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-2/4.png': (818, 840), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-3/1.png': (791, 845), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-3/2.png': (818, 840), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-3/3.png': (782, 836), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-3/4.png': (827, 858), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-4/1.png': (818, 836), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-4/2.png': (791, 849), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-4/3.png': (818, 867), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-4/4.png': (823, 813), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-5/1.png': (832, 817), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-5/2.png': (791, 809), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-5/3.png': (786, 845), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-5/4.png': (809, 854), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-6/1.png': (818, 854), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-6/2.png': (827, 836), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-6/3.png': (832, 849), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-6/4.png': (827, 872), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-7/1.png': (814, 845), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-7/2.png': (836, 836), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-7/3.png': (809, 840), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-7/4.png': (841, 890), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-8/1.png': (832, 849), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-8/2.png': (814, 849), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-8/3.png': (795, 890), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-8/4.png': (814, 850), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-9/1.png': (777, 858), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-9/2.png': (841, 876), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-9/3.png': (809, 854), '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-9/4.png': (827, 880), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-2/1.png': (796, 854), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-2/2.png': (810, 864), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-2/3.png': (832, 837), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-2/4.png': (810, 837), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-3/1.png': (800, 800), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-3/2.png': (805, 840), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-3/3.png': (795, 827), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-3/4.png': (818, 845), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-4/1.png': (805, 822), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-4/2.png': (795, 813), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-4/3.png': (800, 845), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-4/4.png': (823, 899), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-5/1.png': (800, 863), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-5/2.png': (800, 863), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-5/3.png': (818, 849), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-5/4.png': (818, 831), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-6/1.png': (782, 858), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-6/2.png': (811, 863), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-6/3.png': (791, 818), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-6/4.png': (755, 827), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-7/1.png': (764, 863), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-7/2.png': (819, 836), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-7/3.png': (795, 836), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-7/4.png': (809, 854), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-8/1.png': (786, 822), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-8/2.png': (800, 894), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-8/3.png': (800, 840), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-8/4.png': (805, 863), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-9/1.png': (841, 863), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-9/2.png': (791, 841), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-9/3.png': (800, 791), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-9/4.png': (805, 809), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-10/1.png': (809, 858), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-10/2.png': (810, 822), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-10/3.png': (832, 836), '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-10/4.png': (827, 876), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-1/1.png': (805, 827), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-1/2.png': (814, 849), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-1/3.png': (795, 831), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-1/4.png': (823, 809), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-2/1.png': (777, 845), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-2/2.png': (800, 863), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-2/3.png': (832, 809), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-2/4.png': (791, 849), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-3/1.png': (773, 840), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-3/2.png': (823, 858), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-3/3.png': (805, 836), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-3/4.png': (809, 877), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-4/1.png': (827, 862), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-4/2.png': (773, 863), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-4/3.png': (823, 845), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-4/4.png': (786, 831), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-5/1.png': (777, 872), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-5/2.png': (786, 867), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-5/3.png': (795, 849), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-5/4.png': (791, 854), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-6/1.png': (791, 840), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-6/2.png': (774, 845), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-6/3.png': (814, 822), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-6/4.png': (782, 836), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-7/1.png': (818, 908), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-7/2.png': (750, 881), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-7/3.png': (823, 836), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-7/4.png': (795, 822), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-8/1.png': (823, 849), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-8/2.png': (815, 804), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-8/3.png': (791, 822), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-8/4.png': (809, 854), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-9/1.png': (795, 872), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-9/2.png': (823, 850), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-9/3.png': (809, 822), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-9/4.png': (814, 863), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-10/1.png': (795, 849), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-10/2.png': (801, 858), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-10/3.png': (768, 804), '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-10/4.png': (814, 845),
         '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/1.png': (809, 831), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/2.png': (845, 849), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/3.png': (823, 858), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/4.png': (823, 867), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/1.png': (823, 854), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/2.png': (814, 831), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/3.png': (809, 858), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/4.png': (818, 854), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/1.png': (809, 845), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/2.png': (827, 876), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/3.png': (809, 867), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/4.png': (800, 845), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/1.png': (805, 822), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/2.png': (823, 840), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/3.png': (805, 840), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/4.png': (814, 840), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/1.png': (805, 836), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/2.png': (809, 890), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/3.png': (823, 867), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/4.png': (814, 854), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/1.png': (827, 836), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/2.png': (818, 881), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/3.png': (809, 885), '/Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/4.png': (818, 858)
         }

In [16]:
materials_dict = {'4-5-1':'2-2-Bipyridine-4-4-dicarboxylic acid', '4-5-2':'Sodium Dodecylbenzene Sulfonate', 
                  '4-5-3':'2-Hydroxy-1,4-Naphtoquinone', '4-5-4': 'PhenylPhosphonic acid', 
                  '4-5-5':'5-Aminoisoquinoline', '4-5-6':'NaCl', '4-5-7':'Kojic acid', 
                  '4-5-8':'Citraconic acid', '4-5-9':'Lactobionic acid', '4-5-10':'Acetic acid', 
                  '4-5-11':'N-Lauroylsarcosine Na', '4-5-12':'NaCl', '4-6-1': 'Citric acid', 
                  '4-6-2':'Salicylaldoxime', '4-6-3':'Gly-Gly hydrochloride', '4-6-4':'L-Ornithine hydrochloride', 
                  '4-6-5':'1,10-Phenanthroline monohydrate', '4-6-6':'NaCl', '4-6-7':'Phytic acid', 
                  '4-6-8':'Tartaric acid (L-(+)-Tartaric acid,L-Threaric acid, (2R,3R)-(+)-Tartaric acid)', 
                  '4-6-9': 'Aspartic acid/(S)-Aminobutanedioic acid, (S)-(+)-Aminosuccinic acid, L-Aspartic acid', 
                  '4-6-10':'Stearic acid sodium salt', '4-6-11':'2-amino-5-trifluoromethyl-1,3,4-thiadiazole', 
                  '4-6-12':'NaCl', '4-4-1':'Uracil', '4-4-2':'Trimesic acid', '4-4-3':'Urea',
                  '4-4-4':'Acetamide', '4-4-5':'1-(2-Hydroxyethyl)piperazine', '4-4-6':'NaCl', 
                  '4-4-7':'1-2-4-5-Benzenetetracarboxylic acid', '4-4-8':'n-Octyl gallate', 
                  '4-4-9':'D-(+)-Galactose', '4-4-10': 'Terephthalic acid', '4-4-11':'2-Nitroterephthalic acid', 
                  '4-4-12':'NaCl', '4-3-1':'2,3-Pyridinedicarboxylic acid', '4-3-2':'Quinic acid', 
                  '4-3-3':'L-Asparagine', '4-3-4':'Glucose', '4-3-5':'Picolinic acid', '4-3-6':'NaCl', 
                  '4-3-7':'2-Amino-5-methyl-salicylic acid ', '4-3-8':'pyrazine', '4-3-9':'CyDTA/TRANS-12-DIAMINO', 
                  '4-3-10':'Diglycolic acid', '4-3-11':'EDTA', '4-3-12':'NaCl', '4-1-1':'Sodium Formate',
                  '4-1-2':'Ethylenediamine', '4-1-3':'Salicylhydroxamic acid', 
                  '4-1-4':'Dimethylolpropionic acid 2,2-bis(hydroxymethyl)propionic acid', 
                  '4-1-5':'3,4-Dihydroxybenzoic acid', '4-1-6':'NaCl', 
                  '2-2-1':' 8-Hydroxy-5-quinoline sulfonic acid','2-2-2':'8-Hydroxy-7-iodo-5-quinolinesulfonic acid',
                  '2-2-3':'2,6-Pyridinedicarboxylic acid', '2-2-4':'2,5-Pyridinedicarboxylic acid', 
                  '2-2-5':'4-isopropylbenzoic acid', '2-2-6':'NaCl', 
                  '2-2-7':'3,4-Pyridinedicarboxylic acid', '2-2-8':'Pyrazole', 
                  '2-2-9':'Quinaldic acid', '2-2-10':'Nicotinic acid', '2-2-11':'NaCl', 
                  '2-3-1':'Benzotriazole', '2-3-2':'3,5-Dimethylpyrazole', '2-3-3':'1,2,4-Triazole', 
                  '2-3-4':'Hexamethyleneteramine', '2-3-5':'5,5-Dimethylhydantoin', '2-3-6':'NaCl', 
                  '2-3-7':'Piperazine', '2-3-8':'4-Isopropylbenzoic acid', '2-3-9':'4-tert-butylbenzoic acid', 
                  '2-3-10':'3-methyl-2-nitrobenzoic acid', '2-3-11':'NaCl', '2-5-1':'Fumaric acid', 
                  '2-5-2':'Ascorbic acid', '2-5-3':'Malic acid', '2-5-4':'Adipic acid', '2-5-5':'Tannic acid', 
                  '2-5-6':'NaCl', '2-5-7':'Alginic acid sodium salt from brown algae', 
                  '2-5-8':'Chitosan', '2-5-9':'Dextran', '2-5-10':'Penicillin G Na salt', '2-5-11':'Folic acid', 
                  '2-5-12':'NaCl', '2-4-1':"2'-Hydroxy-4'-methoxyaceto-phenone", '2-4-2':'Mandelic acid',
                  '2-4-3':'1-Pheny-1,3-butanedione', '2-4-4':'Maltol', '2-4-5':'Glycolic acid', 
                  '2-4-6':'NaCl', '2-4-7':'Oxalic acid', '2-4-8':'Lactic acid', '2-4-9':'Maleic acid', 
                  '2-4-10':'Malonic acid', '2-4-11':'Succinic acid', '2-4-12':'NaCl', 
                  '2-1-1': 'Thiosalicylic acid', '2-1-2': '3-Nitrosalicylic acid', '2-1-3':'3,5-Dinitrosalicylic acid', 
                  '2-1-4': 'salicylaldehyde', '2-1-5': 'Phthalic acid', '2-1-6': 'NaCl', '2-1-7': '4-Hydroxybenzoic acid', 
                  '2-1-8': '3,4-Dihydroxybenzoic acid', '2-1-9': 'Benzoic acid', '2-1-10': 'p-Toluic acid', 
                  '2-1-11':'8-Hydroxyquinoline', '2-1-12': 'NaCl', '3-5-1':'8-Aminoquinoline', '3-5-2':'8-Nitroquinoline', 
                  '3-5-3':'6-Hydroxyquinoline', '3-5-4': '4-Quinolinol', '3-5-5': '3-HYDROXY-1 2-DIMETHYL-4(1H)-PYRIDONE  &', 
                  '3-5-6':'NaCl', '3-5-7':'DIETHYLENETRIAMINE-PENTAACETIC ACID NA5', 
                  '3-5-8': "N-(2-HYDROXYETHYL)ETHYLENEDIAMINE-N N' N trisodium salt", '3-5-9': 'N-(2-HYDROXYETHYL)IMINODIACETIC ACID  >&', 
                  '3-5-10': '5-NITRO-1-10-PHENANTHROLINE', '3-5-11': 'di-Kaliumoxalat Monohydrat', 
                  '3-5-12': 'NaCl', '3-1-1': '1-2-4-5-Benzenetetracarboxylic acid', '3-1-2': 'n-Octyl gallate', 
                  '3-1-3': 'D-(+)-Galactose', '3-1-4': 'Terephthalic acid', '3-1-5': '2-Nitroterephthalic acid', '3-1-6': 'NaCl',
                  '3-1-7':'Thiourea', '3-1-8': 'L-Cysteine', '3-1-9':'Hydroquinonesulfonic acid potassium salt', 
                  '3-1-10': 'taurine', '3-1-11': '(ACES) N-(2-Acetamido)-2-aminoethanesulfonic acid', '3-1-12': 'NaCl', 
                  '3-7-1': '6-Phosphonohexanoic acid', '3-7-2': 'Hypophosphorous acid', '3-7-3': 'POTASSIUM L-TARTRATE MONOBASIC  99%', 
                  '3-7-4': 'Phenylphosphonic acid', '3-7-5': 'Decylphosphonic acid', '3-7-6': 'NaCl', '3-7-7': "2 2'-(ETHYLENEDIOXY)BIS(ETHYLAMINE)  98%", 
                  '3-7-8':'tri-Natriumcitrat Dihydrat', '3-7-9': '5-AMINO-1 3 4-THIADIAZOLE-2-THIOL  98%', 
                  '3-7-10': '2-Amino-5-trifluoromethyl-1,3,4-thiadiazole', '3-7-11': '3 5-DIMETHYLPYRAZOLE-1-METHANOL  99%', 
                  '3-7-12': 'NaCl', '3-8-1': 'Anthraquinone-2-sulfonic acid sodium salt monohydrate', 
                  '3-8-2': 'Cyclohexaneacetic acid', '3-8-3': 'Cyclohexanemethanol', '3-8-4': 'D-Pinitol', 
                  '3-8-5': 'β-D-Glucopyranose, 4-O-β-D-galactopyranosyl-', '3-8-6': 'NaCl', '3-9-1': 'NaCl', 
                  '3-9-2': '1,2,3,4-Butanetetracarboxylic acid', '3-9-3': 'Cinnamaldehyde, (E)-', 
                  '3-9-4': '3-Methylcinnamic acid', '3-9-5': '2-(3,5-Dimethylphenyl)acetic acid', 
                  '3-9-6': '1,3-Benzenedimethanol, 2-hydroxy-5-methyl-',
                  '4-7-1': '1,3,4-thiadiazole-2,5-dithiol (DMTD, bismuthiol) salt', '4-7-2': "2,2' Bipyridyl", 
                  '4-7-3': '5-Nitrobarbituric acid trihydrate', '4-7-4': 'Salicylic acid', '4-7-5': '3-Methylsalicylic', 
                  '4-7-6': 'NaCl', '4-7-7': '4-Methylsalicylic', '4-7-8':'5-Methylsalicylic acid', 
                  '4-7-9': '4-Aminosalicylic acid', '4-7-10': '5-Aminosalicylic acid', '4-7-11': '5-Sulfosalicylic acid', 
                  '4-7-12': 'NaCl', 
                  '1-1-1':'Tricarballylic acid', '1-1-2':'glycine', 
                  '1-1-3':'Tartronic acid', '1-1-4': '5-Nitrouracil', '1-1-5': '2,5-Dimethyl-1,3,4-thiadiazole', 
                  '1-1-6':'NaCl', '1-1-7':'4-Amino-6-mercapto-1H-pyrazolo[3,4-d]pyrimidine', 
                  '1-1-8': '4-Amino-3-hydrazino-5-mercapto-1,2,4-triazole', '1-1-9': '4,6-Diamino-2-pyrimidinethiol', 
                  '1-1-10': '3-Hydroxybenzoic acid', '1-1-11': '5-Methyl-1,3-dihydro-2H-benzo[d]imidazole-2-thione', 
                  '1-1-12': 'NaCl', 
                  '4-2-1':'3-(2-Thienyl)acrylic acid', '4-2-2': 'Furylacrylic acid', '4-2-3': '3-(4-Pyridyl)acrylic acid', 
                  '4-2-4':'(R)-(−)-Glycidyl benzyl ether', '4-2-5':'(S)-(+)-Glycidyl benzyl ether',
                  '4-2-6':'NaCl', '4-2-7':'Benzotriazole', '4-2-8':'3,5-Dimethylpyrazole',
                  '4-2-9':'trans-3-(3-Pyridyl)acrylic acid', '4-2-10':'Mellitic acid', '4-2-11':'1,2,3-Benzenetricarboxylic acid hydrate', '4-2-12':'NaCl',
                  
                  '1-2-1':'Adipic acid', '1-2-2':'1-2-4-5-Benzenetetracarboxylic acid', 
                  '1-2-3':'lysine', '1-2-4': 'Methionine',  
                  '1-2-5':'NaCl', '1-2-6':'2,2′-Thiodiacetic acid', 
                  '1-2-7':'2,2′-(Ethylenedithio)diacetic acid', 
                  '1-2-8': '4,4′-Dithiodibutyric acid', '1-2-9': 'Iminodiacetic acid', 
                  '1-2-10': 'NaCl', 
                  
                  '1-3-1':'', '1-3-2':'Dimethyl 5-hydroxyisophthalate', 
                  '1-3-3':'4-Nitrophthalic acid', '1-3-4': 'N,N′-Trimethyleneurea',  
                  '1-3-5':'NaCl', '1-3-6':'p-Phenylenediacetic acid', '1-3-7':'Dimethyl 2,6-pyridinedicarboxylate', 
                  '1-3-8': '3-Hydroxy-4-nitrobenzoic acid', '1-3-9': 'Benzamide', 
                  '1-3-10': 'NaCl', 
                  
                  '1-5-1':'Pyrazinecarboxylic acid', '1-5-2':'2-Nitrobenzoic acid', 
                  '1-5-3':'2-Aminopyridine-3-carboxylic acid', '1-5-4': '3-Nitrophthalic acid',  
                  '1-5-5': '4,5-Diamino-2,6-dimercaptopyrimidine', 
                  '1-5-6':'NaCl', '1-5-7':'4-Amino-4H-1,2,4-triazole', 
                  '1-5-8': '1-Undecanethiol', '1-5-9': '2,6-Diamino-4-chloropyrimidine', 
                  '1-5-10': '3-Mercaptobenzoic acid', '1-5-11': '4-Mercaptobenzoic acid',
                  '1-5-12': 'NaCl', 
                  
                  '1-6-1':'2-Mercaptopyridine-3-carboxylic acid', '1-6-2':'2-Mercapto-1-methylimidazole', 
                  '1-6-3':'6-Mercaptopyridine-3-carboxylic acid', '1-6-4': '2-Mercaptoimidazole',  
                  '1-6-5':'NaCl', '1-6-6':'AMPSO', '1-6-7':'TAPS', 
                  '1-6-8': 'EPPS', '1-6-10': 'BIS-TRIS propane', 
                  '1-6-9': 'NaCl',
                  
                  '5-1-1': 'BIS-TRIS', '5-1-2': 'Itaconic acid', 
                  '5-1-3': '3-Amino-4-Hydroxybenzoic acid', 
                  '5-1-4': 'sodium-2-mercaptoethanesulfonate', 
                  '5-1-5': '2-Amino-2-methyl-1,3-propanediol', '5-1-6': 'NaCl'
                  
                  #'3-2-1': 'sodium diethyldithiocarbamate', '3-2-2': '1-Octanethiol, CH3(CH2)7SH', 
                  #'3-2-3': '1-Dodecanethiol,  Lauryl mercaptan, CH3(CH2)11SH', '3-2-4': 'tapso', '3-2-5': '(CHES) 2-(Cyclohexylamino)ethanesulfonic acid', '3-2-6': 'NaCl',
                  #'3-2-7':'Sodium phosphite', '3-2-8': '(12-Phosphonododecyl)phosphonic acid', '3-2-9':'Ethylphosphonic acid', 
                  #'3-2-10': 'Propylphosphonic acid', '3-2-11': 'Hexylphosphonic acid', '3-2-12': 'NaCl'
                 
                 }

NaCl_weight_losses = {'4-2': (0.42, 0.53), '4-4':(0.53, 0.65), 
                      '4-6':(0.57, 0.75), '4-3':(0.58, 0.68), 
                      '4-5':(0.82, 0.69), '4-1':(0.89), 
                      '2-2':(0.66, 0.61), '2-5':(0.5, 0.58), 
                      '2-3':(0.49, 0.76), '2-4':(0.5, 0.52), 
                      '3-9':(0.67), '3-8':(0.72), '2-1':(0.61, 0.66), 
                      '3-5':(0.43, 0.61), 
                      
                      
                      '3-1':(0.5, 0.85) , 
                      
                      
                      '4-7':(0.68, 0.54), '1-1':(0.54, 0.57), 
                      '3-7':(0.6, 0.75), '1-2':(0.61, 0.47), 
                      '1-3':(0.74, 0.64), '1-5':(0.7, 0.54), 
                      '1-6':(0.56, 0.83), '3-2':(0.67, 0.84), 
                      '3-3':(0.7, 0.46), '3-4':(0.5, 0.51), 
                      
                      
                     '3-6':(0.45), 
                      
                      '5-1':(0.45)}#, '3-2':(0.17, 0.03)}

In [5]:
vol_losses_real = pd.read_excel(open('/Users/anna.lisitsyna/Downloads/vol_loss_file.xlsx', 'rb'))
correct_names = pd.read_excel(open('/Users/anna.lisitsyna/Downloads/Compound_names.xlsx', 'rb'))
all_names = list(vol_losses_real['Name '])
names_dict = correct_names.set_index('Number')['Compound name'].to_dict()

In [6]:
#Necessary functions for evaluation
#FUNCTIONS FOR READING ORIGINAL FILES FOR HEATMAP AND PROFILOMETER

def normalise_name(name):
    name = name.lower()
    if name.endswith("should redo"):
        name = name[:-len("should redo")]
    name = name.strip()
    return name

def interp(data, method=None, filename=None, resize_coeff=None, pad=((0, 0), (0, 0))):
    try:
        mask = np.isnan(data)
        if method is None:
            data[mask] = np.interp(np.flatnonzero(mask), np.flatnonzero(~mask), data[~mask])
            if resize_coeff is not None:
                data = np.pad(data, mode='constant', pad_width=pad, constant_values=0)
                data = ndimage.zoom(data, 1.0 / resize_coeff)
    except Exception as e:
        print(f"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!The problem is {e}")
        print(f"The type of data is {type(data)}, and data itself is {data} in file {filename}")
    return np.expand_dims(data, axis=2) 


def resize_profilometer(filepath, resize_coeff, greysc=False):
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
    width_temp, height_temp = pic_profilometer_temp.size
    pic_profilometer_temp= pic_profilometer_temp.resize(
        (int(width_temp / resize_coeff), int(height_temp / resize_coeff)))
    pic_profilometer_temp = np.array(pic_profilometer_temp)
    return pic_profilometer_temp / 255

def load_scanner(filepath, resize_coeff=1, greysc=False):
    im = Image.open(filepath)
    im = np.array(im)
    im1 = np.array(im)[480:2930, 4860:7310]
    im2 = np.array(im)[480:2930, 9370:9370+2450]
    im3 = np.array(im)[480:2930, 13900:13900+2450]
    im4 = np.array(im)[480:2930, 18430:18430+2450]
    return [im1, im2, im3, im4]

def ncc(data0, data1):
    """
    normalized cross-correlation coefficient between two data sets

    Parameters
    ----------
    data0, data1 :  numpy arrays of same size
    """
    return (1.0/(data0.size-1)) * np.sum(data0*data1)

#METRICS AND LOSSES

#REVERSE HUBER WITH ADJUSTABLE THRESHOLD
def RevHub_loss(labels, predictions, c = 0.1):
    if labels is None:
        raise ValueError("labels must not be None.")
    if predictions is None:
        raise ValueError("predictions must not be None.")

    # Make sure shape do match
    predictions.get_shape().assert_is_compatible_with(labels.get_shape())

    # Get absolute error for each pixel in batch
    abs_error = tf.abs(tf.subtract(predictions, labels), name='abs_error')
    c = c * tf.reduce_max(abs_error)
    RevHub_loss = tf.where(abs_error <= c,
                          abs_error,
                          (tf.square(abs_error) + tf.square(c)) / (2 * c))

    loss = tf.reduce_mean(RevHub_loss)

    return loss

def combined_loss(target, output, w=[1, 100]):
    return (w[0]*volume_loss_difference(target, output)+w[1]*RevHub_loss(target, output))/2

def volume_loss_difference(target_img, output_img):
    max_val = 0.1
    min_val = -0.03
    output_denormalised = output_img*(max_val-min_val)+min_val
    target_denormalised = target_img*(max_val-min_val)+min_val
    pixsize = (7.406, 7.406, 1)

    vol_tar = tf.reduce_sum(tf.abs(target_denormalised), axis=[1, 2, 3])* pixsize[0] * resize_coeff * pixsize[1] * resize_coeff * pixsize[2] * resize_coeff /(2*10**6)
    vol_out = tf.reduce_sum(tf.abs(output_denormalised), axis=[1, 2, 3]) * pixsize[0] * resize_coeff * pixsize[1] * resize_coeff * pixsize[2] * resize_coeff / (2*10**6)

    print("Vol_tar is {} and vol_out is {}".format(vol_tar, vol_out))
    vol_loss_diff = tf.divide(tf.abs(vol_tar - vol_out), vol_tar+0.0001) * 100
    print("Vol_loss_diff is {} ".format(vol_loss_diff))
    return tf.reduce_mean(vol_loss_diff)

#FUNCTIONS FOR PATCHES CUTTING AND RECONSTRUCTION (overlap 50%)

def patches(img, patch_size=patch_size, step=128):
    res_patches = []
    x_tops = []
    y_tops = []
    if step is None:
        for i in range(1, img.shape[0] // patch_size[0] * img.shape[1] // patch_size[1]-1):
            x_num = i // (img.shape[0] // patch_size[0])
            y_num = i % (img.shape[0] // patch_size[0])
            patch_temp = img[
                         patch_size[1] * y_num:patch_size[1] * y_num + patch_size[1],
                         patch_size[0] * x_num:patch_size[0] * x_num + patch_size[0]]
            if patch_temp.shape[0] == patch_size[0] and patch_temp.shape[1] == patch_size[1]:
                res_patches.append(patch_temp)
    else:
        x_top = 0
        y_top = 0
        i =0
        while y_top <= img.shape[1] - patch_size[1]:
            while x_top<= img.shape[0]-patch_size[0]:
                patch_temp = img[
                             y_top:y_top + patch_size[1],
                             x_top:x_top + patch_size[0]]
                if patch_temp.shape[0] == patch_size[0] and patch_temp.shape[1] == patch_size[1]:
                    res_patches.append(patch_temp)
                x_tops.append(x_top)
                y_tops.append(y_top)
                i=i+1
                x_top = x_top+step
            x_top = 0
            y_top = y_top + step
    return res_patches

def patches_overlap_reconstruct(preds, orig_heat, patch_size=patch_size, step=128):
    nums_matrix = np.full((orig_heat.shape[0], orig_heat.shape[1]), 0)
    vals_matrix = np.full((orig_heat.shape[0], orig_heat.shape[1]), 0.0)
    for i in range(len(preds)):
        x_top = step*(i % ((orig_heat.shape[1]-patch_size[1]) // step+1))
        y_top = step*(i // ((orig_heat.shape[0]-patch_size[0])// step+1))
        nums_matrix[y_top:y_top + patch_size[1],
                             x_top:x_top + patch_size[0]] += 1
        vals_matrix[y_top:y_top + patch_size[1], x_top:x_top + patch_size[0]] += preds[i][:, :, 0]
    vals_matrix = vals_matrix/np.clip(nums_matrix, a_min=1, a_max=len(preds))
    return vals_matrix

#FUNCTION FOR RELATIVE MEAN ERROR
def relative_mean_err(original, target, val=const_outside):
    mask_supertemp  = create_circular_mask(original.shape[0], original.shape[1], center=(original.shape[1]/2, original.shape[1]/2), radius=670)
    diff = abs(original[np.logical_and(mask_supertemp, target!=0)]-target[np.logical_and(mask_supertemp, target!=0)])
    nonzero_heat = abs(target[np.logical_and(mask_supertemp, target!=0)])
    return np.median(diff/nonzero_heat)*100

#FUNCTION FOR VOLUME LOSS

def get_weight_loss(vol_loss, dens = 1.78):
    return vol_loss*dens

def get_inhibition_efficiency(weight_loss, NaCl_weight_loss):
    if weight_loss>NaCl_weight_loss:
        ie = -(weight_loss - NaCl_weight_loss)/weight_loss
    else:
        ie = 1 - 1.0*weight_loss/NaCl_weight_loss
    return ie

def get_volume(hmap, pixsize=(7.406, 7.406, 1)):
    h, w = hmap.shape[:2]
    mask = create_circular_mask(h, w)
    masked_img = hmap.copy()
    masked_img[~mask] = 0
    all_hmap = masked_img
    all_hmap = all_hmap.flatten()
    vol = sum(abs(all_hmap[all_hmap<0])) * pixsize[0] * pixsize[1] * pixsize[2] / (10**6)
    return vol

def get_full_volume(hmap, pixsize=(7.406, 7.406, 1)):
    all_hmap = hmap
    all_hmap = all_hmap.flatten()
    vol = sum(abs(all_hmap[all_hmap<0])) * pixsize[0] * pixsize[1] * pixsize[2] / (10**6)
    return vol

def remove_ticks(ax):
    ax.tick_params(axis='x', which='both', bottom=False, top=False, labelbottom=False)
    ax.tick_params(axis='y', which='both', left=False, right=False, labelleft=False)


def plot_sample_evaluation(prof, heat, preds, filename_temp):
    vol_losses = []
    maes = []
    rel_maes = []
    for i in range(len(preds)):
        vol_losses.append(get_volume(return_back(preds[i])))
        maes.append(mean_absolute_error(heat.flatten(), preds[i].flatten()))
        rel_maes.append(relative_mean_err(heat, preds[i]))
    vol_loss_gt = get_volume(return_back(heat))
    
    fig, axes = plt.subplots(nrows=1, ncols=len(preds)+2, figsize=(18, 9))
    
    
    fig.suptitle("Prediction for {0} \nVolume loss (predicted): {1} \nVolume loss (on GT): {2}".format(filename_temp,  vol_losses, vol_loss_gt))
    axes[0].set_title("Original input", fontdict={'fontsize': 10,
                                                  'fontweight': 1,
                                                  'verticalalignment': 'baseline',
                                                  'horizontalalignment': 'center'}, loc='center')
    if prof is None:
        print("Profilometer is None for {}".format(filename_temp))
    axes[0].imshow(prof)
    
    if heat is None:
        print("Heatmap is None for {}".format(filename_temp))
    
    im = axes[1].imshow(heat, vmin=0, vmax=1, cmap='plasma')
    axes[1].set_title('Normalized heatmap (GT) \nVolume loss (GT): {:.4f}'.format(vol_loss_gt), fontdict={'fontsize': 10,
                                                         'fontweight': 1,
                                                         'verticalalignment': 'baseline',
                                                         'horizontalalignment': 'center'}, loc='center')
    for i in range(len(preds)):
        
        if preds[i] is None:
            print("Prediction for model {} is None for {}".format(i, filename_temp))
        
        axes[2+i].imshow(preds[i], vmin=0, vmax=1, cmap='plasma')
        if rel_maes[i] is None:
            print("Relative MAE is None for file {} and model {}".format(filename_temp, i))
        axes[2+i].set_title('Predicted heatmap for model {}\n for Reverse Huber\nVolume loss (predicted): {:.4f} \n MAE: {:.4f}\n Relative MAE: {:.4f}'.format(i, vol_losses[i], maes[i], rel_maes[i]), fontdict={'fontsize': 10,
                                                                'fontweight': 1,
                                                                'verticalalignment': 'baseline',
                                                                'horizontalalignment': 'center'}, loc='center')
        
    
    for ax in axes:
        remove_ticks(ax)
    
    fig.colorbar(im, ax=axes.ravel().tolist(), shrink=0.5)
    plt.imshow()
   

#FUNCTIONS FOR NORMALIZATION

def norm_01(X, mean_val=0, std_val=1, min_val=-0.03, max_val=0.01, par=0):
    if par==0:
        X_std = (X - min_val) / (max_val - min_val)
    if par==1:
        X_std = (X - mean_val) / std_val
    return X_std

def return_back(X, mean_val=0, std_val=1, min_val=-0.03, max_val=0.01, par=0):
    if par==0:
        X_std = X*(max_val - min_val)+min_val
    if par==1:
        X_std = X*std_val + mean_val
    return X_std

#FUNCTIONS FOR MASKING

def create_circular_mask(h, w, center=None, radius=None):

    if center is None: # use the middle of the image
        center = (int(w/2), int(h/2))
    if radius is None: # use the smallest distance between the center and image walls
        radius = min(center[0], center[1], w-center[0], h-center[1])

    Y, X = np.ogrid[:h, :w]
    dist_from_center = np.sqrt((X - center[0])**2 + (Y-center[1])**2)

    mask = dist_from_center <= radius
    return mask

def mask(img, c, rad=670):
    mean_val = np.array([el for el in img.flatten() if el >= 0 and el < 0.1]).mean()
    if len(img.shape)==3:
        mean_val = np.array([el for el in img.reshape(-1, img.shape[-1]) ]).mean(0)
    mask = create_circular_mask(img.shape[0], img.shape[1], center=c, radius=rad)
    new_img = copy.deepcopy(img)
    new_img[~mask] = mean_val
    new_img = new_img[c[1]-rad:c[1]+rad, c[0]-rad:c[0]+rad]
    pad = ((98, 98), (98, 98))
    if len(img.shape)==3 and img.shape[2]==3:
        r_, g_, b_ = new_img[:, :, 0], new_img[:, :, 1], new_img[:, :, 2]
        rb = np.pad(array=r_, pad_width=pad, mode='constant', constant_values=mean_val[0])
        gb = np.pad(array=g_, pad_width=pad, mode='constant', constant_values=mean_val[1])
        bb = np.pad(array=b_, pad_width=pad, mode='constant', constant_values=mean_val[2])
        new_img = np.dstack(tup=(rb, gb, bb))
    elif len(img.shape)==3 and img.shape[2]==1:
        new_img = np.pad(new_img[:, :, 0], mode='constant', pad_width=pad, constant_values=mean_val)
        new_img = np.expand_dims(new_img, axis=2)
    else:
        new_img = np.pad(new_img, mode='constant', pad_width=pad, constant_values=mean_val)
    return new_img
        
        
c1 = {}
for temp in c1_temp.keys():
    c1[temp.split("/")[-2]+"/"+temp.split("/")[-1]] = c1_temp[temp]
    
c2 = {}
for temp in c2_temp.keys():
    c2[temp.split("/")[-2]+"/"+temp.split("/")[-1]] = c2_temp[temp]
    
for temp in c1_add.keys():
    c1[temp.split("/")[-2]+"/"+temp.split("/")[-1]] = c1_add[temp]
    
unnecessary = ['3-1-1',
'4-4-7', 
'4-6-11',
'4-4-11',
'2-1-8',
'4-2-8',
'2-2-5',
'4-2-7',
'4-4-9',
'4-4-8'
]
    
middle_folder = listdir(overall_path)
print(middle_folder)
smaller_folder = []
for f in middle_folder:
    temp_smaller = listdir(overall_path+f)
    for sm_f in temp_smaller:
        if os.path.isdir(overall_path+f+"/"+sm_f):
            smaller_folder.append(overall_path+f+"/"+sm_f)
            
exact_paths_prof = []
for sm_f in smaller_folder:
    if sm_f.split("/")[-1]=='before':
        try:
            temp_exact = listdir(sm_f+"/profilometer/")
            for ex in temp_exact:
                if os.path.isdir(sm_f+"/profilometer/"+ex) and ex not in unnecessary:
                    exact_paths_prof.append(sm_f+"/profilometer/"+ex)
        except:
            pass
                
exact_paths_heat = []
for sm_f in smaller_folder:
    if sm_f.split("/")[-1]=='after':
        try:
            temp_exact = listdir(sm_f+"/heatmap raw data")
            for ex in temp_exact:
                if os.path.isdir(sm_f+"/heatmap raw data/"+ex) and ex not in unnecessary:
                    exact_paths_heat.append(sm_f+"/heatmap raw data/"+ex)
        except:
            pass
        
heat_materials = [h.split("/")[-1] for h in exact_paths_heat]
prof_materials = [p.split("/")[-1] for p in exact_paths_prof]

unique_materials = list(set(prof_materials))

list_A = prof_materials
list_B = heat_materials

training_materials = set(list_A).intersection(list_B)

indices_prof = [list_A.index(x) for x in training_materials]
indices_heat = [list_B.index(x) for x in training_materials]

#all_materials = ['1-1', '1-2', '1-3', '1-5', '1-6', '2-1', '2-2', '2-3', '2-4', '2-5',                 '3-1 with results', '3-2 with results', '3-3 with results', 
#                 '3-4 with results', '3-5', '3-6 with results', '3-7', '3-8', '3-9', 
#                '4-1', '4-2', '4-3', '4-4', '4-5', '4-6', '4-7']

all_materials = ['1-1', '1-2', '1-3', '1-5', '1-6', '2-1', '2-2', '2-3', '2-4', '2-5', 
                 '3-1 with results', '3-2 with results', '3-3 with results', 
                 '3-4 with results', '3-5', '3-6 with results', '3-7', '3-8', '3-9', 
                 '4-1', '4-2', '4-3', '4-4', '4-5', '4-6', '4-7', '5-1']

mats = []

for p in exact_paths_prof:
    if p.split('/')[-4] in all_materials:
        mats.append(p.split('/')[-4])

['1-1', '1-2', '1-3', '1-5', '1-6', '2-1', '2-2', '2-3', '2-4', '2-5', '3-1 with results', '3-2 with results', '3-3 with results', '3-4 with results', '3-5', '3-6 with results', '3-7', '3-8', '3-9', '4-1', '4-3', '4-4', '4-5', '4-6', '4-7', '4-2', '5-1']

In [7]:
#Load all of the file names


mats = copy.copy(prof_materials)
for i in range(len(prof_materials)):
    for j in range(len(all_materials)):
        if prof_materials[i].split('-')[0]+'-'+prof_materials[i].split('-')[1]==all_materials[j].split(" ")[0]:
            mats[i] = all_materials[j]
                
        
    
all_paths_prof = [overall_path+mats[i]+'/before/profilometer/'+prof_materials[i] for i in range(len(prof_materials))]

all_filenames_prof = []

for i in range(len(all_paths_prof)):
    try:
        f_temp = listdir(all_paths_prof[i])
        all_filenames_prof.extend([all_paths_prof[i]+"/"+f for f in f_temp])
    except:
        print("Bad!!!"+all_paths_prof[i])

In [8]:
materials_processed = list(set([all_paths_prof[i].split('/')[-4] for i in range(len(all_paths_prof))]))
materials_processed.sort()
print(materials_processed)

['1-1', '1-2', '1-3', '1-5', '1-6', '2-1', '2-2', '2-3', '2-4', '2-5', '3-1 with results', '3-5', '3-7', '3-8', '3-9', '4-1', '4-2', '4-3', '4-4', '4-5', '4-6', '4-7', '5-1']

In [9]:
#Load the model

model_path = "/Users/anna.lisitsyna/model_further_21.keras"
model = tf.keras.models.load_model(model_path, 
                                   compile=False,
                                   custom_objects={'RevHub_loss':RevHub_loss, 'combined_loss':combined_loss, 'volume_loss_difference':volume_loss_difference})

In [10]:
def evaluate_image(prof_filename, heat_filename, model_temp=model):
    try:
        #CALCULATE STUFF
        orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
        orig_heat = (mask(interp(pd.read_csv(filepath_or_buffer=heat_filename, skiprows=22, engine='python').to_numpy()[:1664, :1792],
                   filename=heat_filename, resize_coeff=1), c=c2[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]]))[:, :, 0]
        full_orig_heat = interp(pd.read_csv(filepath_or_buffer=heat_filename, skiprows=22, engine='python').to_numpy()[:1664, :1792],
                   filename=heat_filename, resize_coeff=1)
        vol_loss_gt = get_volume(orig_heat)
        print("Got volume loss gt")

        #GET PATCHES FROM IMAGE AND HEATMAP
        p_heat = np.array(patches(orig_heat))
        p_prof = np.array(patches(orig_prof))
        print("Got everything patched")
        pred = model_temp.predict(p_prof)[0]
        #pred_old = model2.predict(p_prof)[3]
        print("Predicted everything")
        reconstructed_predict = np.clip(return_back(patches_overlap_reconstruct(pred, orig_prof)), a_min=clip_val, a_max=0.1)
        print("Shape of reconstructed: ", reconstructed_predict.shape)
        #reconstructed_predict_old = return_back(patches_overlap_reconstruct(pred_old, orig_heat))
        #SAVE STUFF
        vol_loss = get_volume(reconstructed_predict)
        mae = mean_absolute_error(orig_heat.flatten(), reconstructed_predict.flatten())
        rel_mae = relative_mean_err(orig_heat, reconstructed_predict)
        vol_loss_gt = get_volume(orig_heat)
        ncc_temp = ncc(orig_heat, reconstructed_predict)
        filename_parts = prof_filename.split('/')
        filename_temp = filename_parts[-2]+'/'+filename_parts[-1]

        fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(18, 9))


        fig.suptitle("Prediction for {0} \nVolume loss (predicted): {1} \nVolume loss (on GT): {2}".format(filename_temp,  vol_loss, vol_loss_gt))
        axes[0].set_title("Original input", fontdict={'fontsize': 10,
                                                      'fontweight': 1,
                                                      'verticalalignment': 'baseline',
                                                      'horizontalalignment': 'center'}, loc='center')
        if prof_filename is None:
            print("Profilometer is None for {}".format(filename_temp))
        axes[0].imshow(orig_prof)

        if heat_filename is None:
            print("Heatmap is None for {}".format(filename_temp))

        im = axes[1].imshow(orig_heat, vmin=-0.1, vmax=0.1, cmap='plasma')
        axes[1].set_title('Normalized heatmap (GT) \nVolume loss (GT): {:.4f}'.format(vol_loss_gt), fontdict={'fontsize': 10,
                                                             'fontweight': 1,
                                                             'verticalalignment': 'baseline',
                                                             'horizontalalignment': 'center'}, loc='center')


        axes[2].imshow(reconstructed_predict, vmin=-0.1, vmax=0.1, cmap='plasma')
        axes[2].set_title('Predicted heatmap \n Volume loss (predicted): {:.4f} \n MAE: {:.4f}\n Relative MAE: {:.4f}'.format(vol_loss, mae, rel_mae), fontdict={'fontsize': 10,
                                                                'fontweight': 1,
                                                                'verticalalignment': 'baseline',
                                                                'horizontalalignment': 'center'}, loc='center')

        for ax in axes:
            remove_ticks(ax)

        fig.colorbar(im, ax=axes.ravel().tolist(), shrink=0.5)
        plt.savefig("Test_analysis_"+filename_temp.split('/')[-2]+"_"+filename_temp.split('/')[-1][:-4]+"_after9.pdf", format="pdf")
        plt.close()
        #plot_line_profile(orig_heat, reconstructed_predict, line_id = 700, fname = filename_temp.split('/')[-2]+"/"+filename_temp.split('/')[-1][:-4] )

    except Exception as e:
        print("BAD, problem {} with file {}".format(e, prof_filename))

In [11]:
#Evaluate all the files

#EVALUATE ALL FILES

vol_losses_all = []
materials_all = []
sample_num_all = []
unannotated_files = []

for i in range(len(all_filenames_prof)):
    prof_filename = all_filenames_prof[i]
    print("Starting on file {}, name {}".format(i, prof_filename))
    try:
        materials_all.append(prof_filename.split('/')[-2])
        sample_num_all.append(prof_filename.split('.')[-2][-1])
        print("We look at the annotation under key ", prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1])
        orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])

        #GET PATCHES FROM IMAGE AND HEATMAP
        p_prof = np.array(patches(orig_prof))
        print("Got everything patched")
        pred = model.predict(p_prof)[0]
        print("Predicted everything")
    
        reconstructed_predict = np.clip(return_back(patches_overlap_reconstruct(pred, orig_prof)), a_min=clip_val, a_max=0.1)
        print("Reconstructed")
        if len(reconstructed_predict.shape)==3:
            if reconstructed_predict.shape[2]==1:
                reconstructed_predict = reconstructed_predict[:, :, 0]

        vol_losses_all.append(get_volume(reconstructed_predict))
        print("Vol loss done")
    except Exception:
        print("BAD, problem {} with file {}".format(traceback.format_exc(), prof_filename))
        unannotated_files.append(prof_filename)
        vol_losses_all.append(None)

Starting on file 0, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-1/1.png
We look at the annotation under key  1-1-1/1.png
Got everything patched
4/4 [==============================] - 10s 2s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 1, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-1/2.png
We look at the annotation under key  1-1-1/2.png
Got everything patched
4/4 [==============================] - 11s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 2, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-1/3.png
We look at the annotation under key  1-1-1/3.png
Got everything patched
4/4 [==============================] - 12s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 3, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-1/4.png
We look at the annotation under key  1-1-1/4.png
Got everything patched
4/4 [==============================] - 13s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 4, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-10/1.png
We look at the annotation under key  1-1-10/1.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 5, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-10/2.png
We look at the annotation under key  1-1-10/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 6, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-10/3.png
We look at the annotation under key  1-1-10/3.png
Got everything patched
4/4 [==============================] - 23s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 7, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-10/4.png
We look at the annotation under key  1-1-10/4.png
Got everything patched
4/4 [==============================] - 24s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 8, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-11/1.png
We look at the annotation under key  1-1-11/1.png
Got everything patched
4/4 [==============================] - 26s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 9, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-11/2.png
We look at the annotation under key  1-1-11/2.png
Got everything patched
4/4 [==============================] - 30s 7s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 10, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-11/3.png
We look at the annotation under key  1-1-11/3.png
Got everything patched
4/4 [==============================] - 30s 7s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 11, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-11/4.png
We look at the annotation under key  1-1-11/4.png
Got everything patched
4/4 [==============================] - 31s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 12, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-12/1.png
We look at the annotation under key  1-1-12/1.png
Got everything patched
4/4 [==============================] - 31s 7s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 13, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-12/2.png
We look at the annotation under key  1-1-12/2.png
Got everything patched
4/4 [==============================] - 37s 9s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 14, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-12/3.png
We look at the annotation under key  1-1-12/3.png
Got everything patched
4/4 [==============================] - 34s 8s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 15, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-12/4.png
We look at the annotation under key  1-1-12/4.png
Got everything patched
4/4 [==============================] - 31s 7s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 16, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-2/1.png
We look at the annotation under key  1-1-2/1.png
Got everything patched
4/4 [==============================] - 36s 8s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 17, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-2/2.png
We look at the annotation under key  1-1-2/2.png
Got everything patched
4/4 [==============================] - 36s 9s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 18, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-2/3.png
We look at the annotation under key  1-1-2/3.png
Got everything patched
4/4 [==============================] - 32s 8s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 19, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-2/4.png
We look at the annotation under key  1-1-2/4.png
Got everything patched
4/4 [==============================] - 33s 8s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 20, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-3/1.png
We look at the annotation under key  1-1-3/1.png
Got everything patched
4/4 [==============================] - 32s 8s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 21, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-3/2.png
We look at the annotation under key  1-1-3/2.png
Got everything patched
4/4 [==============================] - 32s 8s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 22, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-3/3.png
We look at the annotation under key  1-1-3/3.png
Got everything patched
4/4 [==============================] - 35s 8s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 23, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-3/4.png
We look at the annotation under key  1-1-3/4.png
Got everything patched
4/4 [==============================] - 34s 8s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 24, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-4/1.png
We look at the annotation under key  1-1-4/1.png
Got everything patched
4/4 [==============================] - 30s 7s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 25, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-4/2.png
We look at the annotation under key  1-1-4/2.png
Got everything patched
4/4 [==============================] - 32s 8s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 26, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-4/3.png
We look at the annotation under key  1-1-4/3.png
Got everything patched
4/4 [==============================] - 29s 7s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 27, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-4/4.png
We look at the annotation under key  1-1-4/4.png
Got everything patched
4/4 [==============================] - 37s 10s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 28, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-5/1.png
We look at the annotation under key  1-1-5/1.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 29, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-5/2.png
We look at the annotation under key  1-1-5/2.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything

Reconstructed
Vol loss done
Starting on file 30, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-5/3.png
We look at the annotation under key  1-1-5/3.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 31, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-5/4.png
We look at the annotation under key  1-1-5/4.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 32, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-6/1.png
We look at the annotation under key  1-1-6/1.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 33, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-6/2.png
We look at the annotation under key  1-1-6/2.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 34, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-6/3.png
We look at the annotation under key  1-1-6/3.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 35, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-6/4.png
We look at the annotation under key  1-1-6/4.png
Got everything patched
4/4 [==============================] - 30s 8s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 36, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-7/1.png
We look at the annotation under key  1-1-7/1.png
Got everything patched
4/4 [==============================] - 30s 7s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 37, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-7/2.png
We look at the annotation under key  1-1-7/2.png
Got everything patched
4/4 [==============================] - 28s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 38, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-7/3.png
We look at the annotation under key  1-1-7/3.png
Got everything patched
4/4 [==============================] - 24s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 39, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-7/4.png
We look at the annotation under key  1-1-7/4.png
Got everything patched
4/4 [==============================] - 24s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 40, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-8/1.png
We look at the annotation under key  1-1-8/1.png
Got everything patched
4/4 [==============================] - 24s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 41, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-8/2.png
We look at the annotation under key  1-1-8/2.png
Got everything patched
4/4 [==============================] - 25s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 42, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-8/3.png
We look at the annotation under key  1-1-8/3.png
Got everything patched
4/4 [==============================] - 33s 8s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 43, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-8/4.png
We look at the annotation under key  1-1-8/4.png
Got everything patched
4/4 [==============================] - 33s 8s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 44, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-9/1.png
We look at the annotation under key  1-1-9/1.png
Got everything patched
4/4 [==============================] - 35s 8s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 45, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-9/2.png
We look at the annotation under key  1-1-9/2.png
Got everything patched
4/4 [==============================] - 27s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 46, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-9/3.png
We look at the annotation under key  1-1-9/3.png
Got everything patched
4/4 [==============================] - 26s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 47, name /Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-9/4.png
We look at the annotation under key  1-1-9/4.png
Got everything patched
4/4 [==============================] - 25s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 48, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-1/1.png
We look at the annotation under key  1-2-1/1.png
Got everything patched
4/4 [==============================] - 23s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 49, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-1/2.png
We look at the annotation under key  1-2-1/2.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 50, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-1/3.png
We look at the annotation under key  1-2-1/3.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 51, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-1/4.png
We look at the annotation under key  1-2-1/4.png
Got everything patched
4/4 [==============================] - 24s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 52, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-10/1.png
We look at the annotation under key  1-2-10/1.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 53, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-10/2.png
We look at the annotation under key  1-2-10/2.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 54, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-10/3.png
We look at the annotation under key  1-2-10/3.png
Got everything patched
4/4 [==============================] - 23s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 55, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-10/4.png
We look at the annotation under key  1-2-10/4.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 56, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-2/1.png
We look at the annotation under key  1-2-2/1.png
Got everything patched
4/4 [==============================] - 23s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 57, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-2/2.png
We look at the annotation under key  1-2-2/2.png
Got everything patched
4/4 [==============================] - 24s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 58, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-2/3.png
We look at the annotation under key  1-2-2/3.png
Got everything patched
4/4 [==============================] - 24s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 59, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-2/4.png
We look at the annotation under key  1-2-2/4.png
Got everything patched

4/4 [==============================] - 27s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 60, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-3/1.png
We look at the annotation under key  1-2-3/1.png
Got everything patched
4/4 [==============================] - 25s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 61, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-3/2.png
We look at the annotation under key  1-2-3/2.png
Got everything patched
4/4 [==============================] - 25s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 62, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-3/3.png
We look at the annotation under key  1-2-3/3.png
Got everything patched
4/4 [==============================] - 24s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 63, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-3/4.png
We look at the annotation under key  1-2-3/4.png
Got everything patched
4/4 [==============================] - 24s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 64, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-4/1.png
We look at the annotation under key  1-2-4/1.png
Got everything patched
4/4 [==============================] - 24s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 65, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-4/2.png
We look at the annotation under key  1-2-4/2.png
Got everything patched
4/4 [==============================] - 25s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 66, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-4/3.png
We look at the annotation under key  1-2-4/3.png
Got everything patched
4/4 [==============================] - 23s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 67, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-4/4.png
We look at the annotation under key  1-2-4/4.png
Got everything patched
4/4 [==============================] - 23s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 68, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-5/1.png
We look at the annotation under key  1-2-5/1.png
Got everything patched
4/4 [==============================] - 23s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 69, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-5/2.png
We look at the annotation under key  1-2-5/2.png
Got everything patched
4/4 [==============================] - 27s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 70, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-5/3.png
We look at the annotation under key  1-2-5/3.png
Got everything patched
4/4 [==============================] - 25s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 71, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-5/4.png
We look at the annotation under key  1-2-5/4.png
Got everything patched
4/4 [==============================] - 27s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 72, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-6/1.png
We look at the annotation under key  1-2-6/1.png
Got everything patched
4/4 [==============================] - 26s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 73, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-6/2.png
We look at the annotation under key  1-2-6/2.png
Got everything patched
4/4 [==============================] - 24s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 74, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-6/3.png
We look at the annotation under key  1-2-6/3.png
Got everything patched
4/4 [==============================] - 31s 7s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 75, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-6/4.png
We look at the annotation under key  1-2-6/4.png
Got everything patched
4/4 [==============================] - 32s 7s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 76, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-7/1.png
We look at the annotation under key  1-2-7/1.png
Got everything patched
4/4 [==============================] - 27s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 77, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-7/2.png
We look at the annotation under key  1-2-7/2.png
Got everything patched
4/4 [==============================] - 30s 7s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 78, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-7/3.png
We look at the annotation under key  1-2-7/3.png
Got everything patched
4/4 [==============================] - 26s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 79, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-7/4.png
We look at the annotation under key  1-2-7/4.png
Got everything patched
4/4 [==============================] - 25s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 80, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-8/1.png
We look at the annotation under key  1-2-8/1.png
Got everything patched
4/4 [==============================] - 25s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 81, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-8/2.png
We look at the annotation under key  1-2-8/2.png
Got everything patched
4/4 [==============================] - 24s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 82, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-8/3.png
We look at the annotation under key  1-2-8/3.png
Got everything patched
4/4 [==============================] - 24s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 83, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-8/4.png
We look at the annotation under key  1-2-8/4.png
Got everything patched
4/4 [==============================] - 27s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 84, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-9/1.png
We look at the annotation under key  1-2-9/1.png
Got everything patched
4/4 [==============================] - 25s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 85, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-9/2.png
We look at the annotation under key  1-2-9/2.png
Got everything patched
4/4 [==============================] - 26s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 86, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-9/3.png
We look at the annotation under key  1-2-9/3.png
Got everything patched
4/4 [==============================] - 25s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 87, name /Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-9/4.png
We look at the annotation under key  1-2-9/4.png
Got everything patched
4/4 [==============================] - 26s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 88, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-10/1.png
We look at the annotation under key  1-3-10/1.png
Got everything patched
4/4 [==============================] - 26s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 89, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-10/2.png
We look at the annotation under key  1-3-10/2.png

Got everything patched
4/4 [==============================] - 25s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 90, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-10/3.png
We look at the annotation under key  1-3-10/3.png
Got everything patched
4/4 [==============================] - 29s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 91, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-10/4.png
We look at the annotation under key  1-3-10/4.png
Got everything patched
4/4 [==============================] - 33s 7s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 92, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-2/1.png
We look at the annotation under key  1-3-2/1.png
Got everything patched
4/4 [==============================] - 27s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 93, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-2/2.png
We look at the annotation under key  1-3-2/2.png
Got everything patched
4/4 [==============================] - 30s 7s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 94, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-2/3.png
We look at the annotation under key  1-3-2/3.png
Got everything patched
4/4 [==============================] - 57s 11s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 95, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-2/4.png
We look at the annotation under key  1-3-2/4.png
Got everything patched
4/4 [==============================] - 23s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 96, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-3/1.png
We look at the annotation under key  1-3-3/1.png
Got everything patched
4/4 [==============================] - 20s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 97, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-3/2.png
We look at the annotation under key  1-3-3/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 98, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-3/3.png
We look at the annotation under key  1-3-3/3.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 99, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-3/4.png
We look at the annotation under key  1-3-3/4.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 100, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-4/1.png
We look at the annotation under key  1-3-4/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 101, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-4/2.png
We look at the annotation under key  1-3-4/2.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 102, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-4/3.png
We look at the annotation under key  1-3-4/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 103, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-4/4.png
We look at the annotation under key  1-3-4/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 104, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-5/1.png
We look at the annotation under key  1-3-5/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 105, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-5/2.png
We look at the annotation under key  1-3-5/2.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 106, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-5/3.png
We look at the annotation under key  1-3-5/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 107, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-5/4.png
We look at the annotation under key  1-3-5/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 108, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-6/1.png
We look at the annotation under key  1-3-6/1.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 109, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-6/2.png
We look at the annotation under key  1-3-6/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 110, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-6/3.png
We look at the annotation under key  1-3-6/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 111, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-6/4.png
We look at the annotation under key  1-3-6/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 112, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-7/1.png
We look at the annotation under key  1-3-7/1.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 113, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-7/2.png
We look at the annotation under key  1-3-7/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 114, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-7/3.png
We look at the annotation under key  1-3-7/3.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 115, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-7/4.png
We look at the annotation under key  1-3-7/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 116, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-8/1.png
We look at the annotation under key  1-3-8/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 117, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-8/2.png
We look at the annotation under key  1-3-8/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 118, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-8/3.png
We look at the annotation under key  1-3-8/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 119, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-8/4.png
We look at the annotation under key  1-3-8/4.png

Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 120, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-9/1.png
We look at the annotation under key  1-3-9/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 121, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-9/2.png
We look at the annotation under key  1-3-9/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 122, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-9/3.png
We look at the annotation under key  1-3-9/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 123, name /Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-9/4.png
We look at the annotation under key  1-3-9/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 124, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-1/1.png
We look at the annotation under key  1-5-1/1.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 125, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-1/2.png
We look at the annotation under key  1-5-1/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 126, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-1/3.png
We look at the annotation under key  1-5-1/3.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 127, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-1/4.png
We look at the annotation under key  1-5-1/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 128, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-10/1.png
We look at the annotation under key  1-5-10/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 129, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-10/2.png
We look at the annotation under key  1-5-10/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 130, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-10/3.png
We look at the annotation under key  1-5-10/3.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 131, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-10/4.png
We look at the annotation under key  1-5-10/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 132, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-11/1.png
We look at the annotation under key  1-5-11/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 133, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-11/2.png
We look at the annotation under key  1-5-11/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 134, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-11/3.png
We look at the annotation under key  1-5-11/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 135, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-11/4.png
We look at the annotation under key  1-5-11/4.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 136, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-12/1.png
We look at the annotation under key  1-5-12/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 137, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-12/2.png
We look at the annotation under key  1-5-12/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 138, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-12/3.png
We look at the annotation under key  1-5-12/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 139, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-12/4.png
We look at the annotation under key  1-5-12/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 140, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-2/1.png
We look at the annotation under key  1-5-2/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 141, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-2/2.png
We look at the annotation under key  1-5-2/2.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 142, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-2/3.png
We look at the annotation under key  1-5-2/3.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 143, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-2/4.png
We look at the annotation under key  1-5-2/4.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 144, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-3/1.png
We look at the annotation under key  1-5-3/1.png
Got everything patched
4/4 [==============================] - 23s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 145, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-3/2.png
We look at the annotation under key  1-5-3/2.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 146, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-3/3.png
We look at the annotation under key  1-5-3/3.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 147, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-3/4.png
We look at the annotation under key  1-5-3/4.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 148, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-4/1.png
We look at the annotation under key  1-5-4/1.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 149, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-4/2.png
We look at the annotation under key  1-5-4/2.png

Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 150, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-4/3.png
We look at the annotation under key  1-5-4/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 151, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-4/4.png
We look at the annotation under key  1-5-4/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 152, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-5/1.png
We look at the annotation under key  1-5-5/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 153, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-5/2.png
We look at the annotation under key  1-5-5/2.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 154, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-5/3.png
We look at the annotation under key  1-5-5/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 155, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-5/4.png
We look at the annotation under key  1-5-5/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 156, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-6/1.png
We look at the annotation under key  1-5-6/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 157, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-6/2.png
We look at the annotation under key  1-5-6/2.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 158, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-6/3.png
We look at the annotation under key  1-5-6/3.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 159, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-6/4.png
We look at the annotation under key  1-5-6/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 160, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-7/1.png
We look at the annotation under key  1-5-7/1.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 161, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-7/2.png
We look at the annotation under key  1-5-7/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 162, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-7/3.png
We look at the annotation under key  1-5-7/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 163, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-7/4.png
We look at the annotation under key  1-5-7/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 164, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-8/1.png
We look at the annotation under key  1-5-8/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 165, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-8/2.png
We look at the annotation under key  1-5-8/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 166, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-8/3.png
We look at the annotation under key  1-5-8/3.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 167, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-8/4.png
We look at the annotation under key  1-5-8/4.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 168, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-9/1.png
We look at the annotation under key  1-5-9/1.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 169, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-9/2.png
We look at the annotation under key  1-5-9/2.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 170, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-9/3.png
We look at the annotation under key  1-5-9/3.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 171, name /Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-9/4.png
We look at the annotation under key  1-5-9/4.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 172, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-1/1.png
We look at the annotation under key  1-6-1/1.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 173, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-1/2.png
We look at the annotation under key  1-6-1/2.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 174, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-1/3.png
We look at the annotation under key  1-6-1/3.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 175, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-1/4.png
We look at the annotation under key  1-6-1/4.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 176, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/1.png
We look at the annotation under key  1-6-10/1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '1-6-10/1.png'
 with file /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/1.png
Starting on file 177, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/2.png
We look at the annotation under key  1-6-10/2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '1-6-10/2.png'
 with file /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/2.png
Starting on file 178, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/3.png
We look at the annotation under key  1-6-10/3.png

BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '1-6-10/3.png'
 with file /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/3.png
Starting on file 179, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/4.png
We look at the annotation under key  1-6-10/4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '1-6-10/4.png'
 with file /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/4.png
Starting on file 180, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/._2.png
We look at the annotation under key  1-6-10/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/._2.png
Starting on file 181, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-2/1.png
We look at the annotation under key  1-6-2/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 182, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-2/2.png
We look at the annotation under key  1-6-2/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 183, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-2/3.png
We look at the annotation under key  1-6-2/3.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 184, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-2/4.png
We look at the annotation under key  1-6-2/4.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 185, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-3/1.png
We look at the annotation under key  1-6-3/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 186, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-3/2.png
We look at the annotation under key  1-6-3/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 187, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-3/3.png
We look at the annotation under key  1-6-3/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 188, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-3/4.png
We look at the annotation under key  1-6-3/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 189, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-4/1.png
We look at the annotation under key  1-6-4/1.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 190, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-4/2.png
We look at the annotation under key  1-6-4/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 191, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-4/3.png
We look at the annotation under key  1-6-4/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 192, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-4/4.png
We look at the annotation under key  1-6-4/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 193, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-5/1.png
We look at the annotation under key  1-6-5/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 194, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-5/2.png
We look at the annotation under key  1-6-5/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 195, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-5/3.png
We look at the annotation under key  1-6-5/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 196, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-5/4.png
We look at the annotation under key  1-6-5/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 197, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-6/1.png
We look at the annotation under key  1-6-6/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 198, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-6/2.png
We look at the annotation under key  1-6-6/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 199, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-6/3.png
We look at the annotation under key  1-6-6/3.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 200, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-6/4.png
We look at the annotation under key  1-6-6/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 201, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-7/1.png
We look at the annotation under key  1-6-7/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 202, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-7/2.png
We look at the annotation under key  1-6-7/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 203, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-7/3.png
We look at the annotation under key  1-6-7/3.png
Got everything patched

4/4 [==============================] - 13s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 204, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-7/4.png
We look at the annotation under key  1-6-7/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 205, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-8/1.png
We look at the annotation under key  1-6-8/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 206, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-8/2.png
We look at the annotation under key  1-6-8/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 207, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-8/3.png
We look at the annotation under key  1-6-8/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 208, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-8/4.png
We look at the annotation under key  1-6-8/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 209, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-9/1.png
We look at the annotation under key  1-6-9/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 210, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-9/2.png
We look at the annotation under key  1-6-9/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 211, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-9/3.png
We look at the annotation under key  1-6-9/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 212, name /Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-9/4.png
We look at the annotation under key  1-6-9/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 213, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-1/1.png
We look at the annotation under key  2-1-1/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 214, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-1/2.png
We look at the annotation under key  2-1-1/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 215, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-1/3.png
We look at the annotation under key  2-1-1/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 216, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-1/4.png
We look at the annotation under key  2-1-1/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 217, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-10/1.png
We look at the annotation under key  2-1-10/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 218, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-10/2.png
We look at the annotation under key  2-1-10/2.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 219, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-10/3.png
We look at the annotation under key  2-1-10/3.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 220, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-10/4.png
We look at the annotation under key  2-1-10/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 221, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-11/1.png
We look at the annotation under key  2-1-11/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 222, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-11/2.png
We look at the annotation under key  2-1-11/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 223, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-11/3.png
We look at the annotation under key  2-1-11/3.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 224, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-11/4.png
We look at the annotation under key  2-1-11/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 225, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-12/1.png
We look at the annotation under key  2-1-12/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 226, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-12/2.png
We look at the annotation under key  2-1-12/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 227, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-12/3.png
We look at the annotation under key  2-1-12/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 228, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-12/4.png
We look at the annotation under key  2-1-12/4.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 229, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-2/1.png
We look at the annotation under key  2-1-2/1.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 230, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-2/2.png
We look at the annotation under key  2-1-2/2.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 231, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-2/3.png
We look at the annotation under key  2-1-2/3.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 232, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-2/4.png
We look at the annotation under key  2-1-2/4.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 233, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-3/1.png
We look at the annotation under key  2-1-3/1.png

Got everything patched
4/4 [==============================] - 23s 6s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 234, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-3/2.png
We look at the annotation under key  2-1-3/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 235, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-3/3.png
We look at the annotation under key  2-1-3/3.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 236, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-3/4.png
We look at the annotation under key  2-1-3/4.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 237, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-4/1.png
We look at the annotation under key  2-1-4/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 238, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-4/2.png
We look at the annotation under key  2-1-4/2.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 239, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-4/3.png
We look at the annotation under key  2-1-4/3.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 240, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-4/4.png
We look at the annotation under key  2-1-4/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 241, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-5/1.png
We look at the annotation under key  2-1-5/1.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 242, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-5/2.png
We look at the annotation under key  2-1-5/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 243, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-5/3.png
We look at the annotation under key  2-1-5/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 244, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-5/4.png
We look at the annotation under key  2-1-5/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 245, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-6/1.png
We look at the annotation under key  2-1-6/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 246, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-6/2.png
We look at the annotation under key  2-1-6/2.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 247, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-6/3.png
We look at the annotation under key  2-1-6/3.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 248, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-6/4.png
We look at the annotation under key  2-1-6/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 249, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-7/1.png
We look at the annotation under key  2-1-7/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 250, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-7/2.png
We look at the annotation under key  2-1-7/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 251, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-7/3.png
We look at the annotation under key  2-1-7/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 252, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-7/4.png
We look at the annotation under key  2-1-7/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 253, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-9/1.png
We look at the annotation under key  2-1-9/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 254, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-9/2.png
We look at the annotation under key  2-1-9/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 255, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-9/3.png
We look at the annotation under key  2-1-9/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 256, name /Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-9/4.png
We look at the annotation under key  2-1-9/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 257, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-1/1.png
We look at the annotation under key  2-2-1/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 258, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-1/2.png
We look at the annotation under key  2-2-1/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 259, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-1/3.png
We look at the annotation under key  2-2-1/3.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 260, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-1/4.png
We look at the annotation under key  2-2-1/4.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 261, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-10/1.png
We look at the annotation under key  2-2-10/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 262, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-10/2.png
We look at the annotation under key  2-2-10/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 263, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-10/3.png
We look at the annotation under key  2-2-10/3.png

Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 264, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-10/4.png
We look at the annotation under key  2-2-10/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 265, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-11/1.png
We look at the annotation under key  2-2-11/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 266, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-11/2.png
We look at the annotation under key  2-2-11/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 267, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-11/3.png
We look at the annotation under key  2-2-11/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 268, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-11/4.png
We look at the annotation under key  2-2-11/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 269, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-2/1.png
We look at the annotation under key  2-2-2/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 270, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-2/2.png
We look at the annotation under key  2-2-2/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 271, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-2/3.png
We look at the annotation under key  2-2-2/3.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 272, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-2/4.png
We look at the annotation under key  2-2-2/4.png
Got everything patched
4/4 [==============================] - 17s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 273, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-3/1.png
We look at the annotation under key  2-2-3/1.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 274, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-3/2.png
We look at the annotation under key  2-2-3/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 275, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-3/3.png
We look at the annotation under key  2-2-3/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 276, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-3/4.png
We look at the annotation under key  2-2-3/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 277, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-4/1.png
We look at the annotation under key  2-2-4/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 278, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-4/2.png
We look at the annotation under key  2-2-4/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 279, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-4/3.png
We look at the annotation under key  2-2-4/3.png
Got everything patched
4/4 [==============================] - 17s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 280, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-4/4.png
We look at the annotation under key  2-2-4/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 281, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-6/1.png
We look at the annotation under key  2-2-6/1.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 282, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-6/2.png
We look at the annotation under key  2-2-6/2.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 283, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-6/3.png
We look at the annotation under key  2-2-6/3.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 284, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-6/4.png
We look at the annotation under key  2-2-6/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 285, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-7/1.png
We look at the annotation under key  2-2-7/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 286, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-7/2.png
We look at the annotation under key  2-2-7/2.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 287, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-7/3.png
We look at the annotation under key  2-2-7/3.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 288, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-7/4.png
We look at the annotation under key  2-2-7/4.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 289, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-8/1.png
We look at the annotation under key  2-2-8/1.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 290, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-8/2.png
We look at the annotation under key  2-2-8/2.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 291, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-8/3.png
We look at the annotation under key  2-2-8/3.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 292, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-8/4.png
We look at the annotation under key  2-2-8/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 293, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-9/1.png
We look at the annotation under key  2-2-9/1.png

Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 294, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-9/2.png
We look at the annotation under key  2-2-9/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 295, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-9/3.png
We look at the annotation under key  2-2-9/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 296, name /Volumes/Expansion/AI2 results 20240119/2-2/before/profilometer/2-2-9/4.png
We look at the annotation under key  2-2-9/4.png
Got everything patched
4/4 [==============================] - 13s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 297, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-1/1.png
We look at the annotation under key  2-3-1/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 298, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-1/2.png
We look at the annotation under key  2-3-1/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 299, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-1/3.png
We look at the annotation under key  2-3-1/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 300, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-1/4.png
We look at the annotation under key  2-3-1/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 301, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-10/1.png
We look at the annotation under key  2-3-10/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 302, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-10/2.png
We look at the annotation under key  2-3-10/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 303, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-10/3.png
We look at the annotation under key  2-3-10/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 304, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-10/4.png
We look at the annotation under key  2-3-10/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 305, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-11/1.png
We look at the annotation under key  2-3-11/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 306, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-11/2.png
We look at the annotation under key  2-3-11/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 307, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-11/3.png
We look at the annotation under key  2-3-11/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 308, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-11/4.png
We look at the annotation under key  2-3-11/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 309, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-2/1.png
We look at the annotation under key  2-3-2/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 310, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-2/2.png
We look at the annotation under key  2-3-2/2.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 311, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-2/3.png
We look at the annotation under key  2-3-2/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 312, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-2/4.png
We look at the annotation under key  2-3-2/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 313, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-3/1.png
We look at the annotation under key  2-3-3/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 314, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-3/2.png
We look at the annotation under key  2-3-3/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 315, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-3/3.png
We look at the annotation under key  2-3-3/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 316, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-3/4.png
We look at the annotation under key  2-3-3/4.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 317, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-4/1.png
We look at the annotation under key  2-3-4/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 318, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-4/2.png
We look at the annotation under key  2-3-4/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 319, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-4/3.png
We look at the annotation under key  2-3-4/3.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 320, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-4/4.png
We look at the annotation under key  2-3-4/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 321, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-5/1.png
We look at the annotation under key  2-3-5/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 322, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-5/2.png
We look at the annotation under key  2-3-5/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 323, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-5/3.png
We look at the annotation under key  2-3-5/3.png

Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 324, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-5/4.png
We look at the annotation under key  2-3-5/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 325, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-6/1.png
We look at the annotation under key  2-3-6/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 326, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-6/2.png
We look at the annotation under key  2-3-6/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 327, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-6/3.png
We look at the annotation under key  2-3-6/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 328, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-6/4.png
We look at the annotation under key  2-3-6/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 329, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-7/1.png
We look at the annotation under key  2-3-7/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 330, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-7/2.png
We look at the annotation under key  2-3-7/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 331, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-7/3.png
We look at the annotation under key  2-3-7/3.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 332, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-7/4.png
We look at the annotation under key  2-3-7/4.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 333, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-8/1.png
We look at the annotation under key  2-3-8/1.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 334, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-8/2.png
We look at the annotation under key  2-3-8/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 335, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-8/3.png
We look at the annotation under key  2-3-8/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 336, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-8/4.png
We look at the annotation under key  2-3-8/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 337, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-9/1.png
We look at the annotation under key  2-3-9/1.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 338, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-9/2.png
We look at the annotation under key  2-3-9/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 339, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-9/3.png
We look at the annotation under key  2-3-9/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 340, name /Volumes/Expansion/AI2 results 20240119/2-3/before/profilometer/2-3-9/4.png
We look at the annotation under key  2-3-9/4.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 341, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-1/1.png
We look at the annotation under key  2-4-1/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 342, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-1/2.png
We look at the annotation under key  2-4-1/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 343, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-1/3.png
We look at the annotation under key  2-4-1/3.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 344, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-1/4.png
We look at the annotation under key  2-4-1/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 345, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-10/1.png
We look at the annotation under key  2-4-10/1.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 346, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-10/2.png
We look at the annotation under key  2-4-10/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 347, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-10/3.png
We look at the annotation under key  2-4-10/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 348, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-10/4.png
We look at the annotation under key  2-4-10/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 349, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-11/1.png
We look at the annotation under key  2-4-11/1.png
Got everything patched
4/4 [==============================] - 20s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 350, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-11/2.png
We look at the annotation under key  2-4-11/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 351, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-11/3.png
We look at the annotation under key  2-4-11/3.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 352, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-11/4.png
We look at the annotation under key  2-4-11/4.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 353, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-12/1.png
We look at the annotation under key  2-4-12/1.png

Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 354, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-12/2.png
We look at the annotation under key  2-4-12/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 355, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-12/3.png
We look at the annotation under key  2-4-12/3.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 356, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-12/4.png
We look at the annotation under key  2-4-12/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 357, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-2/1.png
We look at the annotation under key  2-4-2/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 358, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-2/2.png
We look at the annotation under key  2-4-2/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 359, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-2/3.png
We look at the annotation under key  2-4-2/3.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 360, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-2/4.png
We look at the annotation under key  2-4-2/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 361, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-3/1.png
We look at the annotation under key  2-4-3/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 362, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-3/2.png
We look at the annotation under key  2-4-3/2.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 363, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-3/3.png
We look at the annotation under key  2-4-3/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 364, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-3/4.png
We look at the annotation under key  2-4-3/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 365, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-4/1.png
We look at the annotation under key  2-4-4/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 366, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-4/2.png
We look at the annotation under key  2-4-4/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 367, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-4/3.png
We look at the annotation under key  2-4-4/3.png
Got everything patched
4/4 [==============================] - 11s 2s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 368, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-4/4.png
We look at the annotation under key  2-4-4/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 369, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-5/1.png
We look at the annotation under key  2-4-5/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 370, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-5/2.png
We look at the annotation under key  2-4-5/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 371, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-5/3.png
We look at the annotation under key  2-4-5/3.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 372, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-5/4.png
We look at the annotation under key  2-4-5/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 373, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-6/1.png
We look at the annotation under key  2-4-6/1.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 374, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-6/2.png
We look at the annotation under key  2-4-6/2.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 375, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-6/3.png
We look at the annotation under key  2-4-6/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 376, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-6/4.png
We look at the annotation under key  2-4-6/4.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 377, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-7/1.png
We look at the annotation under key  2-4-7/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 378, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-7/2.png
We look at the annotation under key  2-4-7/2.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 379, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-7/3.png
We look at the annotation under key  2-4-7/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 380, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-7/4.png
We look at the annotation under key  2-4-7/4.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 381, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-8/1.png
We look at the annotation under key  2-4-8/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 382, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-8/2.png
We look at the annotation under key  2-4-8/2.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 383, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-8/3.png
We look at the annotation under key  2-4-8/3.png

Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 384, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-8/4.png
We look at the annotation under key  2-4-8/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 385, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-9/1.png
We look at the annotation under key  2-4-9/1.png
Got everything patched
4/4 [==============================] - 12s 2s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 386, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-9/2.png
We look at the annotation under key  2-4-9/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 387, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-9/3.png
We look at the annotation under key  2-4-9/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 388, name /Volumes/Expansion/AI2 results 20240119/2-4/before/profilometer/2-4-9/4.png
We look at the annotation under key  2-4-9/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 389, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-1/1.png
We look at the annotation under key  2-5-1/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 390, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-1/2.png
We look at the annotation under key  2-5-1/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 391, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-1/3.png
We look at the annotation under key  2-5-1/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 392, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-1/4.png
We look at the annotation under key  2-5-1/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 393, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-10/1.png
We look at the annotation under key  2-5-10/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 394, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-10/2.png
We look at the annotation under key  2-5-10/2.png
Got everything patched
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 22, in <module>
    pred = model.predict(p_prof)[0]
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/keras/src/engine/training.py", line 2579, in predict
    raise ValueError(
ValueError: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.
 with file /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-10/2.png
Starting on file 395, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-10/3.png
We look at the annotation under key  2-5-10/3.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 396, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-10/4.png
We look at the annotation under key  2-5-10/4.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 397, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-11/1.png
We look at the annotation under key  2-5-11/1.png
Got everything patched
4/4 [==============================] - 14s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 398, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-11/2.png
We look at the annotation under key  2-5-11/2.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 399, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-11/3.png
We look at the annotation under key  2-5-11/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 400, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-11/4.png
We look at the annotation under key  2-5-11/4.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 401, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-12/1.png
We look at the annotation under key  2-5-12/1.png
Got everything patched
4/4 [==============================] - 13s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 402, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-12/2.png
We look at the annotation under key  2-5-12/2.png
Got everything patched
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 22, in <module>
    pred = model.predict(p_prof)[0]
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/keras/src/engine/training.py", line 2579, in predict
    raise ValueError(
ValueError: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.
 with file /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-12/2.png
Starting on file 403, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-12/3.png
We look at the annotation under key  2-5-12/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 404, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-12/4.png
We look at the annotation under key  2-5-12/4.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 405, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-2/1.png
We look at the annotation under key  2-5-2/1.png
Got everything patched
4/4 [==============================] - 13s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 406, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-2/2.png
We look at the annotation under key  2-5-2/2.png
Got everything patched
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 22, in <module>
    pred = model.predict(p_prof)[0]
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/keras/src/engine/training.py", line 2579, in predict
    raise ValueError(
ValueError: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.
 with file /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-2/2.png
Starting on file 407, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-2/3.png
We look at the annotation under key  2-5-2/3.png

Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 408, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-2/4.png
We look at the annotation under key  2-5-2/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 409, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-3/1.png
We look at the annotation under key  2-5-3/1.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 410, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-3/2.png
We look at the annotation under key  2-5-3/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 411, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-3/3.png
We look at the annotation under key  2-5-3/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 412, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-3/4.png
We look at the annotation under key  2-5-3/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 413, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-5/1.png
We look at the annotation under key  2-5-5/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 414, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-5/2.png
We look at the annotation under key  2-5-5/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 415, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-5/3.png
We look at the annotation under key  2-5-5/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 416, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-5/4.png
We look at the annotation under key  2-5-5/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 417, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-6/1.png
We look at the annotation under key  2-5-6/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 418, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-6/2.png
We look at the annotation under key  2-5-6/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 419, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-6/3.png
We look at the annotation under key  2-5-6/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 420, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-6/4.png
We look at the annotation under key  2-5-6/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 421, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-7/1.png
We look at the annotation under key  2-5-7/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 422, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-7/2.png
We look at the annotation under key  2-5-7/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 423, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-7/3.png
We look at the annotation under key  2-5-7/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 424, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-7/4.png
We look at the annotation under key  2-5-7/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 425, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-8/1.png
We look at the annotation under key  2-5-8/1.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 426, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-8/2.png
We look at the annotation under key  2-5-8/2.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 427, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-8/3.png
We look at the annotation under key  2-5-8/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 428, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-8/4.png
We look at the annotation under key  2-5-8/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 429, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-9/1.png
We look at the annotation under key  2-5-9/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 430, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-9/2.png
We look at the annotation under key  2-5-9/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 431, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-9/3.png
We look at the annotation under key  2-5-9/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 432, name /Volumes/Expansion/AI2 results 20240119/2-5/before/profilometer/2-5-9/4.png
We look at the annotation under key  2-5-9/4.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 433, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-10/1.png
We look at the annotation under key  3-1-10/1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-10/1.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-10/1.png
Starting on file 434, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-10/2.png
We look at the annotation under key  3-1-10/2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-10/2.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-10/2.png
Starting on file 435, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-10/3.png
We look at the annotation under key  3-1-10/3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-10/3.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-10/3.png
Starting on file 436, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-10/4.png
We look at the annotation under key  3-1-10/4.png

BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-10/4.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-10/4.png
Starting on file 437, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-11/1.png
We look at the annotation under key  3-1-11/1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-11/1.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-11/1.png
Starting on file 438, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-11/2.png
We look at the annotation under key  3-1-11/2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-11/2.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-11/2.png
Starting on file 439, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-11/3.png
We look at the annotation under key  3-1-11/3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-11/3.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-11/3.png
Starting on file 440, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-11/4.png
We look at the annotation under key  3-1-11/4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-11/4.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-11/4.png
Starting on file 441, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-12/1.png
We look at the annotation under key  3-1-12/1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-12/1.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-12/1.png
Starting on file 442, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-12/2.png
We look at the annotation under key  3-1-12/2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-12/2.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-12/2.png
Starting on file 443, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-12/3.png
We look at the annotation under key  3-1-12/3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-12/3.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-12/3.png
Starting on file 444, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-12/4.png
We look at the annotation under key  3-1-12/4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-12/4.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-12/4.png
Starting on file 445, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-2/1.png
We look at the annotation under key  3-1-2/1.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 446, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-2/2.png
We look at the annotation under key  3-1-2/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 447, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-2/3.png
We look at the annotation under key  3-1-2/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 448, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-2/4.png
We look at the annotation under key  3-1-2/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 449, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-3/1.png
We look at the annotation under key  3-1-3/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 450, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-3/2.png
We look at the annotation under key  3-1-3/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 451, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-3/3.png
We look at the annotation under key  3-1-3/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 452, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-3/4.png
We look at the annotation under key  3-1-3/4.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 453, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-4/1.png
We look at the annotation under key  3-1-4/1.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 454, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-4/2.png
We look at the annotation under key  3-1-4/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 455, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-4/3.png
We look at the annotation under key  3-1-4/3.png

Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 456, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-4/4.png
We look at the annotation under key  3-1-4/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 457, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-5/1.png
We look at the annotation under key  3-1-5/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 458, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-5/2.png
We look at the annotation under key  3-1-5/2.png
Got everything patched
4/4 [==============================] - 11s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 459, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-5/3.png
We look at the annotation under key  3-1-5/3.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 460, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-5/4.png
We look at the annotation under key  3-1-5/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 461, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-6/1.png
We look at the annotation under key  3-1-6/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 462, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-6/2.png
We look at the annotation under key  3-1-6/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 463, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-6/3.png
We look at the annotation under key  3-1-6/3.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 464, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-6/4.png
We look at the annotation under key  3-1-6/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 465, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-7/1.png
We look at the annotation under key  3-1-7/1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-7/1.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-7/1.png
Starting on file 466, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-7/2.png
We look at the annotation under key  3-1-7/2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-7/2.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-7/2.png
Starting on file 467, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-7/3.png
We look at the annotation under key  3-1-7/3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-7/3.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-7/3.png
Starting on file 468, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-7/4.png
We look at the annotation under key  3-1-7/4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-7/4.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-7/4.png
Starting on file 469, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-8/1.png
We look at the annotation under key  3-1-8/1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-8/1.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-8/1.png
Starting on file 470, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-8/2.png
We look at the annotation under key  3-1-8/2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-8/2.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-8/2.png
Starting on file 471, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-8/3.png
We look at the annotation under key  3-1-8/3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-8/3.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-8/3.png
Starting on file 472, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-8/4.png
We look at the annotation under key  3-1-8/4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-8/4.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-8/4.png
Starting on file 473, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-9/1.png
We look at the annotation under key  3-1-9/1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-9/1.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-9/1.png
Starting on file 474, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-9/2.png
We look at the annotation under key  3-1-9/2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-9/2.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-9/2.png
Starting on file 475, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-9/3.png
We look at the annotation under key  3-1-9/3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-9/3.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-9/3.png
Starting on file 476, name /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-9/4.png
We look at the annotation under key  3-1-9/4.png

BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
KeyError: '3-1-9/4.png'
 with file /Volumes/Expansion/AI2 results 20240119/3-1 with results/before/profilometer/3-1-9/4.png
Starting on file 477, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-1/1.png
We look at the annotation under key  3-5-1/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 478, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-1/2.png
We look at the annotation under key  3-5-1/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 479, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-1/3.png
We look at the annotation under key  3-5-1/3.png
Got everything patched
4/4 [==============================] - 14s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 480, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-1/4.png
We look at the annotation under key  3-5-1/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 481, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-10/1.png
We look at the annotation under key  3-5-10/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 482, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-10/2.png
We look at the annotation under key  3-5-10/2.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 483, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-10/3.png
We look at the annotation under key  3-5-10/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 484, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-10/4.png
We look at the annotation under key  3-5-10/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 485, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-11/1.png
We look at the annotation under key  3-5-11/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 486, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-11/2.png
We look at the annotation under key  3-5-11/2.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 487, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-11/3.png
We look at the annotation under key  3-5-11/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 488, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-11/4.png
We look at the annotation under key  3-5-11/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 489, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-12/1.png
We look at the annotation under key  3-5-12/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 490, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-12/2.png
We look at the annotation under key  3-5-12/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 491, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-12/3.png
We look at the annotation under key  3-5-12/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 492, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-12/4.png
We look at the annotation under key  3-5-12/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 493, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-2/1.png
We look at the annotation under key  3-5-2/1.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 494, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-2/2.png
We look at the annotation under key  3-5-2/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 495, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-2/3.png
We look at the annotation under key  3-5-2/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 496, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-2/4.png
We look at the annotation under key  3-5-2/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 497, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-3/1.png
We look at the annotation under key  3-5-3/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 498, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-3/2.png
We look at the annotation under key  3-5-3/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 499, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-3/3.png
We look at the annotation under key  3-5-3/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 500, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-3/4.png
We look at the annotation under key  3-5-3/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 501, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-4/1.png
We look at the annotation under key  3-5-4/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 502, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-4/2.png
We look at the annotation under key  3-5-4/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 503, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-4/3.png
We look at the annotation under key  3-5-4/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 504, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-4/4.png
We look at the annotation under key  3-5-4/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 505, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-5/1.png
We look at the annotation under key  3-5-5/1.png

Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 506, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-5/2.png
We look at the annotation under key  3-5-5/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 507, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-5/3.png
We look at the annotation under key  3-5-5/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 508, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-5/4.png
We look at the annotation under key  3-5-5/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 509, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-6/1.png
We look at the annotation under key  3-5-6/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 510, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-6/2.png
We look at the annotation under key  3-5-6/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 511, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-6/3.png
We look at the annotation under key  3-5-6/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 512, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-6/4.png
We look at the annotation under key  3-5-6/4.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 513, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-7/1.png
We look at the annotation under key  3-5-7/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 514, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-7/2.png
We look at the annotation under key  3-5-7/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 515, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-7/3.png
We look at the annotation under key  3-5-7/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 516, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-7/4.png
We look at the annotation under key  3-5-7/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 517, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-8/1.png
We look at the annotation under key  3-5-8/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 518, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-8/2.png
We look at the annotation under key  3-5-8/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 519, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-8/3.png
We look at the annotation under key  3-5-8/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 520, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-8/4.png
We look at the annotation under key  3-5-8/4.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 521, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-9/1.png
We look at the annotation under key  3-5-9/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 522, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-9/2.png
We look at the annotation under key  3-5-9/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 523, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-9/3.png
We look at the annotation under key  3-5-9/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 524, name /Volumes/Expansion/AI2 results 20240119/3-5/before/profilometer/3-5-9/4.png
We look at the annotation under key  3-5-9/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 525, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-1/1.png
We look at the annotation under key  3-7-1/1.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 526, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-1/2.png
We look at the annotation under key  3-7-1/2.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 527, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-1/3.png
We look at the annotation under key  3-7-1/3.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 528, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-1/4.png
We look at the annotation under key  3-7-1/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 529, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-10/1.png
We look at the annotation under key  3-7-10/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 530, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-10/2.png
We look at the annotation under key  3-7-10/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 531, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-10/3.png
We look at the annotation under key  3-7-10/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 532, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-10/4.png
We look at the annotation under key  3-7-10/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 533, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-11/1.png
We look at the annotation under key  3-7-11/1.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 534, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-11/2.png
We look at the annotation under key  3-7-11/2.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 535, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-11/3.png
We look at the annotation under key  3-7-11/3.png

Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 536, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-11/4.png
We look at the annotation under key  3-7-11/4.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 537, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-12/1.png
We look at the annotation under key  3-7-12/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 538, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-12/2.png
We look at the annotation under key  3-7-12/2.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 539, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-12/3.png
We look at the annotation under key  3-7-12/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 540, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-12/4.png
We look at the annotation under key  3-7-12/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 541, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-2/1.png
We look at the annotation under key  3-7-2/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 542, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-2/2.png
We look at the annotation under key  3-7-2/2.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 543, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-2/3.png
We look at the annotation under key  3-7-2/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 544, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-2/4.png
We look at the annotation under key  3-7-2/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 545, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-3/1.png
We look at the annotation under key  3-7-3/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 546, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-3/2.png
We look at the annotation under key  3-7-3/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 547, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-3/3.png
We look at the annotation under key  3-7-3/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 548, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-3/4.png
We look at the annotation under key  3-7-3/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 549, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-4/1.png
We look at the annotation under key  3-7-4/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 550, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-4/2.png
We look at the annotation under key  3-7-4/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 551, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-4/3.png
We look at the annotation under key  3-7-4/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 552, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-4/4.png
We look at the annotation under key  3-7-4/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 553, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-5/1.png
We look at the annotation under key  3-7-5/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 554, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-5/2.png
We look at the annotation under key  3-7-5/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 555, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-5/3.png
We look at the annotation under key  3-7-5/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 556, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-5/4.png
We look at the annotation under key  3-7-5/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 557, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-6/1.png
We look at the annotation under key  3-7-6/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 558, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-6/2.png
We look at the annotation under key  3-7-6/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 559, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-6/3.png
We look at the annotation under key  3-7-6/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 560, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-6/4.png
We look at the annotation under key  3-7-6/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 561, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-7/1.png
We look at the annotation under key  3-7-7/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 562, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-7/2.png
We look at the annotation under key  3-7-7/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 563, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-7/3.png
We look at the annotation under key  3-7-7/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 564, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-7/4.png
We look at the annotation under key  3-7-7/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 565, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-8/1.png
We look at the annotation under key  3-7-8/1.png

Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 566, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-8/2.png
We look at the annotation under key  3-7-8/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 567, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-8/3.png
We look at the annotation under key  3-7-8/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 568, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-8/4.png
We look at the annotation under key  3-7-8/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 569, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-9/1.png
We look at the annotation under key  3-7-9/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 570, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-9/2.png
We look at the annotation under key  3-7-9/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 571, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-9/3.png
We look at the annotation under key  3-7-9/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 572, name /Volumes/Expansion/AI2 results 20240119/3-7/before/profilometer/3-7-9/4.png
We look at the annotation under key  3-7-9/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 573, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-1/1.png
We look at the annotation under key  3-8-1/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 574, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-1/2.png
We look at the annotation under key  3-8-1/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 575, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-1/3.png
We look at the annotation under key  3-8-1/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 576, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-1/4.png
We look at the annotation under key  3-8-1/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 577, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-2/1.png
We look at the annotation under key  3-8-2/1.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 578, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-2/2.png
We look at the annotation under key  3-8-2/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 579, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-2/3.png
We look at the annotation under key  3-8-2/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 580, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-2/4.png
We look at the annotation under key  3-8-2/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 581, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-3/1.png
We look at the annotation under key  3-8-3/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 582, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-3/2.png
We look at the annotation under key  3-8-3/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 583, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-3/3.png
We look at the annotation under key  3-8-3/3.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 584, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-3/4.png
We look at the annotation under key  3-8-3/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 585, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-4/1.png
We look at the annotation under key  3-8-4/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 586, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-4/2.png
We look at the annotation under key  3-8-4/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 587, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-4/3.png
We look at the annotation under key  3-8-4/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 588, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-4/4.png
We look at the annotation under key  3-8-4/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 589, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-5/1.png
We look at the annotation under key  3-8-5/1.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 590, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-5/2.png
We look at the annotation under key  3-8-5/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 591, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-5/3.png
We look at the annotation under key  3-8-5/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 592, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-5/4.png
We look at the annotation under key  3-8-5/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 593, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-6/1.png
We look at the annotation under key  3-8-6/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 594, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-6/2.png
We look at the annotation under key  3-8-6/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 595, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-6/3.png
We look at the annotation under key  3-8-6/3.png

Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 596, name /Volumes/Expansion/AI2 results 20240119/3-8/before/profilometer/3-8-6/4.png
We look at the annotation under key  3-8-6/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 597, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-1/1.png
We look at the annotation under key  3-9-1/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 598, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-1/2.png
We look at the annotation under key  3-9-1/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 599, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-1/3.png
We look at the annotation under key  3-9-1/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 600, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-1/4.png
We look at the annotation under key  3-9-1/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 601, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-2/1.png
We look at the annotation under key  3-9-2/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 602, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-2/2.png
We look at the annotation under key  3-9-2/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 603, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-2/3.png
We look at the annotation under key  3-9-2/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 604, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-2/4.png
We look at the annotation under key  3-9-2/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 605, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-3/1.png
We look at the annotation under key  3-9-3/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 606, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-3/2.png
We look at the annotation under key  3-9-3/2.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 607, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-3/3.png
We look at the annotation under key  3-9-3/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 608, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-3/4.png
We look at the annotation under key  3-9-3/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 609, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-4/1.png
We look at the annotation under key  3-9-4/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 610, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-4/2.png
We look at the annotation under key  3-9-4/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 611, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-4/3.png
We look at the annotation under key  3-9-4/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 612, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-4/4.png
We look at the annotation under key  3-9-4/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 613, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-5/1.png
We look at the annotation under key  3-9-5/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 614, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-5/2.png
We look at the annotation under key  3-9-5/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 615, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-5/3.png
We look at the annotation under key  3-9-5/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 616, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-5/4.png
We look at the annotation under key  3-9-5/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 617, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-6/1.png
We look at the annotation under key  3-9-6/1.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 618, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-6/2.png
We look at the annotation under key  3-9-6/2.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 619, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-6/3.png
We look at the annotation under key  3-9-6/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 620, name /Volumes/Expansion/AI2 results 20240119/3-9/before/profilometer/3-9-6/4.png
We look at the annotation under key  3-9-6/4.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 621, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-1/1.png
We look at the annotation under key  4-1-1/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 622, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-1/2.png
We look at the annotation under key  4-1-1/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 623, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-1/3.png
We look at the annotation under key  4-1-1/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 624, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-1/4.png
We look at the annotation under key  4-1-1/4.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 625, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-2/1.png
We look at the annotation under key  4-1-2/1.png

Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 626, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-2/2.png
We look at the annotation under key  4-1-2/2.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 627, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-2/3.png
We look at the annotation under key  4-1-2/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 628, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-2/4.png
We look at the annotation under key  4-1-2/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 629, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-3/1.png
We look at the annotation under key  4-1-3/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 630, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-3/2.png
We look at the annotation under key  4-1-3/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 631, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-3/3.png
We look at the annotation under key  4-1-3/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 632, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-3/4.png
We look at the annotation under key  4-1-3/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 633, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-4/1.png
We look at the annotation under key  4-1-4/1.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 634, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-4/2.png
We look at the annotation under key  4-1-4/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 635, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-4/3.png
We look at the annotation under key  4-1-4/3.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 636, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-4/4.png
We look at the annotation under key  4-1-4/4.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 637, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-5/1.png
We look at the annotation under key  4-1-5/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 638, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-5/2.png
We look at the annotation under key  4-1-5/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 639, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-5/3.png
We look at the annotation under key  4-1-5/3.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 640, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-5/4.png
We look at the annotation under key  4-1-5/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 641, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-6/1.png
We look at the annotation under key  4-1-6/1.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 642, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-6/2.png
We look at the annotation under key  4-1-6/2.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 643, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-6/3.png
We look at the annotation under key  4-1-6/3.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 644, name /Volumes/Expansion/AI2 results 20240119/4-1/before/profilometer/4-1-6/4.png
We look at the annotation under key  4-1-6/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 645, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-1/1.png
We look at the annotation under key  4-3-1/1.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 646, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-1/2.png
We look at the annotation under key  4-3-1/2.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 647, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-1/3.png
We look at the annotation under key  4-3-1/3.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 648, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-1/4.png
We look at the annotation under key  4-3-1/4.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 649, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-2/1.png
We look at the annotation under key  4-3-2/1.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 650, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-2/2.png
We look at the annotation under key  4-3-2/2.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 651, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-2/3.png
We look at the annotation under key  4-3-2/3.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 652, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-2/4.png
We look at the annotation under key  4-3-2/4.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 653, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-3/1.png
We look at the annotation under key  4-3-3/1.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 654, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-3/2.png
We look at the annotation under key  4-3-3/2.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 655, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-3/3.png
We look at the annotation under key  4-3-3/3.png

Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 656, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-3/4.png
We look at the annotation under key  4-3-3/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 657, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-4/1.png
We look at the annotation under key  4-3-4/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 658, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-4/2.png
We look at the annotation under key  4-3-4/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 659, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-4/3.png
We look at the annotation under key  4-3-4/3.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 660, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-4/4.png
We look at the annotation under key  4-3-4/4.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 661, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-5/1.png
We look at the annotation under key  4-3-5/1.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 662, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-5/2.png
We look at the annotation under key  4-3-5/2.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 663, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-5/3.png
We look at the annotation under key  4-3-5/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 664, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-5/4.png
We look at the annotation under key  4-3-5/4.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 665, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-6/1.png
We look at the annotation under key  4-3-6/1.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 666, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-6/2.png
We look at the annotation under key  4-3-6/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 667, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-6/3.png
We look at the annotation under key  4-3-6/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 668, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-6/4.png
We look at the annotation under key  4-3-6/4.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 669, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-7/1.png
We look at the annotation under key  4-3-7/1.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 670, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-7/2.png
We look at the annotation under key  4-3-7/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 671, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-7/3.png
We look at the annotation under key  4-3-7/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 672, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-7/4.png
We look at the annotation under key  4-3-7/4.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 673, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-8/1.png
We look at the annotation under key  4-3-8/1.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 674, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-8/2.png
We look at the annotation under key  4-3-8/2.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 675, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-8/3.png
We look at the annotation under key  4-3-8/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 676, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-8/4.png
We look at the annotation under key  4-3-8/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 677, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-9/1.png
We look at the annotation under key  4-3-9/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 678, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-9/2.png
We look at the annotation under key  4-3-9/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 679, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-9/3.png
We look at the annotation under key  4-3-9/3.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 680, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-9/4.png
We look at the annotation under key  4-3-9/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 681, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-10/1.png
We look at the annotation under key  4-3-10/1.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 682, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-10/2.png
We look at the annotation under key  4-3-10/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 683, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-10/3.png
We look at the annotation under key  4-3-10/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 684, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-10/4.png
We look at the annotation under key  4-3-10/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 685, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-11/1.png
We look at the annotation under key  4-3-11/1.png

Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 686, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-11/2.png
We look at the annotation under key  4-3-11/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 687, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-11/3.png
We look at the annotation under key  4-3-11/3.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 688, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-11/4.png
We look at the annotation under key  4-3-11/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 689, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-12/1.png
We look at the annotation under key  4-3-12/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 690, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-12/2.png
We look at the annotation under key  4-3-12/2.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 691, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-12/3.png
We look at the annotation under key  4-3-12/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 692, name /Volumes/Expansion/AI2 results 20240119/4-3/before/profilometer/4-3-12/4.png
We look at the annotation under key  4-3-12/4.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 693, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-1/1.png
We look at the annotation under key  4-4-1/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 694, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-1/2.png
We look at the annotation under key  4-4-1/2.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 695, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-1/3.png
We look at the annotation under key  4-4-1/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 696, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-1/4.png
We look at the annotation under key  4-4-1/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 697, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-10/1.png
We look at the annotation under key  4-4-10/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 698, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-10/2.png
We look at the annotation under key  4-4-10/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 699, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-10/3.png
We look at the annotation under key  4-4-10/3.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 700, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-10/4.png
We look at the annotation under key  4-4-10/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 701, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-12/1.png
We look at the annotation under key  4-4-12/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 702, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-12/2.png
We look at the annotation under key  4-4-12/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 703, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-12/3.png
We look at the annotation under key  4-4-12/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 704, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-12/4.png
We look at the annotation under key  4-4-12/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 705, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-2/1.png
We look at the annotation under key  4-4-2/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 706, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-2/2.png
We look at the annotation under key  4-4-2/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 707, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-2/3.png
We look at the annotation under key  4-4-2/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 708, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-2/4.png
We look at the annotation under key  4-4-2/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 709, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-3/1.png
We look at the annotation under key  4-4-3/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 710, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-3/2.png
We look at the annotation under key  4-4-3/2.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 711, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-3/3.png
We look at the annotation under key  4-4-3/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 712, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-3/4.png
We look at the annotation under key  4-4-3/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 713, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-4/1.png
We look at the annotation under key  4-4-4/1.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 714, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-4/2.png
We look at the annotation under key  4-4-4/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 715, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-4/3.png
We look at the annotation under key  4-4-4/3.png

Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 716, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-4/4.png
We look at the annotation under key  4-4-4/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 717, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-5/1.png
We look at the annotation under key  4-4-5/1.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 718, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-5/2.png
We look at the annotation under key  4-4-5/2.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 719, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-5/3.png
We look at the annotation under key  4-4-5/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 720, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-5/4.png
We look at the annotation under key  4-4-5/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 721, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-6/1.png
We look at the annotation under key  4-4-6/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 722, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-6/2.png
We look at the annotation under key  4-4-6/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 723, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-6/3.png
We look at the annotation under key  4-4-6/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 724, name /Volumes/Expansion/AI2 results 20240119/4-4/before/profilometer/4-4-6/4.png
We look at the annotation under key  4-4-6/4.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 725, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-1/1.png
We look at the annotation under key  4-5-1/1.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 726, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-1/2.png
We look at the annotation under key  4-5-1/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 727, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-1/3.png
We look at the annotation under key  4-5-1/3.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 728, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-1/4.png
We look at the annotation under key  4-5-1/4.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 729, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-10/1.png
We look at the annotation under key  4-5-10/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 730, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-10/2.png
We look at the annotation under key  4-5-10/2.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 731, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-10/3.png
We look at the annotation under key  4-5-10/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 732, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-10/4.png
We look at the annotation under key  4-5-10/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 733, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-11/1.png
We look at the annotation under key  4-5-11/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 734, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-11/2.png
We look at the annotation under key  4-5-11/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 735, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-11/3.png
We look at the annotation under key  4-5-11/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 736, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-11/4.png
We look at the annotation under key  4-5-11/4.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 737, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-12/1.png
We look at the annotation under key  4-5-12/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 738, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-12/2.png
We look at the annotation under key  4-5-12/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 739, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-12/3.png
We look at the annotation under key  4-5-12/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 740, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-12/4.png
We look at the annotation under key  4-5-12/4.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 741, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-2/1.png
We look at the annotation under key  4-5-2/1.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 742, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-2/2.png
We look at the annotation under key  4-5-2/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 743, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-2/3.png
We look at the annotation under key  4-5-2/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 744, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-2/4.png
We look at the annotation under key  4-5-2/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 745, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-3/1.png
We look at the annotation under key  4-5-3/1.png

Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 746, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-3/2.png
We look at the annotation under key  4-5-3/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 747, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-3/3.png
We look at the annotation under key  4-5-3/3.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 748, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-3/4.png
We look at the annotation under key  4-5-3/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 749, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-4/1.png
We look at the annotation under key  4-5-4/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 750, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-4/2.png
We look at the annotation under key  4-5-4/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 751, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-4/3.png
We look at the annotation under key  4-5-4/3.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 752, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-4/4.png
We look at the annotation under key  4-5-4/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 753, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-5/1.png
We look at the annotation under key  4-5-5/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 754, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-5/2.png
We look at the annotation under key  4-5-5/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 755, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-5/3.png
We look at the annotation under key  4-5-5/3.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 756, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-5/4.png
We look at the annotation under key  4-5-5/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 757, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-6/1.png
We look at the annotation under key  4-5-6/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 758, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-6/2.png
We look at the annotation under key  4-5-6/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 759, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-6/3.png
We look at the annotation under key  4-5-6/3.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 760, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-6/4.png
We look at the annotation under key  4-5-6/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 761, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-7/1.png
We look at the annotation under key  4-5-7/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 762, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-7/2.png
We look at the annotation under key  4-5-7/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 763, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-7/3.png
We look at the annotation under key  4-5-7/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 764, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-7/4.png
We look at the annotation under key  4-5-7/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 765, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-8/1.png
We look at the annotation under key  4-5-8/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 766, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-8/2.png
We look at the annotation under key  4-5-8/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 767, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-8/3.png
We look at the annotation under key  4-5-8/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 768, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-8/4.png
We look at the annotation under key  4-5-8/4.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 769, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-9/1.png
We look at the annotation under key  4-5-9/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 770, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-9/2.png
We look at the annotation under key  4-5-9/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 771, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-9/3.png
We look at the annotation under key  4-5-9/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 772, name /Volumes/Expansion/AI2 results 20240119/4-5/before/profilometer/4-5-9/4.png
We look at the annotation under key  4-5-9/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 773, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-1/1.png
We look at the annotation under key  4-6-1/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 774, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-1/2.png
We look at the annotation under key  4-6-1/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 775, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-1/3.png
We look at the annotation under key  4-6-1/3.png

Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 776, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-1/4.png
We look at the annotation under key  4-6-1/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 777, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-10/1.png
We look at the annotation under key  4-6-10/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 778, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-10/2.png
We look at the annotation under key  4-6-10/2.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 779, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-10/3.png
We look at the annotation under key  4-6-10/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 780, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-10/4.png
We look at the annotation under key  4-6-10/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 781, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-12/1.png
We look at the annotation under key  4-6-12/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 782, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-12/2.png
We look at the annotation under key  4-6-12/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 783, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-12/3.png
We look at the annotation under key  4-6-12/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 784, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-12/4.png
We look at the annotation under key  4-6-12/4.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 785, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-2/1.png
We look at the annotation under key  4-6-2/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 786, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-2/2.png
We look at the annotation under key  4-6-2/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 787, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-2/3.png
We look at the annotation under key  4-6-2/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 788, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-2/4.png
We look at the annotation under key  4-6-2/4.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 789, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-3/1.png
We look at the annotation under key  4-6-3/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 790, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-3/2.png
We look at the annotation under key  4-6-3/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 791, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-3/3.png
We look at the annotation under key  4-6-3/3.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 792, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-3/4.png
We look at the annotation under key  4-6-3/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 793, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-4/1.png
We look at the annotation under key  4-6-4/1.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 794, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-4/2.png
We look at the annotation under key  4-6-4/2.png
Got everything patched
4/4 [==============================] - 22s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 795, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-4/3.png
We look at the annotation under key  4-6-4/3.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 796, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-4/4.png
We look at the annotation under key  4-6-4/4.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 797, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-5/1.png
We look at the annotation under key  4-6-5/1.png
Got everything patched
4/4 [==============================] - 21s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 798, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-5/2.png
We look at the annotation under key  4-6-5/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 799, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-5/3.png
We look at the annotation under key  4-6-5/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 800, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-5/4.png
We look at the annotation under key  4-6-5/4.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 801, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-6/1.png
We look at the annotation under key  4-6-6/1.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 802, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-6/2.png
We look at the annotation under key  4-6-6/2.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 803, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-6/3.png
We look at the annotation under key  4-6-6/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 804, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-6/4.png
We look at the annotation under key  4-6-6/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 805, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-7/1.png
We look at the annotation under key  4-6-7/1.png

Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 806, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-7/2.png
We look at the annotation under key  4-6-7/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 807, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-7/3.png
We look at the annotation under key  4-6-7/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 808, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-7/4.png
We look at the annotation under key  4-6-7/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 809, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-8/1.png
We look at the annotation under key  4-6-8/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 810, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-8/2.png
We look at the annotation under key  4-6-8/2.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 811, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-8/3.png
We look at the annotation under key  4-6-8/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 812, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-8/4.png
We look at the annotation under key  4-6-8/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 813, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-9/1.png
We look at the annotation under key  4-6-9/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 814, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-9/2.png
We look at the annotation under key  4-6-9/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 815, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-9/3.png
We look at the annotation under key  4-6-9/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 816, name /Volumes/Expansion/AI2 results 20240119/4-6/before/profilometer/4-6-9/4.png
We look at the annotation under key  4-6-9/4.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 817, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-1/1.png
We look at the annotation under key  4-7-1/1.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 818, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-1/2.png
We look at the annotation under key  4-7-1/2.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 819, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-1/3.png
We look at the annotation under key  4-7-1/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 820, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-1/4.png
We look at the annotation under key  4-7-1/4.png
Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 821, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-10/1.png
We look at the annotation under key  4-7-10/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 822, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-10/2.png
We look at the annotation under key  4-7-10/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 823, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-10/3.png
We look at the annotation under key  4-7-10/3.png
Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 824, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-10/4.png
We look at the annotation under key  4-7-10/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 825, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-11/1.png
We look at the annotation under key  4-7-11/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 826, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-11/2.png
We look at the annotation under key  4-7-11/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 827, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-11/3.png
We look at the annotation under key  4-7-11/3.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 828, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-11/4.png
We look at the annotation under key  4-7-11/4.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 829, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-12/1.png
We look at the annotation under key  4-7-12/1.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 830, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-12/2.png
We look at the annotation under key  4-7-12/2.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 831, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-12/3.png
We look at the annotation under key  4-7-12/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 832, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-12/4.png
We look at the annotation under key  4-7-12/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 833, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-2/1.png
We look at the annotation under key  4-7-2/1.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 834, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-2/2.png
We look at the annotation under key  4-7-2/2.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 835, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-2/3.png
We look at the annotation under key  4-7-2/3.png

Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 836, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-2/4.png
We look at the annotation under key  4-7-2/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 837, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-3/1.png
We look at the annotation under key  4-7-3/1.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 838, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-3/2.png
We look at the annotation under key  4-7-3/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 839, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-3/3.png
We look at the annotation under key  4-7-3/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 840, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-3/4.png
We look at the annotation under key  4-7-3/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 841, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-4/1.png
We look at the annotation under key  4-7-4/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 842, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-4/2.png
We look at the annotation under key  4-7-4/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 843, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-4/3.png
We look at the annotation under key  4-7-4/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 844, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-4/4.png
We look at the annotation under key  4-7-4/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 845, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-5/1.png
We look at the annotation under key  4-7-5/1.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 846, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-5/2.png
We look at the annotation under key  4-7-5/2.png
Got everything patched
4/4 [==============================] - 14s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 847, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-5/3.png
We look at the annotation under key  4-7-5/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 848, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-5/4.png
We look at the annotation under key  4-7-5/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 849, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-6/1.png
We look at the annotation under key  4-7-6/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 850, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-6/2.png
We look at the annotation under key  4-7-6/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 851, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-6/3.png
We look at the annotation under key  4-7-6/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 852, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-6/4.png
We look at the annotation under key  4-7-6/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 853, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-7/1.png
We look at the annotation under key  4-7-7/1.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 854, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-7/2.png
We look at the annotation under key  4-7-7/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 855, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-7/3.png
We look at the annotation under key  4-7-7/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 856, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-7/4.png
We look at the annotation under key  4-7-7/4.png
Got everything patched
4/4 [==============================] - 15s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 857, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-8/1.png
We look at the annotation under key  4-7-8/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 858, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-8/2.png
We look at the annotation under key  4-7-8/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 859, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-8/3.png
We look at the annotation under key  4-7-8/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 860, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-8/4.png
We look at the annotation under key  4-7-8/4.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 861, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-9/1.png
We look at the annotation under key  4-7-9/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 862, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-9/2.png
We look at the annotation under key  4-7-9/2.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 863, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-9/3.png
We look at the annotation under key  4-7-9/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 864, name /Volumes/Expansion/AI2 results 20240119/4-7/before/profilometer/4-7-9/4.png
We look at the annotation under key  4-7-9/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 865, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/1.png
We look at the annotation under key  4-2-1/1.png

Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 866, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/._1.png
We look at the annotation under key  4-2-1/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/._1.png
Starting on file 867, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/2.png
We look at the annotation under key  4-2-1/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 868, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/._2.png
We look at the annotation under key  4-2-1/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/._2.png
Starting on file 869, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/3.png
We look at the annotation under key  4-2-1/3.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 870, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/._3.png
We look at the annotation under key  4-2-1/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/._3.png
Starting on file 871, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/4.png
We look at the annotation under key  4-2-1/4.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 872, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/._4.png
We look at the annotation under key  4-2-1/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-1/._4.png
Starting on file 873, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/1.png
We look at the annotation under key  4-2-2/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 874, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/._1.png
We look at the annotation under key  4-2-2/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/._1.png
Starting on file 875, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/2.png
We look at the annotation under key  4-2-2/2.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 876, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/._2.png
We look at the annotation under key  4-2-2/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/._2.png
Starting on file 877, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/3.png
We look at the annotation under key  4-2-2/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 878, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/._3.png
We look at the annotation under key  4-2-2/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/._3.png
Starting on file 879, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/4.png
We look at the annotation under key  4-2-2/4.png

Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 880, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/._4.png
We look at the annotation under key  4-2-2/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-2/._4.png
Starting on file 881, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/1.png
We look at the annotation under key  4-2-3/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 882, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/._1.png
We look at the annotation under key  4-2-3/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/._1.png
Starting on file 883, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/2.png
We look at the annotation under key  4-2-3/2.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 884, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/._2.png
We look at the annotation under key  4-2-3/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/._2.png
Starting on file 885, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/3.png
We look at the annotation under key  4-2-3/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 886, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/._3.png
We look at the annotation under key  4-2-3/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/._3.png
Starting on file 887, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/4.png
We look at the annotation under key  4-2-3/4.png
Got everything patched
4/4 [==============================] - 13s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 888, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/._4.png
We look at the annotation under key  4-2-3/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-3/._4.png
Starting on file 889, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/1.png
We look at the annotation under key  4-2-4/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 890, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/._1.png
We look at the annotation under key  4-2-4/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/._1.png
Starting on file 891, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/2.png
We look at the annotation under key  4-2-4/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 892, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/._2.png
We look at the annotation under key  4-2-4/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/._2.png
Starting on file 893, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/3.png
We look at the annotation under key  4-2-4/3.png

Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 894, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/._3.png
We look at the annotation under key  4-2-4/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/._3.png
Starting on file 895, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/4.png
We look at the annotation under key  4-2-4/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 896, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/._4.png
We look at the annotation under key  4-2-4/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-4/._4.png
Starting on file 897, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/1.png
We look at the annotation under key  4-2-5/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 898, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/._1.png
We look at the annotation under key  4-2-5/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/._1.png
Starting on file 899, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/2.png
We look at the annotation under key  4-2-5/2.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 900, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/._2.png
We look at the annotation under key  4-2-5/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/._2.png
Starting on file 901, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/3.png
We look at the annotation under key  4-2-5/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 902, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/._3.png
We look at the annotation under key  4-2-5/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/._3.png
Starting on file 903, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/4.png
We look at the annotation under key  4-2-5/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 904, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/._4.png
We look at the annotation under key  4-2-5/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-5/._4.png
Starting on file 905, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/1.png
We look at the annotation under key  4-2-6/1.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 906, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/._1.png
We look at the annotation under key  4-2-6/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/._1.png
Starting on file 907, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/2.png
We look at the annotation under key  4-2-6/2.png

Got everything patched
4/4 [==============================] - 19s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 908, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/._2.png
We look at the annotation under key  4-2-6/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/._2.png
Starting on file 909, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/3.png
We look at the annotation under key  4-2-6/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 910, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/._3.png
We look at the annotation under key  4-2-6/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/._3.png
Starting on file 911, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/4.png
We look at the annotation under key  4-2-6/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 912, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/._4.png
We look at the annotation under key  4-2-6/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-6/._4.png
Starting on file 913, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/1.png
We look at the annotation under key  4-2-9/1.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 914, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/._1.png
We look at the annotation under key  4-2-9/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/._1.png
Starting on file 915, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/2.png
We look at the annotation under key  4-2-9/2.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 916, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/._2.png
We look at the annotation under key  4-2-9/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/._2.png
Starting on file 917, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/3.png
We look at the annotation under key  4-2-9/3.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 918, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/._3.png
We look at the annotation under key  4-2-9/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/._3.png
Starting on file 919, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/4.png
We look at the annotation under key  4-2-9/4.png
Got everything patched
4/4 [==============================] - 18s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 920, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/._4.png
We look at the annotation under key  4-2-9/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-9/._4.png
Starting on file 921, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/1.png
We look at the annotation under key  4-2-10/1.png

Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 922, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/._1.png
We look at the annotation under key  4-2-10/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/._1.png
Starting on file 923, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/2.png
We look at the annotation under key  4-2-10/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 924, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/._2.png
We look at the annotation under key  4-2-10/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/._2.png
Starting on file 925, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/3.png
We look at the annotation under key  4-2-10/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 926, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/._3.png
We look at the annotation under key  4-2-10/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/._3.png
Starting on file 927, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/4.png
We look at the annotation under key  4-2-10/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 928, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/._4.png
We look at the annotation under key  4-2-10/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-10/._4.png
Starting on file 929, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-11/1.png
We look at the annotation under key  4-2-11/1.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 930, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-11/._1.png
We look at the annotation under key  4-2-11/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-11/._1.png
Starting on file 931, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-11/2.png
We look at the annotation under key  4-2-11/2.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 932, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-11/._2.png
We look at the annotation under key  4-2-11/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-11/._2.png
Starting on file 933, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-11/3.png
We look at the annotation under key  4-2-11/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 934, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-11/._3.png
We look at the annotation under key  4-2-11/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-11/._3.png
Starting on file 935, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/1.png
We look at the annotation under key  4-2-12/1.png

Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 936, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/._1.png
We look at the annotation under key  4-2-12/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/._1.png
Starting on file 937, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/2.png
We look at the annotation under key  4-2-12/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 938, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/._2.png
We look at the annotation under key  4-2-12/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/._2.png
Starting on file 939, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/3.png
We look at the annotation under key  4-2-12/3.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 940, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/._3.png
We look at the annotation under key  4-2-12/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/._3.png
Starting on file 941, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/4.png
We look at the annotation under key  4-2-12/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 942, name /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/._4.png
We look at the annotation under key  4-2-12/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/4-2/before/profilometer/4-2-12/._4.png
Starting on file 943, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/._1.png
We look at the annotation under key  5-1-4/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/._1.png
Starting on file 944, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/1.png
We look at the annotation under key  5-1-4/1.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 945, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/._2.png
We look at the annotation under key  5-1-4/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/._2.png
Starting on file 946, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/2.png
We look at the annotation under key  5-1-4/2.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 947, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/._3.png
We look at the annotation under key  5-1-4/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/._3.png
Starting on file 948, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/3.png
We look at the annotation under key  5-1-4/3.png

Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 949, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/._4.png
We look at the annotation under key  5-1-4/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/._4.png
Starting on file 950, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-4/4.png
We look at the annotation under key  5-1-4/4.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 951, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/._1.png
We look at the annotation under key  5-1-1/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/._1.png
Starting on file 952, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/1.png
We look at the annotation under key  5-1-1/1.png
Got everything patched
4/4 [==============================] - 15s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 953, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/._2.png
We look at the annotation under key  5-1-1/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/._2.png
Starting on file 954, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/2.png
We look at the annotation under key  5-1-1/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 955, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/._3.png
We look at the annotation under key  5-1-1/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/._3.png
Starting on file 956, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/3.png
We look at the annotation under key  5-1-1/3.png
Got everything patched
4/4 [==============================] - 16s 3s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 957, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/._4.png
We look at the annotation under key  5-1-1/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/._4.png
Starting on file 958, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-1/4.png
We look at the annotation under key  5-1-1/4.png
Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 959, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/._1.png
We look at the annotation under key  5-1-5/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/._1.png
Starting on file 960, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/1.png
We look at the annotation under key  5-1-5/1.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 961, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/._2.png
We look at the annotation under key  5-1-5/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/._2.png
Starting on file 962, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/2.png
We look at the annotation under key  5-1-5/2.png

Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 963, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/._3.png
We look at the annotation under key  5-1-5/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/._3.png
Starting on file 964, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/3.png
We look at the annotation under key  5-1-5/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 965, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/._4.png
We look at the annotation under key  5-1-5/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/._4.png
Starting on file 966, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-5/4.png
We look at the annotation under key  5-1-5/4.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 967, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/._1.png
We look at the annotation under key  5-1-6/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/._1.png
Starting on file 968, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/1.png
We look at the annotation under key  5-1-6/1.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 969, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/._2.png
We look at the annotation under key  5-1-6/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/._2.png
Starting on file 970, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/2.png
We look at the annotation under key  5-1-6/2.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 971, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/._3.png
We look at the annotation under key  5-1-6/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/._3.png
Starting on file 972, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/3.png
We look at the annotation under key  5-1-6/3.png
Got everything patched
4/4 [==============================] - 16s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 973, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/._4.png
We look at the annotation under key  5-1-6/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/._4.png
Starting on file 974, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-6/4.png
We look at the annotation under key  5-1-6/4.png
Got everything patched
4/4 [==============================] - 17s 4s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 975, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/._1.png
We look at the annotation under key  5-1-3/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/._1.png
Starting on file 976, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/1.png
We look at the annotation under key  5-1-3/1.png

Got everything patched
4/4 [==============================] - 17s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 977, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/._2.png
We look at the annotation under key  5-1-3/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/._2.png
Starting on file 978, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/2.png
We look at the annotation under key  5-1-3/2.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 979, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/._3.png
We look at the annotation under key  5-1-3/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/._3.png
Starting on file 980, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/3.png
We look at the annotation under key  5-1-3/3.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 981, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/._4.png
We look at the annotation under key  5-1-3/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/._4.png
Starting on file 982, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-3/4.png
We look at the annotation under key  5-1-3/4.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 983, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/._1.png
We look at the annotation under key  5-1-2/._1.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/._1.png
Starting on file 984, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/1.png
We look at the annotation under key  5-1-2/1.png
Got everything patched
4/4 [==============================] - 18s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 985, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/._2.png
We look at the annotation under key  5-1-2/._2.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/._2.png
Starting on file 986, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/2.png
We look at the annotation under key  5-1-2/2.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 987, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/._3.png
We look at the annotation under key  5-1-2/._3.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/._3.png
Starting on file 988, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/3.png
We look at the annotation under key  5-1-2/3.png
Got everything patched
4/4 [==============================] - 19s 5s/step
Predicted everything
Reconstructed
Vol loss done
Starting on file 989, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/._4.png
We look at the annotation under key  5-1-2/._4.png
BAD, problem Traceback (most recent call last):
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2617601841.py", line 17, in <module>
    orig_prof = mask(resize_profilometer(prof_filename , resize_coeff=1), c=c1[prof_filename.split("/")[-2]+"/"+prof_filename.split("/")[-1]])
  File "/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2998290373.py", line 26, in resize_profilometer
    pic_profilometer_temp = Image.fromarray(cv2.imread(filepath))#[:1664, :1792])
  File "/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/PIL/Image.py", line 3059, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'
 with file /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/._4.png
Starting on file 990, name /Volumes/Expansion/AI2 results 20240119/5-1/before/profilometer/5-1-2/4.png
We look at the annotation under key  5-1-2/4.png

Got everything patched
4/4 [==============================] - 20s 5s/step
Predicted everything
Reconstructed
Vol loss done

In [12]:
import copy
orig_vol_losses_all = copy.deepcopy(vol_losses_all)
orig_all_filenames_prof = copy.deepcopy(all_filenames_prof)

underscore_mask = np.array(['_' in orig_all_filenames_prof[i] for i in range(len(orig_all_filenames_prof))])

all_filenames_prof = np.array(orig_all_filenames_prof)[~underscore_mask]
vol_losses_all = np.array(orig_vol_losses_all)[~underscore_mask]

In [13]:
material_numbers_all = [all_filenames_prof[i].split('/')[-2] for i in range(len(all_filenames_prof))]
unique_materials = list(set(material_numbers_all))

In [14]:
orig_materials_all = copy.deepcopy(materials_all)

materials_all = np.array(materials_all)[~underscore_mask]

In [15]:
all_filenames_prof

array(['/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-1/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-1/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-1/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-1/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-10/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-10/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-10/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-10/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-11/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-11/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-11/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-11/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-12/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-12/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-12/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-12/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-2/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-2/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-2/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-2/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-3/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-3/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-3/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-3/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-4/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-4/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-4/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-4/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-5/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-5/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-5/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-5/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-6/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-6/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-6/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-6/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-7/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-7/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-7/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-7/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-8/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-8/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-8/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-8/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-9/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-9/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-9/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/1-1-9/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-1/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-1/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-1/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-1/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-10/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-10/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-10/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-10/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-2/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-2/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-2/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-2/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-3/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-3/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-3/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-3/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-4/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-4/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-4/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-4/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-5/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-5/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-5/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-5/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-6/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-6/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-6/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-6/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-7/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-7/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-7/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-7/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-8/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-8/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-8/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-8/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-9/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-9/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-9/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-2/before/profilometer/1-2-9/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-10/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-10/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-10/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-10/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-2/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-2/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-2/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-2/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-3/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-3/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-3/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-3/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-4/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-4/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-4/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-4/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-5/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-5/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-5/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-5/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-6/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-6/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-6/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-6/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-7/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-7/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-7/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-7/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-8/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-8/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-8/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-8/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-9/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-9/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-9/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-3/before/profilometer/1-3-9/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-1/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-1/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-1/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-1/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-10/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-10/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-10/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-10/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-11/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-11/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-11/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-11/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-12/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-12/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-12/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-12/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-2/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-2/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-2/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-2/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-3/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-3/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-3/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-3/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-4/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-4/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-4/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-4/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-5/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-5/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-5/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-5/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-6/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-6/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-6/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-6/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-7/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-7/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-7/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-7/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-8/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-8/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-8/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-8/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-9/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-9/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-9/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-5/before/profilometer/1-5-9/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-1/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-1/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-1/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-1/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-10/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-2/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-2/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-2/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-2/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-3/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-3/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-3/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-3/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-4/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-4/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-4/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-4/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-5/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-5/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-5/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-5/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-6/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-6/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-6/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-6/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-7/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-7/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-7/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-7/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-8/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-8/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-8/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-8/4.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-9/1.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-9/2.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-9/3.png',
       '/Volumes/Expansion/AI2 results 20240119/1-6/before/profilometer/1-6-9/4.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-1/1.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-1/2.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-1/3.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-1/4.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-10/1.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-10/2.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-10/3.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-10/4.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-11/1.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-11/2.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-11/3.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-11/4.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-12/1.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-12/2.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-12/3.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-12/4.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-2/1.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-2/2.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-2/3.png',
       '/Volumes/Expansion/AI2 results 20240119/2-1/before/profilometer/2-1-2/4.png',

In [17]:
#FORMAT EVALUATION BY MATERIAL
vol_losses_materials = {}
weight_losses_NaCl_materials = {}
vol_losses_full_materials = {}
nccs_materials = {}
rel_maes_materials = {}
vol_loss_gt_materials = []
vol_loss_gt_full_materials = []
vol_loss_materials = []
inhibition_efficiency_materials = []
inhibition_efficiency_samples = []
weight_loss_NaCl_materials = []
weight_loss_predicted_NaCl_materials = []
ncc_materials = []
rel_mae_materials = []
vol_loss_materials = []
#unique_materials = list(materials_dict.keys())
for i in range(len(unique_materials)):
    try:
        a_splits = unique_materials[i].split('-')
        generic_material = a_splits[0]+'-'+a_splits[1]
        specific_material = a_splits[-1]
        vol_losses_materials[unique_materials[i]] = vol_losses_all[materials_all==unique_materials[i]]
        keys = np.array([generic_material+'-'+str(i+1) for i in range(int(specific_material)-1, 12) if generic_material+'-'+str(i+1) in materials_dict.keys()])
        #print(keys)
        NaCl_values = []
        for k in range(len(keys)):
            #print(materials_dict[keys[k]])
            if materials_dict[keys[k]]=='NaCl':
                vol_losses_temp = []
                for j in range(4):
                    #print("Looking for "+'/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/'+keys[k]+'/'+str(j+1)+'.png')
                    vol_losses_temp.extend(vol_losses_all[all_filenames_prof=='/Volumes/Expansion/AI2 results 20240119/'+generic_material+'/before/profilometer/'+keys[k]+'/'+str(j+1)+'.png'])
                    #print("Found such keys: "+str(sum(all_filenames_prof=='/Volumes/Expansion/AI2 results 20240119/'+generic_material+'/before/profilometer/'
                    #                                  +keys[k]+'/'+str(j+1)+'.png')))
                vol_losses_temp = [vol_losses_temp[l] for l in range(len(vol_losses_temp)) if vol_losses_temp[l] is not None]
                NaCl_values.append(np.nanmean(vol_losses_temp))
        #print("1. "+str(NaCl_values))
        if len(NaCl_values)==0:
            keys = np.array([generic_material+'-'+str(i+1) for i in range(12) if generic_material+'-'+str(i+1) in materials_dict.keys()])
            NaCl_values = []
            for k in range(len(keys)):
                if materials_dict[keys[k]]=='NaCl':
                    vol_losses_temp = []
                    for j in range(4):
                        #print("Looking for "+'/Volumes/Expansion/AI2 results 20240119/1-1/before/profilometer/'+keys[k]+'/'+str(j+1)+'.png')
                        vol_losses_temp.extend(vol_losses_all[all_filenames_prof=='/Volumes/Expansion/AI2 results 20240119/'+generic_material+'/before/profilometer/'+keys[k]+'/'+str(j+1)+'.png'])
                        #print("Found such keys: "+str(sum(all_filenames_prof==
                        #                                  '/Volumes/Expansion/AI2 results 20240119/'+generic_material+'/before/profilometer/'+keys[k]+'/'
                        #                                  +str(j+1)+'.png')))
                    vol_losses_temp = [vol_losses_temp[l] for l in range(len(vol_losses_temp)) if vol_losses_temp[l] is not None]
                    NaCl_values.append(np.nanmean(vol_losses_temp))
            NaCl_values = [NaCl_values[-1]]
        #print("2. "+str(NaCl_values))
        if isinstance(NaCl_weight_losses[generic_material], float):
            weight_losses_NaCl_materials[unique_materials[i]] = NaCl_weight_losses[generic_material]
        elif isinstance(NaCl_weight_losses[generic_material], tuple) and int(specific_material)<=6:
            weight_losses_NaCl_materials[unique_materials[i]] = NaCl_weight_losses[generic_material][0]
        elif isinstance(NaCl_weight_losses[generic_material], tuple) and int(specific_material)>6:
            weight_losses_NaCl_materials[unique_materials[i]] = NaCl_weight_losses[generic_material][1]
        vol_loss_materials.append(vol_losses_materials[unique_materials[i]])
        weight_loss_NaCl_materials.append(weight_losses_NaCl_materials[unique_materials[i]])
        weight_loss_predicted_NaCl_materials.append(get_weight_loss(NaCl_values[0]))
        #print(NaCl_values[0])
        #print(vol_loss_predicted_NaCl_materials[-1])
        ie_temp = []
        for j in range(len(vol_loss_materials[-1])) :
            if vol_loss_materials[-1][j] is not None:
                ie_temp.append(get_inhibition_efficiency(get_weight_loss(vol_loss_materials[-1][j]), weight_loss_predicted_NaCl_materials[-1]))
        inhibition_efficiency_materials.append(np.array(ie_temp).mean())
        inhibition_efficiency_samples.append(np.array(ie_temp))
    except Exception:
        print("BAD, problem {} with material {}".format(traceback.format_exc(), unique_materials[i]))
        print(unique_materials[i] in materials_all)
        print(vol_losses_all[materials_all==unique_materials[i]])
        print(vol_losses_materials[unique_materials[i]])

/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/942525564.py:37: RuntimeWarning: Mean of empty slice
  NaCl_values.append(np.nanmean(vol_losses_temp))
/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/942525564.py:70: RuntimeWarning: Mean of empty slice.
  inhibition_efficiency_materials.append(np.array(ie_temp).mean())
/Users/anna.lisitsyna/venvs/tf/lib/python3.10/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

In [18]:
#FORMAT THE EVALUATION DATA FOR SAVING

filenames_all = copy.copy(all_filenames_prof)

##PLOT THE TABLE
#rows = ["Compound number", 'Sample number', 'Volume loss predicted']
#metrics_dict = {}
#for sample_index in range(len(filenames_all)):
#    sample = filenames_all[sample_index].split('/')[-1].split('.')[0]
#    compound = filenames_all[sample_index].split('/')[-2]
#    metrics_dict[sample_index] = [compound, sample, vol_losses_all[sample_index]]
#evaluation_data  = pd.DataFrame(data=metrics_dict, index=rows).transpose()

#evaluation_data.to_excel('last_model_eval.xlsx')

#FORMAT EVALUATION DATA FOR MATERIALS
#PLOT THE TABLE
rows = ['Material name', 'Compound number','Volume loss predicted each sample', 
        'Volume loss predicted mean', 'Weight loss NaCl predicted', 'Weight loss NaCl from Ci Song',
        'Inhibition Efficiency', 'Inhibition efficiency per sample']

print(len(filenames_all))
print(len(unique_materials))
metrics_dict_materials = {}
for mat_index in range(len(unique_materials)):
    #print("Mat index is mat_index: ", mat_index)
    #print("Predicted volume loss: ", np.array(list(filter(None, vol_loss_materials[mat_index]))))
    if unique_materials[mat_index] in materials_all:
        metrics_dict_materials[mat_index] = [materials_dict[unique_materials[mat_index]], unique_materials[mat_index],
                                             vol_loss_materials[mat_index],np.array(list(filter(None, vol_loss_materials[mat_index]))).mean(), 
                                             weight_loss_predicted_NaCl_materials[mat_index], 
                                             weight_loss_NaCl_materials[mat_index], inhibition_efficiency_materials[mat_index], inhibition_efficiency_samples[mat_index]]
    else:
        metrics_dict_materials[mat_index] = [materials_dict[unique_materials[mat_index]], unique_materials[mat_index],
                                             None, None, 
                                             None, 
                                             None, None, None]
        
#print(f"Rows are {rows} with length {len(rows)}")
#print(f"Metrics_dict_materials are {metrics_dict_materials} with shape {metrics_dict_materials.shape}")
evaluation_data_materials  = pd.DataFrame(data=metrics_dict_materials, index=rows).transpose()

#SAVE EVALUATION DATA
evaluation_data_materials.to_excel("material_eval_temp_clip"+str(abs(clip_val))+".xlsx")

927
232

/var/folders/rh/wqjw407133jfhj_bhjtl3tgj23ky7h/T/ipykernel_19487/2047276829.py:30: RuntimeWarning: Mean of empty slice.
  vol_loss_materials[mat_index],np.array(list(filter(None, vol_loss_materials[mat_index]))).mean(),

In [19]:
evaluation_data_materials

,Material name,Compound number,Volume loss predicted each sample,Volume loss predicted mean,Weight loss NaCl predicted,Weight loss NaCl from Ci Song,Inhibition Efficiency,Inhibition efficiency per sample
0,2-2-Bipyridine-4-4-dicarboxylic acid,4-5-1,"[1.1732298701919586, 0.6939703579683763, 0.766...",0.913176,1.479921,0.82,-0.057995,"[-0.2913441095259718, 0.1653153868907089, 0.07..."
1,Phytic acid,4-6-7,"[0.3845856654619597, 0.6120935722899241, 0.686...",0.575324,0.95312,0.75,-0.049287,"[0.28176691427546097, -0.12519779960100377, -0..."
2,Pyrazole,2-2-8,"[0.6952292678062966, 0.6110675743782258, 0.674...",0.662367,1.320789,0.61,0.107341,"[0.06305355449338546, 0.17647656925521327, 0.0..."
3,NaCl,4-7-6,"[0.28440139716579627, 0.39632081894409354, 0.6...",0.760298,1.353331,0.68,0.181916,"[0.625934490772984, 0.4787298851799744, 0.1865..."
4,N-Lauroylsarcosine Na,4-5-11,"[0.5261962291366984, 0.45051044025745696, 0.69...",0.571401,1.862825,0.69,0.454005,"[0.4971995423058989, 0.5695201846485022, 0.338..."
...,...,...,...,...,...,...,...,...
227,"1,10-Phenanthroline monohydrate",4-6-5,"[0.5009861038178468, 0.8049521990595654, 0.458...",0.541441,1.060954,0.57,0.114346,"[0.15947760879285555, -0.25953198918644477, 0...."
228,"1,3,4-thiadiazole-2,5-dithiol (DMTD, bismuthio...",4-7-1,"[0.27654490323355213, 0.5902645519208278, 0.56...",0.488799,1.353331,0.68,0.357096,"[0.6362679259557606, 0.22364090896429967, 0.25..."
229,D-(+)-Galactose,3-1-3,"[0.45311247640386243, 0.3354153526938221, 0.69...",0.492744,NaN,0.5,NaN,"[nan, nan, nan, nan]"
230,NaCl,3-1-12,"[None, None, None, None]",NaN,NaN,0.85,NaN,[]
231,NaCl,1-6-9,"[0.743036240240178, 0.8770639902445672, 0.7366...",0.738053,1.313735,0.83,0.007474,"[-0.006706378251545584, -0.15849565554194428, ..."

In [20]:
#Load old table

original_table = pd.read_excel("/Users/anna.lisitsyna/Downloads/Result Table.xlsx")

In [21]:
#Combine the table and evaluation

original_table['Normalised name'] = original_table['Inhibitor'].map(normalise_name)
original_table[['Inhibitor', 'Normalised name']]
evaluation_data_materials['Normalised name']=evaluation_data_materials['Material name'].map(normalise_name)
important = evaluation_data_materials['Material name']!='NaCl'
evaluation_data_important = evaluation_data_materials[important]
important_old = original_table['Inhibitor']!='NaCl'
original_table_important = original_table[important_old]
merged_table_important = original_table_important.merge(evaluation_data_important, on='Normalised name')

In [22]:
evaluation_data_materials['SMILES'] = [None for i in range(len(unique_materials))]
for i in range(len(unique_materials)):
    print(evaluation_data_materials['Normalised name'][i])
    if evaluation_data_materials['Normalised name'][i] in list(original_table['Normalised name']):
        index_temp = list(original_table['Normalised name']).index(evaluation_data_materials['Normalised name'][i])
        evaluation_data_materials['SMILES'][i] = original_table['SMILES'][index_temp]
        
evaluation_data_materials.to_excel("/Users/anna.lisitsyna/Documents/EvaluationSubset_latest_clip"+str(abs(clip_val))+".xlsx")

2-2-bipyridine-4-4-dicarboxylic acid
phytic acid
pyrazole
nacl
n-lauroylsarcosine na
citric acid
taps
1,2,3-benzenetricarboxylic acid hydrate
glucose
cinnamaldehyde, (e)-
maleic acid
terephthalic acid
epps
3-hydroxy-4-nitrobenzoic acid
8-nitroquinoline
1,2,3,4-butanetetracarboxylic acid
salicylic acid
3 5-dimethylpyrazole-1-methanol  99%
4-isopropylbenzoic acid
nacl
2-amino-2-methyl-1,3-propanediol
fumaric acid
1-pheny-1,3-butanedione
3-amino-4-hydroxybenzoic acid
3-hydroxybenzoic acid
2-nitrobenzoic acid
bis-tris
1-2-4-5-benzenetetracarboxylic acid
malic acid
3,4-dihydroxybenzoic acid
3,4-pyridinedicarboxylic acid
lysine
decylphosphonic acid
acetic acid
nacl
2-amino-5-trifluoromethyl-1,3,4-thiadiazole
adipic acid
nacl
chitosan
ascorbic acid
iminodiacetic acid
edta
trans-3-(3-pyridyl)acrylic acid
nicotinic acid
quinic acid
nacl
acetamide
2-aminopyridine-3-carboxylic acid
methionine
(s)-(+)-glycidyl benzyl ether
5-nitro-1-10-phenanthroline
1-(2-hydroxyethyl)piperazine
citraconic acid
nacl
nacl
5-methyl-1,3-dihydro-2h-benzo[d]imidazole-2-thione
salicylaldehyde
nacl
n-octyl gallate
6-hydroxyquinoline
nacl
benzamide
glycine
nacl
tartronic acid
hypophosphorous acid
lactic acid
hexamethyleneteramine
2'-hydroxy-4'-methoxyaceto-phenone
3,5-dinitrosalicylic acid
1,3-benzenedimethanol, 2-hydroxy-5-methyl-
salicylaldoxime
diethylenetriamine-pentaacetic acid na5
4,5-diamino-2,6-dimercaptopyrimidine
3-nitrosalicylic acid
bis-tris propane
2,6-diamino-4-chloropyrimidine
2-hydroxy-1,4-naphtoquinone
tartaric acid (l-(+)-tartaric acid,l-threaric acid, (2r,3r)-(+)-tartaric acid)
5-sulfosalicylic acid
nacl
succinic acid
4-quinolinol
nacl
nacl
nacl
4-aminosalicylic acid
2-nitroterephthalic acid
2-mercaptopyridine-3-carboxylic acid
hydroquinonesulfonic acid potassium salt
cydta/trans-12-diamino
anthraquinone-2-sulfonic acid sodium salt monohydrate
4-amino-6-mercapto-1h-pyrazolo[3,4-d]pyrimidine
4-amino-4h-1,2,4-triazole
6-mercaptopyridine-3-carboxylic acid
6-phosphonohexanoic acid
1-undecanethiol
2,3-pyridinedicarboxylic acid
pyrazine
nacl
potassium l-tartrate monobasic  99%
thiourea
4-mercaptobenzoic acid
terephthalic acid
lactobionic acid
5-nitrouracil
malonic acid
tannic acid
nacl
4-methylsalicylic
furylacrylic acid
quinaldic acid
picolinic acid
tricarballylic acid
8-hydroxy-7-iodo-5-quinolinesulfonic acid
di-kaliumoxalat monohydrat
(aces) n-(2-acetamido)-2-aminoethanesulfonic acid
nacl
dimethyl 2,6-pyridinedicarboxylate
2,6-pyridinedicarboxylic acid
3-(4-pyridyl)acrylic acid
sodium dodecylbenzene sulfonate
4,6-diamino-2-pyrimidinethiol
kojic acid
cyclohexaneacetic acid
5,5-dimethylhydantoin
nacl
cyclohexanemethanol
ethylenediamine
2,2' bipyridyl
l-cysteine
nacl
sodium-2-mercaptoethanesulfonate
dimethyl 5-hydroxyisophthalate
l-ornithine hydrochloride
1,2,4-triazole
nacl
nacl
alginic acid sodium salt from brown algae
β-d-glucopyranose, 4-o-β-d-galactopyranosyl-
3-methylcinnamic acid
2 2'-(ethylenedioxy)bis(ethylamine)  98%
nacl
p-toluic acid
3-(2-thienyl)acrylic acid
phenylphosphonic acid
8-hydroxy-5-quinoline sulfonic acid
n-(2-hydroxyethyl)ethylenediamine-n n' n trisodium salt
tri-natriumcitrat dihydrat
nacl
5-aminosalicylic acid
nacl
4-hydroxybenzoic acid
2,2′-(ethylenedithio)diacetic acid
nacl
dimethylolpropionic acid 2,2-bis(hydroxymethyl)propionic acid
nacl
nacl
2-(3,5-dimethylphenyl)acetic acid
glycolic acid
uracil
folic acid
3-hydroxy-1 2-dimethyl-4(1h)-pyridone  &
4-amino-3-hydrazino-5-mercapto-1,2,4-triazole
2,5-dimethyl-1,3,4-thiadiazole
mandelic acid
3,5-dimethylpyrazole
4,4′-dithiodibutyric acid
mellitic acid
2-mercapto-1-methylimidazole
nacl
nacl
d-pinitol
trimesic acid
5-methylsalicylic acid
nacl
nacl
benzotriazole
3-mercaptobenzoic acid
penicillin g na salt
2-amino-5-methyl-salicylic acid
3-methylsalicylic
3-methyl-2-nitrobenzoic acid
p-phenylenediacetic acid
pyrazinecarboxylic acid
thiosalicylic acid
8-hydroxyquinoline
5-nitrobarbituric acid trihydrate
ampso
nacl
phthalic acid
dextran
nacl
nacl
3-nitrophthalic acid
salicylhydroxamic acid
n,n′-trimethyleneurea
l-asparagine
gly-gly hydrochloride
nacl
4-tert-butylbenzoic acid
2,2′-thiodiacetic acid
n-(2-hydroxyethyl)iminodiacetic acid  >&
stearic acid sodium salt
oxalic acid
taurine
nacl
sodium formate
urea
benzoic acid
2,5-pyridinedicarboxylic acid
nacl
2-mercaptoimidazole
diglycolic acid
nacl
maltol
nacl
aspartic acid/(s)-aminobutanedioic acid, (s)-(+)-aminosuccinic acid, l-aspartic acid
nacl
5-amino-1 3 4-thiadiazole-2-thiol  98%
piperazine
8-aminoquinoline
(r)-(−)-glycidyl benzyl ether
4-nitrophthalic acid
itaconic acid
phenylphosphonic acid
5-aminoisoquinoline
1,10-phenanthroline monohydrate
1,3,4-thiadiazole-2,5-dithiol (dmtd, bismuthiol) salt
d-(+)-galactose
nacl
nacl

In [23]:
real_volume_losses = []
for i in range(len(evaluation_data_materials['Compound number'])):
    name_num = evaluation_data_materials['Compound number'][i]
    idx = vol_losses_real.index[vol_losses_real['Name ']==name_num].tolist()
    real_vol_loss_temp = []
    for i in range(4):
        real_vol_loss_temp.extend(vol_losses_real.iloc[idx][i+1].tolist())
    real_volume_losses.append(real_vol_loss_temp)
real_volume_losses

[[0.4, 0.484, 0.35, 0.414],
 [0.797, 0.905, 0.853, 0.942],
 [0.311, 0.286, 0.262, 0.237],
 [0.402, 0.378, 0.354, 0.405],
 [0.236, 0.349, 0.311, 0.308],
 [1.167, 1.378, 1.179, 1.172],
 [0.767, 0.845, 0.883, 1.091],
 [0.161, 0.191, 0.176, 0.277],
 [0.286, 0.381, 0.247, 0.348],
 [0.312, 0.257, 0.345, 0.191],
 [0.186, 0.234, 0.35, 0.41],
 [0.039, 0.057, 0.116, 0.133],
 [1.123, 1.112, 1.176, 1.338],
 [0.347, 0.241, 0.606, 0.483],
 [0.217, 0.182, 0.291, 0.32],
 [0.246, 0.21, 0.293, 0.265],
 [0.405, 0.19, 0.369, 0.178],
 [0.197, 0.383, 0.298, 0.339],
 [0.324, 0.393, 0.384, 0.37],
 [0.45, 0.42, 0.442, 0.37],
 [1.015, 0.939, 0.888, 0.903],
 [0.136, 0.133, 0.109, 0.097],
 [0.208, 0.353, 0.321, 0.31],
 [0.432, 0.511, 0.421, 0.43],
 [0.49, 0.529, 0.582, 0.687],
 [0.749, 0.875, 0.805, 0.628],
 [0.572, 0.596, 0.51, 0.599],
 [0.168, 0.161, 0.147, 0.163],
 [0.063, 0.229, 0.181, 0.216],
 [1.1, 1.19, 1.14, 1.21],
 [0.145, 0.272, 0.165, 0.164],
 [0.684, 0.815, 0.797, 0.963],
 [0.245, 0.3, 0.262, 0.286],
 [0.299, 0.339, 0.357, 0.238],
 [0.444, 0.413, 0.292, 0.403],
 [0.234, 0.245, 0.187, 0.212],
 [0.499, 0.364, 0.337, 0.344],
 [0.405, 0.352, 0.435, 0.493],
 [0.258, 0.269, 0.27, 0.274],
 [0.336, 0.346, 0.408, 0.359],
 [0.715, 0.654, 0.575, 0.663],
 [1.087, 1.202, 1.181, 1.211],
 [0.208, 0.247, 0.204, 0.278],
 [0.268, 0.255, 0.312, 0.205],
 [0.224, 0.214, 0.249, 0.279],
 [0.26, 0.29, 0.266, 0.287],
 [0.309, 0.362, 0.484, 0.368],
 [0.643, 0.436, 0.454, 0.481],
 [0.568, 0.622, 0.806, 0.813],
 [0.252, 0.272, 0.299, 0.312],
 [0.388, 0.222, 0.536, 0.309],
 [0.689, 0.648, 0.744, 0.693],
 [0.229, 0.32, 0.269, 0.277],
 [0.218, -1.0, 0.385, 0.285],
 [0.277, 0.25, 0.406, 0.437],
 [0.17, 0.172, 0.212, 0.167],
 [0.242, 0.223, 0.281, 0.222],
 [0.33, 0.233, 0.283, 0.28],
 [0.218, 0.162, 0.166, 0.198],
 [0.277, 0.325, 0.272, 0.331],
 [0.317, 0.35, 0.281, 0.273],
 [0.287, 0.226, 0.394, 0.292],
 [0.721, 0.728, 0.916, 0.751],
 [0.371, 0.329, 0.313, 0.365],
 [0.263, 0.307, 0.249, 0.213],
 [0.526, 0.541, 0.525, 0.606],
 [0.427, 0.512, 0.498, 0.409],
 [0.348, 0.559, 0.411, 0.359],
 [0.22, 0.141, 0.232, 0.266],
 [0.345, 0.398, 0.183, 0.238],
 [0.56, 0.42, 0.389, 0.394],
 [0.424, 0.628, 0.509, 0.48],
 [1.307, 1.199, 1.26, 1.304],
 [0.224, 0.341, 0.286, 0.149],
 [0.336, 0.331, 0.294, 0.437],
 [1.26, 1.426, 1.526, 1.216],
 [0.302, 0.374, 0.216, 0.302],
 [0.518, 0.389, 0.334, 0.348],
 [0.124, 0.25, 0.287, 0.209],
 [0.553, 0.52, -1.0, 0.546],
 [0.33, 0.475, 0.399, 0.301],
 [0.196, 0.305, 0.313, 0.438],
 [0.27, 0.261, 0.336, 0.33],
 [0.329, 0.217, 0.29, 0.351],
 [0.718, 0.218, 0.281, 0.248],
 [0.28, 0.271, 0.279, 0.285],
 [0.139, -1.0, 0.137, 0.129],
 [0.366, 0.399, 0.315, 0.223],
 [0.338, 0.349, 0.308, 0.526],
 [0.377, 0.777, 0.676, 0.417],
 [1.111, 1.174, 1.022, 0.963],
 [0.581, -1.0, 0.53, 0.612],
 [0.243, 0.191, 0.194, 0.141],
 [0.401, 0.324, 0.362, 0.385],
 [0.572, 0.486, 0.545, 0.758],
 [0.419, 0.449, 0.485, 0.496],
 [0.432, 0.326, 0.35, 0.476],
 [0.237, 0.117, 0.284, 0.219],
 [0.48, 0.64, 0.549, 0.428],
 [0.315, 0.271, 0.336, 0.416],
 [0.201, 0.222, 0.192, 0.299],
 [0.141, 0.151, 0.123, 0.109],
 [0.193, 0.273, 0.142, 0.213],
 [0.207, 0.145, 0.073, 0.178],
 [0.245, 0.243, 0.22, 0.224],
 [0.234, 0.213, 0.191, 0.155],
 [0.185, 0.299, 0.274, 0.352],
 [0.345, 0.326, 0.365, 0.4],
 [0.54, 0.46, 0.52, 0.49],
 [0.081, 0.165, 0.212, 0.138],
 [0.165, 0.319, 0.236, 0.194],
 [0.312, 0.463, 0.315, 0.367],
 [0.246, 0.223, 0.304, 0.278],
 [0.347, 0.396, 0.353, 0.356],
 [0.657, 0.686, 0.494, 0.485],
 [0.184, 0.172, 0.222, 0.145],
 [1.219, 1.486, 1.181, 1.311],
 [0.438, 0.415, 0.264, 0.373],
 [0.286, 0.332, 0.409, 0.468],
 [0.277, 0.328, 0.181, 0.216],
 [0.293, 0.336, 0.404, 0.445],
 [0.071, 0.104, 0.143, 0.101],
 [0.268, 0.226, 0.21, 0.211],
 [0.438, 0.79, 0.634, 0.533],
 [0.413, 0.404, 0.431, 0.361],
 [1.117, 1.112, 1.089, 1.223],
 [0.287, 0.334, 0.395, 0.283],
 [0.429, 0.258, 0.412, 0.285],
 [2.68, 2.81, 2.71, 2.93],
 [0.265, 0.255, 0.35, 0.259],
 [0.794, 0.949, 0.863, 0.894],
 [0.382, 0.401, 0.425, 0.461],
 [0.663, 0.648, 0.586, 0.522],
 [0.439, 0.339, 0.29, 0.463],
 [1.238, 1.235, 1.265, 0.991],
 [1.135, 1.03, 0.999, 1.055],
 [0.393, 0.459, 0.359, 0.322],
 [0.208, 0.16, 0.319, 0.264],
 [0.199, 0.186, 0.172, 0.221],
 [0.468, 0.494, 0.482, 0.434],
 [0.182, 0.103, 0.224, 0.217],
 [1.282, 1.247, 1.316, 1.212],
 [0.235, 0.254, 0.288, 0.272],
 [0.331, 0.442, 0.349, 0.31],
 [0.198, 0.36, 0.244, 0.224],
 [0.435, 0.555, 0.396, 0.482],
 [0.707, 0.915, 0.871, 0.758],
 [0.846, 0.895, 0.886, 0.86],
 [0.268, 0.21, 0.21, 0.213],
 [0.318, 0.262, 0.385, 0.292],
 [0.071, 0.113, 0.129, 0.131],
 [0.288, 0.259, 0.207, 0.254],
 [0.837, 0.737, 0.878, 0.793],
 [0.216, 0.24, 0.234, 0.248],
 [0.308, 0.404, 0.348, 0.376],
 [0.26, 0.36, 0.32, 0.32],
 [0.361, 0.376, 0.485, 0.349],
 [0.327, 0.381, 0.354, 0.425],
 [0.389, 0.265, 0.291, 0.297],
 [0.168, 0.19, 0.23, 0.169],
 [0.668, 0.403, 0.788, 0.666],
 [0.258, 0.379, 0.318, 0.401],
 [0.542, 0.628, 0.566, 0.584],
 [0.249, 0.194, 0.239, 0.187],
 [0.262, 0.348, 0.33, 0.296],
 [0.188, 0.226, 0.295, 0.294],
 [0.251, 0.453, 0.328, 0.335],
 [0.259, 0.275, 0.283, 0.159],
 [0.294, 0.242, 0.188, 0.239],
 [0.432, 0.365, 0.423, 0.482],
 [0.281, 0.299, 0.322, 0.389],
 [0.457, 0.46, 0.425, 0.362],
 [0.422, 0.414, 0.449, 0.503],
 [0.105, 0.178, 0.179, 0.14],
 [0.1, -1.0, 0.112, 0.138],
 [0.531, 0.404, 0.488, 0.419],
 [0.338, 0.374, 0.224, 0.273],
 [0.512, 0.577, 0.576, 0.622],
 [0.273, 0.122, 0.104, 0.15],
 [0.369, 0.407, 0.528, 0.522],
 [0.264, 0.2, 0.161, 0.135],
 [0.184, 0.159, 0.176, 0.168],
 [1.442, 1.605, 1.525, 1.357],
 [0.333, 0.367, 0.334, 0.312],
 [0.36, 0.389, 0.374, 0.367],
 [0.367, 0.457, 0.324, 0.331],
 [0.391, 0.474, 0.38, 0.448],
 [0.32, 0.161, 0.196, 0.213],
 [1.186, 1.129, 1.111, 1.25],
 [0.335, 0.291, 0.35, 0.299],
 [0.365, 0.256, 0.309, 0.324],
 [0.185, 0.263, 0.258, 0.263],
 [0.356, 0.293, 0.317, 0.395],
 [0.506, 0.279, 0.429, 0.412],
 [0.371, 0.602, 0.413, 0.577],
 [0.77, 0.79, 0.65, 0.88],
 [0.352, 0.349, 0.393, 0.435],
 [0.696, 0.866, 0.709, 0.64],
 [0.744, 0.879, 0.805, 0.975],
 [0.22, 0.259, 0.327, 0.316],
 [0.327, 0.391, 0.504, 0.482],
 [0.262, 0.182, 0.242, 0.247],
 [0.713, 1.086, 0.81, 0.969],
 [0.513, 0.603, 0.613, 0.57],
 [0.162, 0.172, 0.196, 0.269],
 [0.601, 0.637, 0.835, 0.555],
 [0.242, 0.243, 0.281, 0.21],
 [0.34, 0.34, 0.3, 0.38],
 [0.402, 0.238, 0.242, 0.282],
 [0.307, 0.302, 0.263, 0.269],
 [0.174, 0.204, 0.198, 0.15],
 [0.338, 0.315, 0.412, 0.317],
 [0.346, 0.34, 0.377, 0.254],
 [0.3, 0.277, 0.276, 0.338],
 [0.252, 0.364, 0.303, 0.287],
 [0.724, 0.711, 0.701, 0.723],
 [0.28, 0.375, 0.258, 0.399],
 [0.717, 0.767, 0.712, 0.77],
 [0.335, 0.229, 0.25, 0.36],
 [0.204, 0.16, 0.131, 0.192],
 [0.544, 0.561, 0.633, 0.543],
 [0.406, 0.4, 0.404, 0.504],
 [0.443, 0.426, 0.427, 0.34],
 [0.367, 0.227, 0.225, 0.565],
 [0.183, 0.261, 0.204, 0.243],
 [0.583, 0.543, 0.674, 0.486],
 [0.15, 0.201, 0.183, 0.157],
 [0.187, 0.293, 0.299, 0.261],
 [0.028, 0.061, 0.072, 0.032],
 [0.275, 0.293, 0.185, 0.321],
 [0.466, 0.446, 0.53, 0.462],
 [0.466, 0.466, 0.406, 0.533]]

In [24]:
evaluation_data_materials['Real volume losses'] = real_volume_losses

In [25]:
new_names = []
for i in range(len(evaluation_data_materials['Compound number'])):
    new_names.append(names_dict[evaluation_data_materials['Compound number'][i]])
print(new_names)

['2-2-Bipyridine-4-4-dicarboxylic acid', 'Phytic acid', 'Pyrazole', 'NaCl', 'N-Lauroylsarcosine Na', 'Citric acid', 'TAPS', '1,2,3-Benzenetricarboxylic acid hydrate', 'Glucose', 'Cinnamaldehyde, (E)-', 'Maleic acid', 'Terephthalic acid', 'EPPS', '3-Hydroxy-4-nitrobenzoic acid', '8-Nitroquinoline', '1,2,3,4-Butanetetracarboxylic acid', 'Salicylic acid', '3 5-DIMETHYLPYRAZOLE-1-METHANOL  99%', '4-Isopropylbenzoic acid', 'NaCl', '2-Amino-2-methyl-1,3-propanediol', 'Fumaric acid', '1-Pheny-1,3-butanedione', '3-Amino-4-Hydroxybenzoic acid', '3-Hydroxybenzoic acid', '2-Nitrobenzoic acid', 'BIS-TRIS', '1-2-4-5-Benzenetetracarboxylic acid', 'Malic acid', '3,4-Dihydroxybenzoic acid', '3,4-Pyridinedicarboxylic acid', 'lysine', 'Decylphosphonic acid', 'Acetic acid', 'NaCl', '2-Amino-5-trifluoromethyl-1,3,4-thiadiazole', 'Adipic acid', 'NaCl', 'Chitosan', 'Ascorbic acid', 'Iminodiacetic acid', 'EDTA', 'trans-3-(3-Pyridyl)acrylic acid', 'Nicotinic acid', 'Quinic acid', 'NaCl', 'Acetamide', '2-Aminopyridine-3-carboxylic acid', 'Methionine', '(S)-(+)-Glycidyl benzyl ether', '5-NITRO-1-10-PHENANTHROLINE', '1-(2-Hydroxyethyl)piperazine', 'Citraconic acid', 'NaCl', 'NaCl', '5-Methyl-1,3-dihydro-2H-benzo[d]imidazole-2-thione', 'salicylaldehyde ', 'NaCl', 'n-Octyl gallate', '6-Hydroxyquinoline', 'NaCl', 'Benzamide', 'glycine', 'NaCl', 'Tartronic acid', 'Hypophosphorous acid\xa0', 'Lactic acid', 'Hexamethyleneteramine', "2'-Hydroxy-4'-methoxyaceto-phenone", '3,5-Dinitrosalicylic acid', '1,3-Benzenedimethanol, 2-hydroxy-5-methyl-', 'Salicylaldoxime', 'DIETHYLENETRIAMINE-PENTAACETIC ACID NA5', '4,5-Diamino-2,6-dimercaptopyrimidine', '3-Nitrosalicylic acid', 'BIS-TRIS propane', '2,6-Diamino-4-chloropyrimidine', '2-Hydroxy-1,4-Naphtoquinone', 'Tartaric acid (L-(+)-Tartaric acid,\n L-Threaric acid, (2R,3R)-(+)-Tartaric acid)', '5-Sulfosalicylic acid', 'NaCl', 'Succinic acid', '4-Quinolinol', 'NaCl', 'NaCl', 'NaCl', '4-Aminosalicylic acid', '2-Nitroterephthalic acid', '2-Mercaptopyridine-3-carboxylic acid', 'Hydroquinonesulfonic acid potassium salt', 'CyDTA/TRANS-12-DIAMINO', 'Anthraquinone-2-sulfonic acid sodium salt monohydrate', '4-Amino-6-mercapto-1H-pyrazolo[3,4-d]pyrimidine', '4-Amino-4H-1,2,4-triazole', '6-Mercaptopyridine-3-carboxylic acid', '6-Phosphonohexanoic acid', '1-Undecanethiol', '2,3-Pyridinedicarboxylic acid', 'pyrazine', 'NaCl', 'POTASSIUM L-TARTRATE MONOBASIC  99%', 'Thiourea', '4-Mercaptobenzoic acid', 'Terephthalic acid', 'Lactobionic acid', ' 5-Nitrouracil ', 'Malonic acid', 'Tannic acid', 'NaCl', '4-Methylsalicylic', 'Furylacrylic acid', 'Quinaldic acid', 'Picolinic acid', 'Tricarballylic acid', '8-Hydroxy-7-iodo-5-quinolinesulfonic acid', 'di-Kaliumoxalat Monohydrat', '(ACES) N-(2-Acetamido)-2-aminoethanesulfonic acid', 'NaCl', 'Dimethyl 2,6-pyridinedicarboxylate', '2,6-Pyridinedicarboxylic acid', '3-(4-Pyridyl)acrylic acid', 'Sodium Dodecylbenzene Sulfonate', '4,6-Diamino-2-pyrimidinethiol', 'Kojic acid', 'Cyclohexaneacetic acid', '5,5-Dimethylhydantoin', 'NaCl', 'Cyclohexanemethanol', 'Ethylenediamine', "2,2' Bipyridyl", 'L-Cysteine', 'NaCl', 'sodium-2-mercaptoethanesulfonate', 'Dimethyl 5-hydroxyisophthalate', 'L-Ornithine hydrochloride', '1,2,4-Triazole', 'NaCl', 'NaCl', 'Alginic acid sodium salt from brown algae', 'β-D-Glucopyranose, 4-O-β-D-galactopyranosyl-', '3-Methylcinnamic acid', "2 2'-(ETHYLENEDIOXY)BIS(ETHYLAMINE)  98%", 'NaCl', 'p-Toluic acid', '3-(2-Thienyl)acrylic acid', 'PhenylPhosphonic acid', ' 8-Hydroxy-5-quinoline sulfonic acid', "N-(2-HYDROXYETHYL)ETHYLENEDIAMINE-N N' N trisodium salt", 'tri-Natriumcitrat Dihydrat', 'NaCl', '5-Aminosalicylic acid', 'NaCl', '4-Hydroxybenzoic acid', '2,2′-(Ethylenedithio)diacetic acid', 'NaCl', 'Dimethylolpropionic acid\n2,2-bis(hydroxymethyl)propionic acid', 'NaCl', 'NaCl', '2-(3,5-Dimethylphenyl)acetic acid', 'Glycolic acid', 'Uracil', 'Folic acid', '3-HYDROXY-1 2-DIMETHYL-4(1H)-PYRIDONE  &', '4-Amino-3-hydrazino-5-mercapto-1,2,4-triazole', '2,5-Dimethyl-1,3,4-thiadiazole', 'Mandelic acid', '3,5-Dimethylpyrazole', '4,4′-Dithiodibutyric acid', 'Mellitic acid', '2-Mercapto-1-methylimidazole', 'NaCl', 'NaCl', 'D-Pinitol', 'Trimesic acid', '5-Methylsalicylic acid', 'NaCl', 'NaCl', 'Benzotriazole', '3-Mercaptobenzoic acid', 'Penicillin G Na salt', '2-Amino-5-methyl-salicylic acid ', '3-Methylsalicylic', '3-methyl-2-nitrobenzoic acid', 'p-Phenylenediacetic acid', 'Pyrazinecarboxylic acid', 'Thiosalicylic acid', '8-Hydroxyquinoline ', '5-Nitrobarbituric acid trihydrate', 'AMPSO', 'NaCl', 'Phthalic acid', 'Dextran', 'NaCl', 'NaCl', '3-Nitrophthalic acid', 'Salicylhydroxamic acid', 'N,N′-Trimethyleneurea', 'L-Asparagine', 'Gly-Gly hydrochloride', 'NaCl', '4-tert-butylbenzoic acid', '2,2′-Thiodiacetic acid', 'N-(2-HYDROXYETHYL)IMINODIACETIC ACID  >&', 'Stearic acid sodium salt', 'Oxalic acid', 'taurine', 'NaCl', 'Sodium Formate', 'Urea', 'Benzoic acid', '2,5-Pyridinedicarboxylic acid', 'NaCl', '2-Mercaptoimidazole', 'Diglycolic acid', 'NaCl', 'Maltol', 'NaCl', 'Aspartic acid/\n\n(S)-Aminobutanedioic acid, (S)-(+)-Aminosuccinic acid, L-Aspartic acid', 'NaCl', '5-AMINO-1 3 4-THIADIAZOLE-2-THIOL  98%', 'Piperazine', '8-Aminoquinoline', '(R)-(−)-Glycidyl benzyl ether', '4-Nitrophthalic acid', 'Itaconic acid', 'Phenylphosphonic acid', '5-Aminoisoquinoline', '1,10-Phenanthroline monohydrate', '1,3,4-thiadiazole-2,5-dithiol (DMTD, bismuthiol) salt', 'D-(+)-Galactose', 'NaCl', 'NaCl']

In [26]:
evaluation_data_materials[['Material name','SMILES', 'Inhibition Efficiency', 'Inhibition efficiency per sample', 'Volume loss predicted each sample', 'Volume loss predicted mean', 'Weight loss NaCl predicted', 'Weight loss NaCl from Ci Song','Compound number']].to_excel("/Users/anna.lisitsyna/Documents/Results_Tim_clip"+str(abs(clip_val))+".xlsx")

In [27]:
evaluation_data_materials[['Material name', 'Real volume losses', 'Volume loss predicted each sample', 'Compound number']]

,Material name,Real volume losses,Volume loss predicted each sample,Compound number
0,2-2-Bipyridine-4-4-dicarboxylic acid,"[0.4, 0.484, 0.35, 0.414]","[1.1732298701919586, 0.6939703579683763, 0.766...",4-5-1
1,Phytic acid,"[0.797, 0.905, 0.853, 0.942]","[0.3845856654619597, 0.6120935722899241, 0.686...",4-6-7
2,Pyrazole,"[0.311, 0.286, 0.262, 0.237]","[0.6952292678062966, 0.6110675743782258, 0.674...",2-2-8
3,NaCl,"[0.402, 0.378, 0.354, 0.405]","[0.28440139716579627, 0.39632081894409354, 0.6...",4-7-6
4,N-Lauroylsarcosine Na,"[0.236, 0.349, 0.311, 0.308]","[0.5261962291366984, 0.45051044025745696, 0.69...",4-5-11
...,...,...,...,...
227,"1,10-Phenanthroline monohydrate","[0.187, 0.293, 0.299, 0.261]","[0.5009861038178468, 0.8049521990595654, 0.458...",4-6-5
228,"1,3,4-thiadiazole-2,5-dithiol (DMTD, bismuthio...","[0.028, 0.061, 0.072, 0.032]","[0.27654490323355213, 0.5902645519208278, 0.56...",4-7-1
229,D-(+)-Galactose,"[0.275, 0.293, 0.185, 0.321]","[0.45311247640386243, 0.3354153526938221, 0.69...",3-1-3
230,NaCl,"[0.466, 0.446, 0.53, 0.462]","[None, None, None, None]",3-1-12
231,NaCl,"[0.466, 0.466, 0.406, 0.533]","[0.743036240240178, 0.8770639902445672, 0.7366...",1-6-9