# Extract volume loss for every sample

In [1]:
from pathlib import Path

import pandas as pd

In [2]:
# Define paths
PROJECT_PATH = Path("/data/dust/user/dammal/beegfs.migration/repos/ai2")
SOURCE_PATH = PROJECT_PATH / "rawdata/results/all-results.xlsx"
TARGET_PATH = PROJECT_PATH / "data/volume-loss/volume-loss.csv"

In [3]:
# Read data from excel
data = pd.read_excel(SOURCE_PATH, skiprows=1, usecols="A,C:G", names=["id", "name", "volumeloss1", "volumeloss2", "volumeloss3", "volumeloss4"])
data

,id,name,volumeloss1,volumeloss2,volumeloss3,volumeloss4
0,1-1-1,Tricarballylic acid,0.347,0.396,0.353,0.356
1,1-1-2,glycine,0.721,0.728,0.916,0.751
2,1-1-3,Tartronic acid,0.263,0.307,0.249,0.213
3,1-1-4,5-Nitrouracil,0.234,0.213,0.191,0.155
4,1-1-5,"2,5-Dimethyl-1,3,4-thiadiazole",0.262,0.348,0.330,0.296
...,...,...,...,...,...,...
294,#4-11-8,"2,4-Dimethoxybenzylakohol redo",0.932,0.549,0.276,0.215
295,#4-11-9,8-Anilino-1-naphthalenesulfonic acid redo,0.716,0.392,0.254,0.128
296,#4-11-10,"4-Hydroxy-3,5-dimethylbenzoic acid",0.682,0.553,0.495,0.367
297,#4-11-11,"3,5-Dimethoxybenzylalcohol",0.323,0.318,0.433,0.454
298,#4-11-12,NaCl,0.304,0.319,0.367,0.396

In [4]:
# Check id names
data[data.id.str.contains("#")]

,id,name,volumeloss1,volumeloss2,volumeloss3,volumeloss4
278,5-1-1 (#3-1-1),BIS-TRIS,0.572,0.596,0.510,0.599
284,#3-3-1,"2,4-Dimethoxybenzyl alcohol",0.585,0.498,0.556,0.364
285,#3-3-2,8-Anilino-1-naphthalenesulfonic acid,0.396,0.406,0.335,0.345
286,#3-3-3,"4-Hydroxy-3,5-dimethylbenzoic acid",0.446,0.427,0.337,0.363
287,#3-3-4,NaCl,0.496,0.450,0.446,0.386
288,#4-4-7,"3,5-Dimethoxyphenylacetic acid",0.439,0.487,0.454,0.529
289,#4-4-8,DL-4-Hydroxy-3-methoxymandelic acid,0.480,0.441,0.584,0.582
290,#4-4-9,6-Aminoindole,0.371,0.379,0.300,0.328
291,#4-4-10,5-Aminoindole,0.385,0.451,0.469,0.408
292,#4-4-11,NaCl,0.595,0.492,0.542,0.452
293,#4-11-7,a-cyano-3-hydroxycinnamic acid,0.663,0.558,0.735,0.853
294,#4-11-8,"2,4-Dimethoxybenzylakohol redo",0.932,0.549,0.276,0.215
295,#4-11-9,8-Anilino-1-naphthalenesulfonic acid redo,0.716,0.392,0.254,0.128
296,#4-11-10,"4-Hydroxy-3,5-dimethylbenzoic acid",0.682,0.553,0.495,0.367
297,#4-11-11,"3,5-Dimethoxybenzylalcohol",0.323,0.318,0.433,0.454
298,#4-11-12,NaCl,0.304,0.319,0.367,0.396

In [5]:
# Replace delete id extension
data["id"] = data["id"].str.replace(" (#3-1-1)", "")

In [6]:
# Replace #s by 1
data["id"] = data["id"].str.replace("#", "1")

In [7]:
data

,id,name,volumeloss1,volumeloss2,volumeloss3,volumeloss4
0,1-1-1,Tricarballylic acid,0.347,0.396,0.353,0.356
1,1-1-2,glycine,0.721,0.728,0.916,0.751
2,1-1-3,Tartronic acid,0.263,0.307,0.249,0.213
3,1-1-4,5-Nitrouracil,0.234,0.213,0.191,0.155
4,1-1-5,"2,5-Dimethyl-1,3,4-thiadiazole",0.262,0.348,0.330,0.296
...,...,...,...,...,...,...
294,14-11-8,"2,4-Dimethoxybenzylakohol redo",0.932,0.549,0.276,0.215
295,14-11-9,8-Anilino-1-naphthalenesulfonic acid redo,0.716,0.392,0.254,0.128
296,14-11-10,"4-Hydroxy-3,5-dimethylbenzoic acid",0.682,0.553,0.495,0.367
297,14-11-11,"3,5-Dimethoxybenzylalcohol",0.323,0.318,0.433,0.454
298,14-11-12,NaCl,0.304,0.319,0.367,0.396

In [8]:
# Put different volume losses to rows and expand id by adding the image identifier
data = data.melt(id_vars=["id", "name"], var_name="lossimage", value_name="volumeloss")
data["id"] = data["id"] + "-" + data["lossimage"].str[-1]
data.drop(["lossimage"], axis=1, inplace=True)
data

              id                                       name  volumeloss
0        1-1-1-1                        Tricarballylic acid       0.347
1        1-1-2-1                                    glycine       0.721
2        1-1-3-1                             Tartronic acid       0.263
3        1-1-4-1                             5-Nitrouracil        0.234
4        1-1-5-1             2,5-Dimethyl-1,3,4-thiadiazole       0.262
...          ...                                        ...         ...
1191   14-11-8-4             2,4-Dimethoxybenzylakohol redo       0.215
1192   14-11-9-4  8-Anilino-1-naphthalenesulfonic acid redo       0.128
1193  14-11-10-4         4-Hydroxy-3,5-dimethylbenzoic acid       0.367
1194  14-11-11-4                 3,5-Dimethoxybenzylalcohol       0.454
1195  14-11-12-4                                       NaCl       0.396

[1196 rows x 3 columns]

In [9]:
# Remove line breaks in names
data.name = data.name.str.replace("\n", "-")

In [10]:
# Export data to CSV
data.to_csv(TARGET_PATH)